/**
 * Diagnostic Booster — Undifferentiated Abdominal Pain Data v3
 * 3-agent retroaudit 全指摘対応済み
 */

export const SYMPTOMS = [
  { id: 'sudden_onset', label: '突然発症', cat: '発症様式' },
  { id: 'colicky', label: '疝痛（波のある痛み）', cat: '発症様式' },
  { id: 'constant', label: '持続痛', cat: '発症様式' },
  { id: 'epigastric', label: '心窩部痛', cat: '部位' },
  { id: 'ruq', label: '右季肋部痛', cat: '部位' },
  { id: 'rlq', label: '右下腹部痛', cat: '部位' },
  { id: 'llq', label: '左下腹部痛', cat: '部位' },
  { id: 'periumbilical', label: '臍周囲痛', cat: '部位' },
  { id: 'lower_abd', label: '下腹部痛', cat: '部位' },
  { id: 'back_pain', label: '腰背部痛', cat: '部位' },
  { id: 'flank_pain', label: '側腹部痛（鼠径部放散）', cat: '部位' },
  { id: 'diffuse', label: '腹部全体', cat: '部位' },
  { id: 'nausea_vomiting', label: '嘔気・嘔吐', cat: '消化器' },
  { id: 'diarrhea', label: '下痢', cat: '消化器' },
  { id: 'constipation', label: '便秘', cat: '消化器' },
  { id: 'no_flatus', label: '排ガス停止', cat: '消化器' },
  { id: 'bloody_stool', label: '血便・黒色便', cat: '消化器' },
  { id: 'fever', label: '発熱', cat: '全身' },
  { id: 'jaundice', label: '黄疸', cat: '全身' },
  { id: 'shock_signs', label: 'ショック徴候（冷汗・蒼白・頻脈）', cat: '全身' },
  { id: 'dysuria', label: '排尿障害・血尿', cat: '泌尿器' },
  { id: 'vaginal_bleeding', label: '不正出血', cat: '婦人科' },
  { id: 'missed_period', label: '月経遅延・妊娠可能', cat: '婦人科' },
];

export const FINDINGS = [
  { id: 'peritoneal_signs', label: '腹膜刺激徴候（筋性防御・反跳痛）', triggers: ['sudden_onset', 'constant', 'diffuse', 'epigastric', 'rlq', 'llq'], weight: 4 },
  { id: 'board_like', label: '板状硬', triggers: ['sudden_onset', 'diffuse', 'epigastric'] },
  { id: 'murphy_sign', label: 'Murphy徴候陽性', triggers: ['ruq', 'fever'] },
  { id: 'mcburney', label: 'McBurney圧痛・Rovsing徴候', triggers: ['rlq', 'periumbilical'] },
  { id: 'pulsatile_mass', label: '拍動性腫瘤', triggers: ['back_pain', 'shock_signs', 'sudden_onset'], weight: 4 },
  { id: 'cva_tenderness', label: 'CVA叩打痛', triggers: ['back_pain', 'dysuria', 'flank_pain'] },
  { id: 'bowel_sounds_absent', label: '腸蠕動音消失', triggers: ['constipation', 'no_flatus', 'diffuse', 'nausea_vomiting'] },
  { id: 'metallic_sounds', label: '腸蠕動音亢進・金属音', triggers: ['colicky', 'constipation', 'no_flatus', 'nausea_vomiting'] },
  { id: 'abdominal_distension', label: '腹部膨満', triggers: ['constipation', 'no_flatus', 'nausea_vomiting'] },
  { id: 'tenderness_llq', label: '左下腹部圧痛', triggers: ['llq', 'fever'] },
  { id: 'uterine_tenderness', label: '子宮圧痛・付属器圧痛', triggers: ['lower_abd', 'vaginal_bleeding', 'missed_period', 'fever'] },
  { id: 'rectal_blood', label: '直腸診: 血液付着', triggers: ['bloody_stool'] },
  { id: 'epigastric_tenderness', label: '心窩部圧痛', triggers: ['epigastric'] },
  { id: 'jaundice_sign', label: '眼球結膜黄染', triggers: ['jaundice', 'ruq'] },
  { id: 'pain_out_of_proportion', label: '痛みの割に腹部所見が乏しい（Pain out of proportion）', triggers: ['sudden_onset', 'periumbilical', 'diffuse'], weight: 4 },
  { id: 'tachycardia', label: '頻脈 HR>100', triggers: [] },
  { id: 'hypotension', label: '収縮期血圧<90', triggers: [] },
];

export const DIFFERENTIALS = [
  // === Killer Abdominal Pain ===
  {
    id: 'aaa_rupture',
    name: '腹部大動脈瘤破裂',
    cat: '血管 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['sudden_onset', 'back_pain', 'shock_signs', 'periumbilical'],
    findings: ['pulsatile_mass', 'hypotension', 'tachycardia'],
    redFlags: ['pulsatile_mass', 'hypotension'],
    nextStep: '即座に救急搬送。静脈路確保・酸素投与。CT施設へ。',
    link: null,
    comment: '高齢男性・喫煙歴・動脈硬化。突然の腹痛+腰背部痛+ショック+拍動性腫瘤。触診は愛護的に。',
  },
  {
    id: 'sma_occlusion',
    name: '上腸間膜動脈閉塞（腸間膜虚血）',
    cat: '血管 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['sudden_onset', 'periumbilical', 'nausea_vomiting', 'diffuse'],
    findings: ['pain_out_of_proportion', 'tachycardia'],
    redFlags: ['shock_signs', 'pain_out_of_proportion'],
    nextStep: '臨床的疑いだけで紹介/搬送の閾値を下げよ。造影CTが確定診断。乳酸値上昇は遅発性。Pain out of proportionは最重要サイン。',
    link: null,
    comment: 'Pain out of proportion（痛みの割に所見が乏しい）が最大の手がかり。Af・動脈硬化リスクの高齢者。血管系イベントは「所見が追いつかない」。',
  },
  {
    id: 'perforation',
    name: '消化管穿孔',
    cat: '外科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    symptoms: ['sudden_onset', 'epigastric', 'diffuse', 'constant'],
    findings: ['board_like', 'peritoneal_signs'],
    redFlags: ['board_like', 'peritoneal_signs'],
    nextStep: '腹部X線（立位: free air）。即外科紹介/搬送。',
    link: null,
    comment: '板状硬+free air=穿孔。NSAIDs・ステロイド・潰瘍歴がリスク。被蓋穿孔では一時的に症状軽減することがあるが、直後に急激悪化する。',
  },
  {
    id: 'ectopic_pregnancy',
    name: '異所性妊娠破裂',
    cat: '婦人科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['lower_abd', 'sudden_onset', 'vaginal_bleeding', 'missed_period', 'shock_signs'],
    findings: ['uterine_tenderness', 'hypotension', 'tachycardia'],
    redFlags: ['hypotension', 'missed_period', 'vaginal_bleeding'],
    nextStep: '尿妊娠反応（必須）。陽性ならエコー+産婦人科紹介/搬送。',
    link: null,
    comment: '妊娠可能年齢女性の腹痛では常に考慮。「妊娠の可能性なし」と言われても妊娠反応を確認せよ。',
  },
  {
    id: 'strangulated_obstruction',
    name: '絞扼性腸閉塞',
    cat: '外科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['colicky', 'nausea_vomiting', 'no_flatus', 'constipation', 'diffuse'],
    findings: ['abdominal_distension', 'metallic_sounds', 'bowel_sounds_absent', 'peritoneal_signs', 'tachycardia'],
    redFlags: ['peritoneal_signs'],
    nextStep: '腹部X線（鏡面像・拡張腸管）。外科紹介/搬送。絶飲食・補液。',
    link: null,
    comment: '腹部手術歴が最大リスク。初期:亢進・金属音→進行:蠕動消失。腹膜刺激徴候出現で絞扼を疑う。',
  },
  // === 高頻度疾患 ===
  {
    id: 'appendicitis',
    name: '急性虫垂炎',
    cat: '外科',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 4,
    symptoms: ['rlq', 'periumbilical', 'nausea_vomiting', 'fever'],
    findings: ['mcburney', 'peritoneal_signs'],
    redFlags: [],
    nextStep: 'Alvarado Score評価。採血（WBC/CRP）。外科紹介（CT評価が必要）。',
    link: null,
    comment: '心窩部/臍周囲痛→右下腹部への移動（migrating pain）が典型。McBurney圧痛+Rovsing徴候。穿孔で汎発性腹膜炎。',
  },
  {
    id: 'cholecystitis',
    name: '急性胆嚢炎',
    cat: '外科 / 消化器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 3,
    symptoms: ['ruq', 'epigastric', 'nausea_vomiting', 'fever'],
    findings: ['murphy_sign', 'jaundice_sign'],
    redFlags: [],
    nextStep: '採血（肝胆道系酵素・炎症・ビリルビン）。消化器内科/外科紹介（エコー・CT評価が必要）。',
    link: '/docs/070-hepatobiliary',
    comment: '右季肋部痛+発熱+Murphy徴候。脂肪食後に悪化。胆管炎（Charcot三徴）に進展する場合あり。',
  },
  {
    id: 'cholelithiasis',
    name: '胆石発作（胆石疝痛）',
    cat: '消化器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['ruq', 'epigastric', 'colicky', 'nausea_vomiting'],
    findings: ['murphy_sign'],
    redFlags: [],
    nextStep: '消化器内科紹介（エコー評価が必要）。鎮痙薬（ブスコパン※緑内障・前立腺肥大に禁忌）で一時的緩和。',
    link: '/docs/070-hepatobiliary',
    comment: '脂肪食後の右季肋部疝痛が典型。発熱がなければ胆嚢炎ではなく胆石発作。',
  },
  {
    id: 'acute_pancreatitis',
    name: '急性膵炎',
    cat: '消化器 / 緊急',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['epigastric', 'back_pain', 'nausea_vomiting', 'constant', 'diffuse'],
    findings: ['epigastric_tenderness'],
    redFlags: [],
    nextStep: '採血（アミラーゼ・リパーゼ）。CT施設へ紹介（重症度判定にCTが必須）。絶飲食・補液。',
    link: null,
    comment: '心窩部痛+背部への放散。前かがみで軽減。アルコール・胆石が2大原因。リパーゼの方がアミラーゼより特異度高い。',
  },
  {
    id: 'peptic_ulcer',
    name: '胃・十二指腸潰瘍',
    cat: '消化器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['epigastric', 'nausea_vomiting', 'bloody_stool'],
    findings: ['epigastric_tenderness'],
    redFlags: [],
    nextStep: 'PPI投与。活動性出血疑い（黒色便/吐血）→PPI静注+緊急内視鏡可能施設へ紹介（止血が優先）。',
    link: '/docs/050-gastroenteritis',
    comment: 'NSAIDs・H.pylori・ストレスがリスク。黒色便は上部消化管出血を示唆。穿孔→消化管穿孔の項参照。',
  },
  {
    id: 'acute_gastroenteritis',
    name: '急性胃腸炎',
    cat: '感染症',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['periumbilical', 'diffuse', 'nausea_vomiting', 'diarrhea', 'fever'],
    findings: [],
    redFlags: [],
    nextStep: '脱水評価。整腸剤・補液。血便→細菌性を考慮（便培養）。',
    link: '/docs/050-gastroenteritis',
    comment: '最も頻度が高い。ウイルス性が大半。血便・持続する高熱は細菌性を疑う。除外診断。',
  },
  {
    id: 'diverticulitis',
    name: '大腸憩室炎',
    cat: '消化器',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['llq', 'rlq', 'fever', 'constant'],
    findings: ['tenderness_llq', 'peritoneal_signs'],
    redFlags: [],
    nextStep: '採血（WBC/CRP）。CT施設へ紹介（穿孔・膿瘍の評価）。軽症なら外来抗菌薬。',
    link: null,
    comment: '左下腹部痛+発熱+便秘傾向。「左側の虫垂炎」。日本人では右側（上行結腸）憩室炎も多い点に注意。穿孔・膿瘍形成で外科緊急。',
  },
  {
    id: 'ureterolithiasis',
    name: '尿管結石',
    cat: '泌尿器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['colicky', 'back_pain', 'flank_pain', 'dysuria', 'rlq', 'llq'],
    findings: ['cva_tenderness'],
    redFlags: [],
    nextStep: '尿検査（血尿）。鎮痛（NSAIDs坐薬※腎障害・消化性潰瘍に注意）。CT施設へ紹介（結石の位置・サイズ評価）。再受診基準: 38℃以上の発熱→腎盂腎炎/敗血症の可能性→即再受診。',
    link: '/docs/250-Urinary-Tract/n201-ureterolithiasis',
    comment: '突然の側腹部〜鼠径部への放散する疝痛。体動で落ち着かない（もがく）。尿潜血陽性が参考。右尿管結石は右下腹部痛として来院することあり。',
  },
  {
    id: 'pyelonephritis',
    name: '急性腎盂腎炎',
    cat: '感染症（細菌）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['back_pain', 'flank_pain', 'fever', 'dysuria'],
    findings: ['cva_tenderness', 'tachycardia'],
    redFlags: [],
    nextStep: '尿検査・尿培養。採血。高熱+全身状態不良は入院対象→紹介。',
    link: '/docs/250-Urinary-Tract/n10-acute-pyelonephritis',
    comment: '女性に多い。高熱+CVA叩打痛が診断的。男性では尿路異常（前立腺肥大・結石）の合併を検索。',
  },
  {
    id: 'ovarian_torsion',
    name: '卵巣嚢腫茎捻転',
    cat: '婦人科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['rlq', 'llq', 'lower_abd', 'sudden_onset', 'nausea_vomiting'],
    findings: ['uterine_tenderness'],
    redFlags: [],
    nextStep: '産婦人科へ紹介/搬送（経腟エコーが必要）。',
    link: null,
    comment: '突然の下腹部痛+嘔気。体位で変動。卵巣嚢腫の既往がリスク。虚血進行で壊死→緊急手術。',
  },
  {
    id: 'pid',
    name: '骨盤内炎症性疾患（PID）',
    cat: '婦人科 / 感染症',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['lower_abd', 'fever', 'vaginal_bleeding'],
    findings: ['uterine_tenderness'],
    redFlags: [],
    nextStep: '内診（子宮頸管圧痛・付属器圧痛）。STI検査。産婦人科紹介。',
    link: null,
    comment: '性活動のある若年女性。下腹部痛+発熱+帯下異常。クラミジア・淋菌が原因。不妊リスクあり。',
  },
  {
    id: 'bowel_obstruction',
    name: '腸閉塞（非絞扼性）',
    cat: '外科',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['colicky', 'nausea_vomiting', 'no_flatus', 'constipation'],
    findings: ['abdominal_distension', 'metallic_sounds'],
    redFlags: [],
    nextStep: '腹部X線（鏡面像）。絶飲食・補液。外科紹介。',
    link: null,
    comment: '腹部手術歴による癒着が最多原因。嘔吐+腹部膨満+排ガス停止。腹膜刺激徴候なし=非絞扼性。',
  },
  {
    id: 'acs_epigastric',
    name: '急性冠症候群（心窩部痛型）',
    cat: '循環器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['epigastric', 'nausea_vomiting', 'constant'],
    findings: ['tachycardia', 'hypotension'],
    redFlags: ['hypotension'],
    nextStep: '12誘導心電図（必須）。トロポニン。ACS確定/疑いなら即循環器施設へ搬送。',
    link: null,
    comment: '心窩部痛として発症するACSは見逃しやすい。糖尿病・高齢者は非典型的。「腹痛の12誘導心電図」を忘れるな。',
    showWhen: { anyOf: ['epigastric', 'cold_sweat', 'tachycardia', 'hypotension', 'shock_signs'] },
  },
  {
    id: 'constipation_functional',
    name: '機能性便秘',
    cat: '消化器',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['lower_abd', 'constipation', 'periumbilical'],
    findings: [],
    redFlags: [],
    nextStep: '腹部X線（便塊確認）。緩下剤。器質的疾患を除外してからの診断。',
    link: null,
    comment: '最も多い腹痛原因の1つ。ただし「便秘」で片付ける前に器質的疾患（大腸癌など）の除外を。50歳以上の新規便秘は要精査。',
  },
  {
    id: 'cholangitis',
    name: '急性胆管炎',
    cat: '外科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    symptoms: ['ruq', 'fever', 'jaundice', 'nausea_vomiting', 'shock_signs'],
    findings: ['murphy_sign', 'jaundice_sign', 'hypotension', 'tachycardia'],
    redFlags: ['hypotension'],
    nextStep: 'Charcot三徴（痛み+発熱+黄疸）で疑う。Reynolds五徴（+ショック+意識障害）は重症。採血（肝胆道系酵素・ビリルビン・炎症）。即消化器内科/外科紹介（ERCP/PTCDが必要）。',
    link: '/docs/070-hepatobiliary',
    comment: '胆嚢炎からの進展or総胆管結石が原因。敗血症に急速進展しうるKiller disease。Reynolds五徴は死亡率高い。',
  },
  {
    id: 'ibs',
    name: '過敏性腸症候群（IBS）',
    cat: '消化器（機能性）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['periumbilical', 'lower_abd', 'diarrhea', 'constipation'],
    findings: [],
    redFlags: [],
    nextStep: 'Rome IV基準で評価。器質的疾患を除外してからの診断。',
    link: '/docs/060-Bowel-Disorder',
    comment: 'ストレスで悪化する腹痛+便通異常。体重減少・血便・発熱・50歳以上の新規発症はIBSでは説明できない→除外診断必須。',
    showWhen: { anyOf: ['periumbilical', 'lower_abd', 'diarrhea', 'constipation'] },
  },
];

export const RED_FLAGS = [
  {
    conditions: ['shock_signs'],
    message: 'ショック徴候: AAA破裂・異所性妊娠破裂・消化管出血を考慮。即座に静脈路確保・酸素投与・救急搬送。',
    severity: 'critical',
  },
  {
    conditions: ['hypotension'],
    message: '低血圧（収縮期<90）: ショック。即座に輸液・搬送準備。',
    severity: 'critical',
  },
  {
    conditions: ['board_like'],
    message: '板状硬: 消化管穿孔を強く疑う。腹部X線（free air確認）。即外科紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['peritoneal_signs'],
    message: '腹膜刺激徴候: 外科的緊急症を考慮。穿孔・虫垂炎穿孔・絞扼性イレウスの鑑別。外科紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['pulsatile_mass'],
    message: '拍動性腫瘤: AAA破裂を疑う。愛護的触診。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['tachycardia'],
    message: '頻脈: 脱水・出血・敗血症・ショック前段階の可能性。バイタル・血圧を再確認し、輸液を考慮。',
    severity: 'warning',
  },
  {
    conditions: ['missed_period'],
    message: '月経遅延/妊娠可能: 異所性妊娠を除外せよ。尿妊娠反応を必ず実施。',
    severity: 'warning',
  },
  {
    conditions: ['vaginal_bleeding'],
    message: '不正出血: 異所性妊娠・卵巣嚢腫茎捻転を考慮。妊娠反応確認+産婦人科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['bloody_stool'],
    message: '血便・黒色便: 消化管出血を考慮。バイタル確認。黒色便は上部出血を示唆。',
    severity: 'warning',
  },
  {
    conditions: ['no_flatus'],
    message: '排ガス停止: 腸閉塞を考慮。腹部X線・外科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['pain_out_of_proportion'],
    message: 'Pain out of proportion（痛みの割に所見が乏しい）: SMA閉塞（腸間膜虚血）を疑う。Af・動脈硬化リスクの高齢者で特に注意。臨床的疑いで即紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['jaundice', 'fever'],
    message: '黄疸+発熱: 急性胆管炎（Charcot三徴）を疑う。敗血症に急速進展しうる。即紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['jaundice'],
    message: '黄疸: 胆管閉塞・膵頭部癌を考慮。肝胆道系酵素+ビリルビン。',
    severity: 'warning',
  },
];
