/**
 * Diagnostic Booster — Undifferentiated Chest Pain Data
 */

export const SYMPTOMS = [
  // 発症・性状
  { id: 'sudden_onset', label: '突然発症', cat: '発症様式' },
  { id: 'exertional', label: '労作時に出現', cat: '発症様式' },
  { id: 'at_rest', label: '安静時に出現', cat: '発症様式' },
  { id: 'pressure', label: '圧迫感・締め付け', cat: '性状' },
  { id: 'tearing', label: '裂けるような痛み', cat: '性状' },
  { id: 'pleuritic', label: '深呼吸・咳で悪化（胸膜痛）', cat: '性状' },
  { id: 'burning', label: '灼熱感・焼けるような', cat: '性状' },
  { id: 'positional', label: '体位で変化（前屈で軽減等）', cat: '性状' },
  { id: 'reproducible', label: '胸壁を押すと同じ痛み', cat: '性状' },
  // 部位・放散
  { id: 'retrosternal', label: '胸骨後部', cat: '部位' },
  { id: 'left_chest', label: '左胸部', cat: '部位' },
  { id: 'back_radiation', label: '背部への放散', cat: '部位' },
  { id: 'arm_jaw_radiation', label: '左肩・左腕・顎への放散', cat: '部位' },
  { id: 'epigastric', label: '心窩部', cat: '部位' },
  // 随伴
  { id: 'cold_sweat', label: '冷汗', cat: '随伴症状' },
  { id: 'nausea_vomiting', label: '嘔気・嘔吐', cat: '随伴症状' },
  { id: 'dyspnea', label: '呼吸困難', cat: '随伴症状' },
  { id: 'syncope', label: '失神・前失神', cat: '随伴症状' },
  { id: 'cough', label: '咳嗽', cat: '随伴症状' },
  { id: 'hemoptysis', label: '喀血', cat: '随伴症状' },
  { id: 'palpitations', label: '動悸', cat: '随伴症状' },
  { id: 'fever', label: '発熱', cat: '随伴症状' },
  { id: 'post_vomiting', label: '嘔吐後に発症', cat: '随伴症状' },
  // リスク
  { id: 'cv_risk', label: '冠危険因子あり（高血圧/DM/脂質/喫煙/家族歴）', cat: 'リスク' },
  { id: 'dvt_risk', label: 'DVTリスク（長期臥床/術後/OC/悪性腫瘍）', cat: 'リスク' },
  { id: 'leg_swelling', label: '下肢腫脹（片側性）', cat: 'リスク' },
];

export const FINDINGS = [
  // 心血管
  { id: 'st_change', label: 'ST変化（上昇/低下）・新規陰性T波', triggers: ['pressure', 'retrosternal', 'arm_jaw_radiation', 'cold_sweat', 'cv_risk'] },
  { id: 'bp_asymmetry', label: '血圧左右差 >20mmHg', triggers: ['tearing', 'back_radiation', 'sudden_onset'] },
  { id: 'new_murmur', label: '新規心雑音', triggers: ['pressure', 'dyspnea'] },
  { id: 'pericardial_rub', label: '心膜摩擦音', triggers: ['positional', 'pleuritic', 'fever'] },
  { id: 'gallop', label: '奔馬調律（S3/S4）', triggers: ['dyspnea', 'pressure'] },
  { id: 'jvd', label: '頸静脈怒張', triggers: ['dyspnea', 'syncope'] },
  // 呼吸器
  { id: 'absent_breath', label: '呼吸音消失（片側）', triggers: ['pleuritic', 'dyspnea', 'sudden_onset'] },
  { id: 'tracheal_deviation', label: '気管偏位', triggers: ['dyspnea', 'sudden_onset'] },
  { id: 'crackles', label: '肺crackles（湿性ラ音）', triggers: ['dyspnea', 'cough'] },
  { id: 'subcutaneous_emphysema', label: '皮下気腫', triggers: ['post_vomiting', 'sudden_onset'] },
  // その他
  { id: 'chest_wall_tenderness', label: '胸壁圧痛（再現性あり）', triggers: ['reproducible', 'pleuritic'] },
  { id: 'unilateral_rash', label: '片側性水疱性皮疹（帯状疱疹）', triggers: ['pleuritic', 'burning'] },
  { id: 'leg_edema_asymmetry', label: '下腿浮腫左右差', triggers: ['leg_swelling', 'dvt_risk'] },
  // バイタル（常時表示）
  { id: 'tachycardia', label: '頻脈 HR>100', triggers: [] },
  { id: 'hypotension', label: '収縮期血圧<90', triggers: [] },
  { id: 'hypoxia', label: 'SpO2 <93%', triggers: [] },
];

export const DIFFERENTIALS = [
  // === Killer Chest Pain 5疾患 ===
  {
    id: 'acs',
    name: '急性冠症候群（ACS）',
    cat: '循環器 / 緊急',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['pressure', 'retrosternal', 'arm_jaw_radiation', 'cold_sweat', 'nausea_vomiting', 'dyspnea', 'exertional', 'cv_risk', 'epigastric'],
    findings: ['st_change', 'tachycardia', 'hypotension', 'gallop', 'new_murmur'],
    redFlags: ['st_change', 'hypotension'],
    nextStep: '12誘導心電図（受付後10分以内）。ACS疑いなら即搬送。アスピリン162-325mg噛砕（大動脈解離を除外した上で）。HEART Score評価。',
    link: null,
    comment: '胸骨後部の圧迫感+冷汗+放散痛が典型。女性・高齢者・糖尿病では非典型的（嘔気・倦怠感・息切れのみ）。心窩部痛型にも注意。',
  },
  {
    id: 'aortic_dissection',
    name: '大動脈解離',
    cat: '血管 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['sudden_onset', 'tearing', 'back_radiation', 'syncope'],
    findings: ['bp_asymmetry', 'new_murmur', 'hypotension'],
    redFlags: ['bp_asymmetry', 'hypotension'],
    nextStep: '両上肢血圧測定（必須）。解離疑いなら抗血小板薬・抗凝固薬は禁忌。即搬送（造影CT必要）。',
    link: null,
    comment: '突然発症の裂けるような激痛+背部放散。痛みが移動する（胸→背→腹）。血圧左右差>20mmHgが手がかり。高血圧・Marfan症候群がリスク。ACSに似たST変化を示すことがある→誤ってアスピリン投与すると致命的。',
  },
  {
    id: 'pulmonary_embolism',
    name: '肺塞栓症',
    cat: '循環器 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['sudden_onset', 'pleuritic', 'dyspnea', 'syncope', 'hemoptysis', 'dvt_risk', 'leg_swelling', 'palpitations'],
    findings: ['tachycardia', 'hypoxia', 'hypotension', 'jvd', 'leg_edema_asymmetry'],
    redFlags: ['hypotension', 'hypoxia'],
    nextStep: 'Wells Score評価。D-dimer・造影CTは当院測定不可のため、Wells高リスクなら臨床判断で即搬送。',
    link: null,
    comment: '突然の呼吸困難+胸膜痛+頻脈。DVTリスク因子（長期臥床・術後・OC・悪性腫瘍・下肢腫脹）を必ず聴取。SpO2低下+頻脈+正常胸部X線=PE疑い。',
  },
  {
    id: 'tension_pneumothorax',
    name: '緊張性気胸',
    cat: '呼吸器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['sudden_onset', 'pleuritic', 'dyspnea'],
    findings: ['absent_breath', 'tracheal_deviation', 'jvd', 'hypotension', 'tachycardia', 'hypoxia'],
    redFlags: ['absent_breath', 'tracheal_deviation', 'hypotension'],
    nextStep: '身体所見で診断可能（X線不要）。脱気処置（18G針で第2肋間鎖骨中線）→即搬送。',
    link: null,
    comment: '呼吸音消失（患側）+気管偏位（健側へ）+頸静脈怒張+ショック。身体所見のみで即座に脱気判断。X線を待たない。',
  },
  {
    id: 'esophageal_rupture',
    name: '食道破裂（Boerhaave症候群）',
    cat: '外科 / 緊急',
    freq: '極めて低頻度',
    prevalenceWeight: 1,
    severityWeight: 5,
    symptoms: ['sudden_onset', 'post_vomiting', 'back_radiation', 'dyspnea'],
    findings: ['subcutaneous_emphysema', 'tachycardia', 'hypotension'],
    redFlags: ['subcutaneous_emphysema'],
    nextStep: '胸部X線（縦隔気腫・左胸水）。即搬送（外科手術が必要）。',
    link: null,
    comment: '嘔吐後の激烈な胸痛+背部痛。Mackler三徴（嘔吐+胸痛+皮下気腫）。皮下気腫の触診（握雪感）がkey finding。死亡率が時間とともに急上昇するため超緊急。',
  },
  // === 非致死的だが重要 ===
  {
    id: 'pneumothorax',
    name: '気胸（非緊張性）',
    cat: '呼吸器',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['sudden_onset', 'pleuritic', 'dyspnea'],
    findings: ['absent_breath'],
    redFlags: [],
    nextStep: '胸部X線。軽症（肺虚脱<15%）は経過観察可。中等症以上は胸腔ドレナージ→紹介。',
    link: null,
    comment: 'やせ型の若年男性に好発（自然気胸）。突然の胸痛+呼吸困難。患側の呼吸音減弱。緊張性への移行に注意。',
  },
  {
    id: 'pericarditis',
    name: '急性心膜炎',
    cat: '循環器',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 2,
    symptoms: ['pleuritic', 'positional', 'fever', 'retrosternal'],
    findings: ['pericardial_rub', 'st_change'],
    redFlags: [],
    nextStep: '12誘導心電図（広範なST上昇+PR低下が特徴的）。心嚢液評価のため循環器紹介（心エコーは当院不可）。NSAIDs+コルヒチン。',
    link: null,
    comment: '前屈位で軽減する胸痛+心膜摩擦音が特徴的。ウイルス感染後に多い。ACSとの鑑別: ST上昇が広範（誘導をまたぐ）+reciprocal changeがない。心タンポナーデへの移行に注意。',
  },
  {
    id: 'myocarditis',
    name: '急性心筋炎',
    cat: '循環器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['dyspnea', 'palpitations', 'fever', 'retrosternal'],
    findings: ['tachycardia', 'gallop', 'st_change', 'hypotension'],
    redFlags: ['hypotension'],
    nextStep: '12誘導心電図+胸部X線。心不全徴候があれば即紹介/搬送。若年者の感冒後の心不全を疑え。',
    link: null,
    comment: '感冒後1-2週の若年者の胸痛+心不全症状。劇症型は急速にショックに進展。トロポニン・BNPは当院測定不可→心筋炎疑いなら即紹介。',
  },
  {
    id: 'pneumonia',
    name: '肺炎',
    cat: '感染症',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 3,
    symptoms: ['pleuritic', 'cough', 'fever', 'dyspnea'],
    findings: ['crackles', 'tachycardia', 'hypoxia'],
    redFlags: [],
    nextStep: '胸部X線。A-DROP評価。',
    link: '/docs/020-Pneumonia',
    comment: '咳+発熱+胸膜痛。胸部X線で浸潤影確認。A-DROP 2点以上は紹介。',
  },
  {
    id: 'pleuritis',
    name: '胸膜炎',
    cat: '呼吸器',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['pleuritic', 'cough', 'fever', 'dyspnea'],
    findings: ['crackles'],
    redFlags: [],
    nextStep: '胸部X線（胸水確認）。原因検索（感染・膠原病・悪性腫瘍）。',
    link: null,
    comment: '深呼吸で悪化する鋭い胸痛。肺炎随伴性・ウイルス性・結核性・悪性胸水の鑑別。大量胸水は紹介。',
  },
  {
    id: 'gerd',
    name: 'GERD（逆流性食道炎）',
    cat: '消化器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['burning', 'retrosternal', 'epigastric', 'nausea_vomiting'],
    findings: [],
    redFlags: [],
    nextStep: 'PPI試験投与。改善なし→上部消化管内視鏡紹介。再受診基準: 胸痛が安静時に持続(>20分)、冷汗→ACS除外のため即受診。',
    link: '/docs/050-gastroenteritis',
    comment: '食後・臥位で悪化する胸骨後部の灼熱感。PPI反応性が診断的。ただしACSを除外してから。',
  },
  {
    id: 'musculoskeletal',
    name: '筋骨格性胸痛',
    cat: '筋骨格',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['reproducible', 'pleuritic'],
    findings: ['chest_wall_tenderness'],
    redFlags: [],
    nextStep: 'NSAIDs。Killer疾患を除外した上での除外診断。再受診基準: 冷汗を伴う胸痛再発、安静時の持続する胸痛(>20分)、失神、呼吸困難悪化→即救急要請。',
    link: null,
    comment: '胸壁圧痛の再現性が最大の手がかり。ただし「押して痛い＝筋骨格」と短絡しない。ACSでも胸壁圧痛を認めることがある（感度特異度ともに低い）。Killer疾患を除外してから診断。',
  },
  {
    id: 'intercostal_neuralgia',
    name: '肋間神経痛',
    cat: '神経',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['pleuritic', 'left_chest'],
    findings: ['chest_wall_tenderness'],
    redFlags: [],
    nextStep: 'NSAIDs。帯状疱疹前駆期との鑑別（2-3日後に皮疹出現あり）。再受診基準: 冷汗・安静時胸痛(>20分)→即受診。',
    link: null,
    comment: '片側の肋骨に沿った刺すような痛み。体動で悪化。帯状疱疹前駆期（皮疹前の神経痛）の可能性を念頭に。',
  },
  {
    id: 'herpes_zoster',
    name: '帯状疱疹（胸壁）',
    cat: '感染症（ウイルス）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['pleuritic', 'burning', 'left_chest'],
    findings: ['unilateral_rash'],
    redFlags: [],
    nextStep: '抗ウイルス薬（バラシクロビル）72時間以内。皮疹前の前駆痛期間があることに注意。',
    link: null,
    comment: '片側のデルマトームに沿う水疱+灼熱痛。皮疹出現前は肋間神経痛やACSと誤認されうる。高齢者・免疫低下者に注意。',
  },
  {
    id: 'panic_disorder',
    name: 'パニック障害',
    cat: '精神科',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['palpitations', 'dyspnea', 'left_chest', 'at_rest'],
    findings: [],
    redFlags: [],
    nextStep: 'Killer疾患を除外した上での診断。過換気があれば紙袋呼吸は推奨されない。精神科/心療内科紹介。',
    link: '/docs/170-psychiatry',
    comment: '若年者の反復性胸痛+動悸+過換気+四肢しびれ。除外診断であり、初発時はKiller疾患を必ず除外。「パニックだろう」は最後の診断。',
    alwaysShow: true,
  },
  {
    id: 'costochondritis',
    name: '肋軟骨炎（Tietze症候群）',
    cat: '筋骨格',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['reproducible', 'left_chest', 'retrosternal'],
    findings: ['chest_wall_tenderness'],
    redFlags: [],
    nextStep: 'NSAIDs。2-4週で自然軽快。再受診基準: 冷汗を伴う胸痛、安静時胸痛(>20分)、呼吸困難→即受診。',
    link: null,
    comment: '肋軟骨接合部の圧痛・腫脹。特に第2-3肋軟骨。若年者に多い。除外診断。',
  },
  {
    id: 'heart_failure',
    name: '急性心不全（増悪）',
    cat: '循環器',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['dyspnea', 'at_rest', 'retrosternal', 'palpitations'],
    findings: ['crackles', 'jvd', 'gallop', 'hypoxia', 'tachycardia'],
    redFlags: ['hypoxia'],
    nextStep: '胸部X線（肺うっ血・心拡大）。12誘導心電図。酸素投与。循環器紹介/搬送。',
    link: null,
    comment: '起座呼吸・発作性夜間呼吸困難が特徴。既往歴（心不全・弁膜症・心筋症）を聴取。BNP測定が有用だが当院不可→紹介。',
  },
  {
    id: 'atrial_fibrillation',
    name: '心房細動（新規発症・頻脈性）',
    cat: '循環器',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    resolvedStillDangerous: true,
    symptoms: ['palpitations', 'dyspnea', 'at_rest'],
    findings: ['tachycardia'],
    redFlags: [],
    nextStep: '12誘導心電図（絶対性不整脈確認）。HR>150 or 血行動態不安定→搬送。安定なら循環器紹介。',
    link: null,
    comment: '胸痛よりも動悸・息切れが主訴のことが多い。脈の不整が手がかり。新規Afは心不全・弁膜症・甲状腺機能亢進の検索が必要。',
  },
];

export const RED_FLAGS = [
  {
    conditions: ['hypotension'],
    message: 'ショック: ACS・大動脈解離・massive PE・緊張性気胸を考慮。即搬送準備。',
    severity: 'critical',
  },
  {
    conditions: ['st_change'],
    message: 'ST変化: ACS（STEMI/NSTEMI）を強く疑う。両上肢血圧で解離を除外→アスピリン→即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['bp_asymmetry'],
    message: '血圧左右差>20mmHg: 大動脈解離を疑う。抗血小板薬・抗凝固薬は禁忌。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['absent_breath'],
    message: '呼吸音消失（片側）: 緊張性気胸を疑う。気管偏位+JVD+ショックなら即座に脱気。X線を待たない。',
    severity: 'critical',
  },
  {
    conditions: ['tracheal_deviation'],
    message: '気管偏位: 緊張性気胸を強く示唆。即座に脱気処置+搬送。',
    severity: 'critical',
  },
  {
    conditions: ['subcutaneous_emphysema'],
    message: '皮下気腫: 食道破裂（Boerhaave）または気胸を疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['hypoxia'],
    message: 'SpO2<93%: 酸素投与。PE・肺炎・心不全・気胸を鑑別。',
    severity: 'warning',
  },
  {
    conditions: ['tachycardia'],
    message: '頻脈: PE・ショック前段階・Afを考慮。12誘導心電図+SpO2確認。',
    severity: 'warning',
  },
  {
    conditions: ['cold_sweat'],
    message: '冷汗: ACSを強く疑う所見。12誘導心電図を即座に。',
    severity: 'warning',
  },
  {
    conditions: ['syncope'],
    message: '失神: PE・大動脈解離・不整脈・ACSを考慮。バイタル+心電図+搬送準備。',
    severity: 'warning',
  },
  {
    conditions: ['hemoptysis'],
    message: '喀血: PE・肺癌・結核を考慮。胸部X線+搬送検討。',
    severity: 'warning',
  },
];
