/**
 * Diagnostic Booster — Undifferentiated Dizziness Data v2
 * 3-agent audit v1指摘 全件対応済み
 */

export const SYMPTOMS = [
  { id: 'vertigo', label: '回転性めまい（vertigo）', cat: '性状' },
  { id: 'floating', label: '浮動性めまい（ふわふわ）', cat: '性状' },
  { id: 'presyncope', label: '前失神感（立ちくらみ・目の前が暗く）', cat: '性状' },
  { id: 'disequilibrium', label: '平衡障害（まっすぐ歩けない）', cat: '性状' },
  { id: 'sudden_onset', label: '突然発症', cat: '発症様式' },
  { id: 'positional', label: '頭位変換で誘発', cat: '発症様式' },
  { id: 'on_standing', label: '起立時に誘発', cat: '発症様式' },
  { id: 'at_rest', label: '安静時にも持続', cat: '発症様式' },
  { id: 'seconds', label: '秒〜1分で消失', cat: '持続時間' },
  { id: 'minutes_hours', label: '数分〜数時間持続', cat: '持続時間' },
  { id: 'days', label: '数日以上持続', cat: '持続時間' },
  { id: 'recurrent', label: '反復性', cat: '持続時間' },
  { id: 'hearing_loss', label: '聴力低下（片側）', cat: '随伴症状' },
  { id: 'tinnitus', label: '耳鳴・耳閉感', cat: '随伴症状' },
  { id: 'headache', label: '頭痛', cat: '随伴症状' },
  { id: 'diplopia', label: '複視', cat: '随伴症状' },
  { id: 'dysarthria', label: '構音障害（ろれつが回らない）', cat: '随伴症状' },
  { id: 'dysphagia', label: '嚥下障害', cat: '随伴症状' },
  { id: 'limb_weakness', label: '四肢麻痺・しびれ', cat: '随伴症状' },
  { id: 'nausea_vomiting', label: '嘔気・嘔吐', cat: '随伴症状' },
  { id: 'palpitations', label: '動悸', cat: '随伴症状' },
  { id: 'cv_risk', label: '脳血管リスク（高血圧/DM/Af/喫煙）', cat: 'リスク' },
  { id: 'antihypertensive', label: '降圧薬・α遮断薬使用中', cat: 'リスク' },
  { id: 'ototoxic_drug', label: '耳毒性薬剤（アミノグリコシド等）', cat: 'リスク' },
];

export const FINDINGS = [
  { id: 'hit_negative', label: 'Head Impulse Test（HIT）陰性', triggers: ['vertigo', 'sudden_onset', 'days', 'at_rest'] },
  { id: 'hit_positive', label: 'Head Impulse Test（HIT）陽性', triggers: ['vertigo', 'sudden_onset', 'days', 'at_rest'] },
  { id: 'direction_changing_nystagmus', label: '方向交代性眼振', triggers: ['vertigo', 'sudden_onset', 'days'] },
  { id: 'skew_deviation', label: 'Skew deviation（交代遮蔽で垂直偏位）', triggers: ['vertigo', 'sudden_onset', 'days'] },
  { id: 'dix_hallpike_positive', label: 'Dix-Hallpike陽性（上眼瞼向き回旋性眼振+潜時）', triggers: ['positional', 'seconds', 'vertigo', 'recurrent'] },
  { id: 'cerebellar_ataxia', label: '小脳失調（指鼻試験異常・失調性歩行）', triggers: ['disequilibrium', 'vertigo', 'sudden_onset'] },
  { id: 'truncal_ataxia', label: '体幹失調（座位保持困難）', triggers: ['disequilibrium', 'nausea_vomiting'] },
  { id: 'focal_deficit', label: '神経巣症状（片麻痺・感覚障害・Horner）', triggers: ['limb_weakness', 'diplopia', 'dysarthria', 'dysphagia'] },
  { id: 'orthostatic_drop', label: '起立性血圧低下（収縮期≥20 or 拡張期≥10mmHg低下）', triggers: ['presyncope', 'on_standing', 'antihypertensive'] },
  { id: 'irregular_pulse', label: '脈不整', triggers: [] },
  { id: 'bradycardia', label: '徐脈 HR<50', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 中枢性（Killer Dizziness）===
  {
    id: 'cerebellar_stroke',
    name: '小脳梗塞・小脳出血',
    cat: '脳血管 / 緊急',
    freq: '低頻度',
    symptoms: ['vertigo', 'sudden_onset', 'days', 'nausea_vomiting', 'headache', 'disequilibrium', 'cv_risk'],
    findings: ['hit_negative', 'direction_changing_nystagmus', 'skew_deviation', 'cerebellar_ataxia', 'truncal_ataxia'],
    redFlags: ['hit_negative', 'direction_changing_nystagmus', 'skew_deviation', 'cerebellar_ataxia', 'truncal_ataxia'],
    nextStep: 'HINTS中枢パターン（HIT陰性+方向交代性眼振+skew deviation）→即搬送。※HINTS examは訓練を受けた医師が実施した場合に高い診断精度を持つ（Kattah JC et al. Stroke 2009: 感度100%, 特異度96%）。非訓練者では偽陰性/偽陽性が増加するため、HINTS陰性でも臨床的に中枢性を疑えば搬送をためらわないこと。初回MRI-DWIは48h以内で偽陰性あり。',
    link: null,
    comment: 'めまい診療で最も怖いのは「よくあるめまい」として帰宅させた小脳梗塞。BPPVやメニエールに酷似しうる。「いつものめまいと違う」「嘔吐が止まらない」「まっすぐ歩けない」→即日画像精査。',
  },
  {
    id: 'brainstem_stroke',
    name: '脳幹梗塞',
    cat: '脳血管 / 緊急',
    freq: '低頻度',
    symptoms: ['vertigo', 'sudden_onset', 'days', 'diplopia', 'dysarthria', 'dysphagia', 'limb_weakness', 'cv_risk'],
    findings: ['hit_negative', 'focal_deficit', 'skew_deviation'],
    redFlags: ['focal_deficit', 'dysarthria'],
    nextStep: '神経巣症状あり→即搬送。発症4.5h以内ならt-PA適応あり。',
    link: null,
    comment: '複視・構音障害・嚥下障害・交叉性感覚障害・Horner症候群など脳幹徴候。Wallenberg症候群（後下小脳動脈閉塞）は回転性めまい+嚥下障害+Horner+交叉性感覚障害。',
  },
  {
    id: 'vba_insufficiency',
    name: '椎骨脳底動脈循環不全',
    cat: '脳血管',
    freq: '低〜中頻度',
    symptoms: ['vertigo', 'cv_risk', 'diplopia', 'headache'],
    findings: ['focal_deficit'],
    redFlags: [],
    nextStep: '一過性であっても脳血管精査が必要。MRA施設へ紹介。',
    link: null,
    comment: '高齢者の一過性めまい+後方循環症状（複視・構音障害・ふらつき）。TIA（一過性脳虚血発作）の可能性→ABCD2スコア評価。頸部回旋で誘発される場合あり。',
  },
  // === 末梢性 ===
  {
    id: 'bppv',
    name: '良性発作性頭位めまい症（BPPV）',
    cat: '末梢性前庭',
    freq: '極めて高頻度',
    symptoms: ['vertigo', 'positional', 'seconds', 'recurrent', 'nausea_vomiting'],
    findings: ['dix_hallpike_positive', 'hit_positive'],
    redFlags: [],
    nextStep: 'Dix-Hallpike陽性→Epley法（耳石置換法）実施。治療後めまい消失を確認。※Dix-Hallpike陰性や非典型パターン（潜時なし・減衰しない眼振・下眼瞼向き眼振）の場合は中枢性を除外せよ→HINTS exam実施またはCT/MRI施設へ紹介。',
    link: '/docs/150-Vertigo',
    comment: '最も頻度の高いめまい。頭位変換で回転性めまいが誘発され、1分以内に消失する。上眼瞼向き回旋性眼振＋潜時あり（2-5秒）。Epley法の成功率は約80%。非典型パターンや改善しない場合は中枢性除外を怠らないこと。',
  },
  {
    id: 'menieres',
    name: 'メニエール病',
    cat: '末梢性前庭',
    freq: '中頻度',
    symptoms: ['vertigo', 'hearing_loss', 'tinnitus', 'minutes_hours', 'recurrent', 'nausea_vomiting'],
    findings: ['hit_positive'],
    redFlags: [],
    nextStep: '耳鼻科紹介（聴力検査を含む精査）。発作時: 制吐剤+安静。予防: 減塩+イソソルビド。',
    link: '/docs/150-Vertigo',
    comment: '三徴: 回転性めまい+低音障害型感音難聴+耳鳴。発作は20分〜数時間持続。発作間欠期は無症状。反復し聴力が段階的に悪化。',
  },
  {
    id: 'vestibular_neuritis',
    name: '前庭神経炎',
    cat: '末梢性前庭',
    freq: '中頻度',
    symptoms: ['vertigo', 'sudden_onset', 'days', 'nausea_vomiting', 'at_rest'],
    findings: ['hit_positive'],
    redFlags: [],
    nextStep: 'HIT陽性=末梢性を支持。聴力正常を確認。対症療法（メリスロン+制吐剤）。前庭リハビリ。※HIT陽性が得られない場合やHIT陰性の場合は小脳梗塞を除外→HINTS中枢パターン確認→搬送を検討。',
    link: '/docs/150-Vertigo',
    comment: '突発性の持続する回転性めまい。聴力は正常（メニエールとの鑑別点）。ウイルス感染後に発症することが多い。自然経過で数日〜数週で改善。HIT陽性が末梢性の証拠。',
  },
  {
    id: 'sudden_hearing_loss',
    name: '突発性難聴',
    cat: '耳鼻',
    freq: '低〜中頻度',
    symptoms: ['hearing_loss', 'tinnitus', 'vertigo', 'sudden_onset'],
    findings: ['hit_positive'],
    redFlags: [],
    nextStep: '72時間以内のステロイド開始が推奨。即日耳鼻科紹介。',
    link: null,
    comment: '突然の片側感音難聴（3周波数以上で30dB以上低下）。めまいを伴うのは約30%。聴力回復にはステロイド早期開始が重要→耳鼻科緊急紹介。',
  },
  // === 非前庭性 ===
  {
    id: 'orthostatic_hypotension',
    name: '起立性低血圧',
    cat: '循環器',
    freq: '高頻度',
    symptoms: ['presyncope', 'on_standing', 'antihypertensive'],
    findings: ['orthostatic_drop'],
    redFlags: [],
    nextStep: '臥位→立位3分後の血圧測定。原因検索: 脱水・消化管出血（黒色便）・副腎不全・薬剤性（降圧薬・α遮断薬・三環系）。',
    link: '/docs/090-Cardiovascular',
    comment: '臥位→立位で収縮期≥20mmHg or 拡張期≥10mmHg低下。高齢者の「立ちくらみ」で最多。降圧薬過量は見直し。黒色便→消化管出血の除外を忘れるな。',
  },
  {
    id: 'arrhythmia',
    name: '不整脈（徐脈性・頻脈性）',
    cat: '循環器',
    freq: '中頻度',
    symptoms: ['presyncope', 'palpitations', 'floating'],
    findings: ['irregular_pulse', 'bradycardia'],
    redFlags: ['bradycardia'],
    nextStep: '12誘導心電図。24時間ホルター心電図（循環器紹介）。失神を伴えば即紹介。',
    link: null,
    comment: '一過性のふわっとするめまい+動悸。脈不整の触診がスクリーニング。完全房室ブロック・洞不全症候群→ペースメーカー適応あり。新規Af→脳塞栓リスク評価が必要。',
  },
  {
    id: 'anemia',
    name: '貧血',
    cat: '血液',
    freq: '中頻度',
    symptoms: ['floating', 'presyncope', 'on_standing'],
    findings: [],
    redFlags: [],
    nextStep: 'CBC確認。鉄欠乏→原因検索（消化管出血・月経過多）。Hb<7は輸血検討→紹介。',
    link: null,
    comment: '慢性のふわふわするめまい+労作時息切れ+顔色不良。急性発症なら消化管出血を疑え。',
  },
  {
    id: 'drug_induced',
    name: '薬剤性めまい',
    cat: '薬剤性',
    freq: '中頻度',
    symptoms: ['floating', 'disequilibrium', 'antihypertensive', 'ototoxic_drug'],
    findings: ['orthostatic_drop'],
    redFlags: [],
    nextStep: '被疑薬の同定。用量調整or代替薬への変更。アミノグリコシド→聴力・前庭機能モニタリング。',
    link: null,
    comment: '降圧薬過量→起立性低血圧。アミノグリコシド→前庭毒性（bilateral vestibulopathy）。三環系抗うつ薬・抗てんかん薬・ベンゾジアゼピン系→中枢性めまい。',
    alwaysShow: true,
  },
  {
    id: 'anxiety_ppv',
    name: '心因性めまい・持続性知覚性姿勢誘発めまい（PPPD）',
    cat: '精神・機能性',
    freq: '中頻度',
    symptoms: ['floating', 'disequilibrium', 'days', 'recurrent'],
    findings: [],
    redFlags: [],
    nextStep: '器質的疾患を十分に除外してからの診断。PPPDはBarany Society基準で3ヶ月以上の持続が前提。SSRI・前庭リハビリ。心療内科/耳鼻科紹介。安易に診断を閉じないこと。',
    link: null,
    comment: '慢性のふわふわ感。動く視覚刺激（スーパー・電車内）で悪化。身体所見は正常。BPPV・前庭神経炎後に遷延することが多い。除外診断であり、器質的疾患（特に中枢性）の十分な除外が前提。',
    alwaysShow: true,
  },
  {
    id: 'vestibular_migraine',
    name: '前庭性片頭痛',
    cat: '一次性頭痛 / 前庭',
    freq: '中頻度',
    symptoms: ['vertigo', 'headache', 'minutes_hours', 'recurrent', 'nausea_vomiting'],
    findings: [],
    redFlags: [],
    nextStep: '片頭痛の既往+反復性めまい→前庭性片頭痛を疑う。トリプタン。予防薬。',
    link: null,
    comment: '片頭痛の既往がある患者の反復性めまい。めまいと頭痛が同時でないこともある。メニエール病との鑑別が難しい。',
  },
  {
    id: 'hypoglycemia',
    name: '低血糖',
    cat: '代謝',
    freq: '低〜中頻度',
    symptoms: ['presyncope', 'floating'],
    findings: [],
    redFlags: [],
    nextStep: '血糖測定。低血糖ならブドウ糖投与。インスリン・SU薬使用患者で注意。',
    link: null,
    comment: 'めまい+冷汗+振戦+空腹感。DM治療中（インスリン・SU薬）で発作性の場合は疑え。',
  },
];

export const RED_FLAGS = [
  {
    conditions: ['hit_negative'],
    message: 'HIT陰性（急性持続性めまいで）: HINTS中枢パターンの一部。小脳/脳幹梗塞を疑う。方向交代性眼振・skew deviationも確認せよ。※HINTS examは訓練を受けた医師が実施した場合に高い精度を持つ。非訓練者では偽陰性あり→臨床的に中枢を疑えば搬送をためらわない。',
    severity: 'critical',
  },
  {
    conditions: ['direction_changing_nystagmus'],
    message: '方向交代性眼振: HINTS中枢パターン。小脳/脳幹梗塞を疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['skew_deviation'],
    message: 'Skew deviation: HINTS中枢パターン。中枢性めまいを強く疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['cerebellar_ataxia'],
    message: '小脳失調: 小脳梗塞/出血を疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['truncal_ataxia'],
    message: '体幹失調（座位保持困難）: 小脳正中部病変を疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['focal_deficit'],
    message: '神経巣症状（片麻痺・感覚障害・Horner）: 脳幹梗塞を疑う。即搬送。発症4.5h以内はt-PA適応。',
    severity: 'critical',
  },
  {
    conditions: ['dysarthria'],
    message: '構音障害: 脳幹/小脳病変を強く疑う。BE-FASTの構成要素。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['diplopia'],
    message: '複視: 脳幹病変を疑う。急性めまいに随伴する複視は即紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['hearing_loss'],
    message: '急性聴力低下: 突発性難聴の可能性。72h以内のステロイド開始が重要→即日耳鼻科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['bradycardia'],
    message: '徐脈 HR<50: 完全房室ブロック・洞不全症候群を考慮。12誘導心電図+循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['irregular_pulse'],
    message: '脈不整: 新規心房細動の可能性→脳塞栓リスク。12誘導心電図。循環器紹介。',
    severity: 'warning',
  },
];
