/**
 * Diagnostic Booster — Unexplained Fatigue Data
 */

export const SYMPTOMS = [
  // 期間
  { id: 'acute', label: '急性（1ヶ月未満）', cat: '期間' },
  { id: 'subacute', label: '亜急性（1-6ヶ月）', cat: '期間' },
  { id: 'chronic', label: '慢性（6ヶ月以上）', cat: '期間' },
  // 性状
  { id: 'post_exertional', label: '労作後に極端に悪化', cat: '性状' },
  { id: 'rest_persistent', label: '安静時も持続', cat: '性状' },
  { id: 'muscle_weakness', label: '筋力低下（動けない）', cat: '性状' },
  { id: 'easy_fatigability', label: '易疲労性（動けるが疲れやすい）', cat: '性状' },
  { id: 'morning_worse', label: '朝に強い', cat: '性状' },
  { id: 'evening_worse', label: '夕方に強い', cat: '性状' },
  // 全身症状
  { id: 'weight_loss', label: '体重減少', cat: '全身' },
  { id: 'weight_gain', label: '体重増加', cat: '全身' },
  { id: 'fever', label: '発熱', cat: '全身' },
  { id: 'anorexia', label: '食欲低下', cat: '全身' },
  { id: 'polydipsia', label: '口渇・多飲・多尿', cat: '全身' },
  { id: 'edema', label: '浮腫（むくみ）', cat: '全身' },
  { id: 'cold_intolerance', label: '寒がり', cat: '全身' },
  { id: 'constipation', label: '便秘', cat: '全身' },
  { id: 'hair_loss', label: '脱毛', cat: '全身' },
  { id: 'dry_skin', label: '皮膚乾燥', cat: '全身' },
  { id: 'hyperpigmentation', label: '色素沈着', cat: '全身' },
  { id: 'jaundice', label: '黄疸', cat: '全身' },
  { id: 'lymphadenopathy', label: 'リンパ節腫脹', cat: '全身' },
  // 循環器・呼吸器
  { id: 'exertional_dyspnea', label: '労作時息切れ', cat: '循環器' },
  { id: 'palpitations', label: '動悸', cat: '循環器' },
  { id: 'orthopnea', label: '起座呼吸（横になると苦しい）', cat: '循環器' },
  // 精神
  { id: 'anhedonia', label: '興味・喜びの喪失', cat: '精神' },
  { id: 'depressed_mood', label: '気分の落ち込み', cat: '精神' },
  { id: 'suicidal', label: '希死念慮', cat: '精神' },
  // 睡眠
  { id: 'insomnia', label: '不眠（入眠障害/中途覚醒/早朝覚醒）', cat: '睡眠' },
  { id: 'daytime_sleepiness', label: '日中の過度の眠気', cat: '睡眠' },
  { id: 'snoring', label: 'いびき・無呼吸の指摘', cat: '睡眠' },
  // リスク
  { id: 'steroid_history', label: 'ステロイド長期使用歴', cat: 'リスク' },
  { id: 'unrefreshing_sleep', label: '睡眠で回復しない', cat: 'リスク' },
];

export const FINDINGS = [
  { id: 'pallor', label: '眼瞼結膜蒼白', triggers: ['exertional_dyspnea', 'palpitations', 'easy_fatigability'] },
  { id: 'thyroid_enlargement', label: '甲状腺腫大', triggers: ['cold_intolerance', 'weight_gain', 'constipation', 'dry_skin'] },
  { id: 'delayed_reflex', label: '深部腱反射の弛緩相遅延', triggers: ['cold_intolerance', 'weight_gain', 'constipation'] },
  { id: 'proximal_weakness', label: '近位筋筋力低下（起立・階段困難）', triggers: ['muscle_weakness', 'steroid_history'] },
  { id: 'hepatomegaly', label: '肝腫大', triggers: ['jaundice', 'edema', 'anorexia'] },
  { id: 'splenomegaly', label: '脾腫', triggers: ['lymphadenopathy', 'fever'] },
  { id: 'pitting_edema', label: '圧痕性浮腫', triggers: ['edema', 'exertional_dyspnea', 'orthopnea'] },
  { id: 'low_bp', label: '低血圧（収縮期100未満）', triggers: ['hyperpigmentation', 'steroid_history'] },
  { id: 'low_sodium', label: '低Na血症', triggers: [] },
  { id: 'eosinophilia', label: '好酸球増多', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 器質的疾患 ===
  {
    id: 'hypothyroidism',
    name: '甲状腺機能低下症',
    cat: '内分泌',
    freq: '高頻度',
    symptoms: ['easy_fatigability', 'cold_intolerance', 'weight_gain', 'constipation', 'dry_skin', 'hair_loss', 'chronic'],
    findings: ['thyroid_enlargement', 'delayed_reflex'],
    redFlags: [],
    nextStep: 'TSH+FT4。TSH高値→甲状腺機能低下症確定。レボチロキシン開始。再受診基準: 6-8週で効果判定。',
    link: '/docs/130-Endocrine',
    comment: '倦怠感の原因として最も見逃されやすい。寒がり+便秘+体重増加+皮膚乾燥+脱毛が揃えば強く疑う。橋本病が最多原因。深部腱反射の弛緩相遅延（アキレス腱）は診察室で確認可能な特徴的所見。',
  },
  {
    id: 'anemia',
    name: '貧血',
    cat: '血液',
    freq: '高頻度',
    symptoms: ['easy_fatigability', 'exertional_dyspnea', 'palpitations'],
    findings: ['pallor'],
    redFlags: [],
    nextStep: 'CBC+フェリチン。鉄欠乏→原因検索（消化管出血・月経過多）。Hb<7は輸血検討→紹介。再受診基準: 鉄剤開始後2-4週で効果判定。',
    link: '/docs/320-Hematology',
    comment: '眼瞼結膜蒼白が簡便なスクリーニング。鉄欠乏が最多だが、大球性（VitB12/葉酸欠乏）、腎性、慢性疾患に伴う貧血も鑑別。急性発症なら消化管出血を疑え。',
  },
  {
    id: 'diabetes',
    name: '糖尿病（新規・コントロール不良）',
    cat: '代謝',
    freq: '高頻度',
    symptoms: ['polydipsia', 'weight_loss', 'easy_fatigability'],
    findings: [],
    redFlags: [],
    nextStep: 'HbA1c+随時血糖。HbA1c≧6.5%→糖尿病確定。再受診基準: 口渇悪化・意識障害→即受診（DKA/HHS）。',
    link: '/docs/110-Diabetes',
    comment: '口渇+多飲+多尿+体重減少で疑う。倦怠感のみの症状で受診するDM患者も多い。',
  },
  {
    id: 'heart_failure',
    name: '慢性心不全',
    cat: '循環器',
    freq: '中頻度',
    symptoms: ['exertional_dyspnea', 'edema', 'orthopnea', 'easy_fatigability', 'palpitations'],
    findings: ['pitting_edema', 'pallor'],
    redFlags: ['orthopnea'],
    nextStep: 'BNP+胸部X線+心電図。BNP高値→心エコー（当院不可→循環器紹介）。再受診基準: 安静時息切れ・起座呼吸・体重急増→即受診。',
    link: '/docs/090-Cardiovascular',
    comment: '労作時息切れ+浮腫+起座呼吸。BNP<100で心不全はほぼ否定。高齢者ではHFpEF（駆出率保持型）も多い。',
  },
  {
    id: 'ckd',
    name: '慢性腎臓病（CKD）',
    cat: '腎臓',
    freq: '中頻度',
    symptoms: ['easy_fatigability', 'edema', 'anorexia'],
    findings: ['pitting_edema'],
    redFlags: [],
    nextStep: '生化学（Cre/BUN/eGFR）+尿検査。eGFR<30は腎臓内科紹介。再受診基準: 浮腫悪化・尿量減少・呼吸困難→即受診。',
    link: '/docs/270-Nephrology',
    comment: '倦怠感+浮腫+食欲低下+夜間尿。eGFRの推移で進行度を評価。腎性貧血の合併も倦怠感の原因。',
  },
  {
    id: 'malignancy',
    name: '悪性腫瘍',
    cat: '腫瘍',
    freq: '低〜中頻度',
    symptoms: ['weight_loss', 'anorexia', 'fever', 'lymphadenopathy', 'chronic'],
    findings: ['hepatomegaly', 'splenomegaly'],
    redFlags: ['weight_loss'],
    nextStep: '基本検査（CBC/LDH/CRP/肝機能）+年齢に応じたがんスクリーニング。体重減少6ヶ月で5%以上は精査。CT施設紹介。',
    link: null,
    comment: '説明のつかない体重減少+倦怠感は悪性腫瘍を除外すべき。特に50歳以上、喫煙歴、リンパ節腫脹、肝脾腫。LDH/sIL-2R上昇は悪性リンパ腫を疑う。',
  },
  {
    id: 'adrenal_insufficiency',
    name: '副腎不全',
    cat: '内分泌 / 緊急',
    freq: '低頻度',
    symptoms: ['easy_fatigability', 'weight_loss', 'anorexia', 'hyperpigmentation', 'steroid_history'],
    findings: ['low_bp', 'low_sodium', 'eosinophilia'],
    redFlags: ['low_bp', 'hyperpigmentation'],
    nextStep: '早朝コルチゾール（9時まで）。低値（<5μg/dL）→副腎不全。ACTH負荷試験は内分泌科で。副腎クリーゼ（ショック+低Na）→即搬送+ヒドロコルチゾン静注。',
    link: null,
    comment: '見逃されやすい。ステロイド長期使用→突然の中止→二次性副腎不全。低Na+好酸球増多+低血圧+色素沈着（一次性Addison病）が手がかり。副腎クリーゼは致死的。',
  },
  {
    id: 'liver_disease',
    name: '肝疾患（慢性肝炎・肝硬変）',
    cat: '消化器',
    freq: '中頻度',
    symptoms: ['easy_fatigability', 'jaundice', 'anorexia', 'edema'],
    findings: ['hepatomegaly'],
    redFlags: ['jaundice'],
    nextStep: '肝機能（AST/ALT/γGTP/ALP/ビリルビン/アルブミン）。肝硬変疑い→腹部エコー（当院不可→紹介）。',
    link: '/docs/070-Hepatobiliary',
    comment: '倦怠感+黄疸+食欲低下+浮腫。アルコール歴・B/C型肝炎歴を聴取。アルブミン低値は肝予備能低下を示唆。',
  },
  {
    id: 'infection_chronic',
    name: '慢性感染症（結核・HIV・EBV等）',
    cat: '感染症',
    freq: '低頻度',
    symptoms: ['fever', 'weight_loss', 'lymphadenopathy', 'subacute'],
    findings: ['splenomegaly'],
    redFlags: [],
    nextStep: '胸部X線+CBC+CRP。リスク行動歴→HIV検査。慢性微熱+体重減少→結核（保健所相談）。EBV既感染後の遷延性倦怠感もある。',
    link: null,
    comment: '慢性の倦怠感+微熱+体重減少で想起。結核・HIV・慢性EBVが代表。リスク因子の聴取が重要。',
  },
  // === 精神疾患 ===
  {
    id: 'depression',
    name: 'うつ病',
    cat: '精神科',
    freq: '高頻度',
    symptoms: ['anhedonia', 'depressed_mood', 'insomnia', 'anorexia', 'chronic', 'morning_worse', 'easy_fatigability'],
    findings: [],
    redFlags: ['suicidal'],
    nextStep: 'PHQ-2≧3→PHQ-9で詳細評価。PHQ-9≧10→中等度以上のうつ。精神科/心療内科紹介。希死念慮→安全確保+精神科緊急。再受診基準: 症状悪化、希死念慮出現→即受診。',
    link: '/docs/170-Psychiatry',
    comment: '倦怠感の原因として器質的疾患と並ぶ高頻度。朝に強い倦怠感+興味喪失+気分の落ち込みが手がかり。ただし器質的疾患の除外が先。「うつだろう」で甲状腺機能低下を見逃すな。',
  },
  {
    id: 'anxiety',
    name: '不安障害',
    cat: '精神科',
    freq: '中頻度',
    symptoms: ['easy_fatigability', 'insomnia', 'palpitations', 'chronic'],
    findings: [],
    redFlags: [],
    nextStep: 'GAD-7でスクリーニング。器質的疾患を除外した上での診断。精神科/心療内科紹介。',
    link: '/docs/170-Psychiatry',
    comment: '慢性の倦怠感+不眠+動悸+不安。過覚醒状態が持続し疲弊する。器質的疾患の除外が前提。',
  },
  // === 睡眠関連 ===
  {
    id: 'osas',
    name: '閉塞性睡眠時無呼吸症候群（OSAS）',
    cat: '睡眠',
    freq: '中〜高頻度',
    symptoms: ['daytime_sleepiness', 'snoring', 'easy_fatigability', 'unrefreshing_sleep'],
    findings: [],
    redFlags: [],
    nextStep: 'ESS（エプワース眠気尺度）。ESS≧11→OSAS疑い。簡易PSG/精密PSG（当院不可→紹介）。BMI≧25+いびき+日中傾眠=高確率。',
    link: '/docs/160-Sleep-Apnea',
    comment: 'いびき+日中の過度の眠気+睡眠で回復しない。肥満男性に多いが女性・痩せ型でも起こる。未治療は高血圧・心房細動・脳卒中のリスク。',
  },
  {
    id: 'insomnia_disorder',
    name: '不眠症',
    cat: '睡眠',
    freq: '高頻度',
    symptoms: ['insomnia', 'easy_fatigability', 'daytime_sleepiness', 'chronic'],
    findings: [],
    redFlags: [],
    nextStep: '睡眠衛生指導。非薬物療法（CBT-I）が第一選択。薬物療法は短期間。器質的原因（OSAS等）を除外。再受診基準: 改善なし4週→紹介。',
    link: '/docs/170-Psychiatry',
    comment: '入眠障害・中途覚醒・早朝覚醒。睡眠衛生の乱れ（スマホ・カフェイン・不規則な就寝時間）が多い。うつ病の合併を見逃さない。',
  },
  // === 機能性 ===
  {
    id: 'cfs',
    name: '慢性疲労症候群（CFS/ME）',
    cat: '機能性',
    freq: '低頻度',
    symptoms: ['chronic', 'post_exertional', 'unrefreshing_sleep', 'easy_fatigability', 'rest_persistent'],
    findings: [],
    redFlags: [],
    nextStep: '全ての器質的疾患を除外してからの診断。診断基準: 6ヶ月以上の疲労+労作後の極端な消耗+睡眠で回復しない+認知障害 or 起立不耐。「異常なし=気のせい」ではない。専門外来紹介。',
    link: null,
    comment: '器質的疾患を全て除外した後の診断。労作後の極端な消耗（PEM: post-exertional malaise）が特徴。「怠けている」のではなく病態が存在する。',
    alwaysShow: true,
  },
  // === 薬剤性 ===
  {
    id: 'drug_induced_fatigue',
    name: '薬剤性倦怠感',
    cat: '薬剤性',
    freq: '中頻度',
    symptoms: ['easy_fatigability', 'chronic'],
    findings: [],
    redFlags: [],
    nextStep: '被疑薬の同定。β遮断薬・抗ヒスタミン薬（第一世代）・抗てんかん薬・抗うつ薬・スタチン・降圧薬が代表。用量調整or代替薬。',
    link: null,
    comment: 'ポリファーマシーの高齢者で特に見逃されやすい。β遮断薬（疲労感+徐脈）、スタチン（筋痛+CK上昇）、第一世代抗ヒスタミン薬（鎮静）が代表的。',
    alwaysShow: true,
  },
];

export const RED_FLAGS = [
  {
    conditions: ['weight_loss'],
    message: '説明のつかない体重減少: 悪性腫瘍・副腎不全・甲状腺機能亢進症を考慮。精査。',
    severity: 'warning',
  },
  {
    conditions: ['muscle_weakness'],
    message: '筋力低下: 多発性筋炎/皮膚筋炎・甲状腺疾患・副腎不全・神経筋疾患を鑑別。CK+TSH+コルチゾール。近位筋優位→筋疾患/内分泌。',
    severity: 'warning',
  },
  {
    conditions: ['jaundice'],
    message: '黄疸: 肝疾患（慢性肝炎・肝硬変・肝癌）を疑う。肝機能+腹部エコー紹介。',
    severity: 'warning',
  },
  {
    conditions: ['suicidal'],
    message: '希死念慮: 精神科緊急対応。安全確保（一人にしない）。精神科紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['orthopnea'],
    message: '起座呼吸: 心不全を疑う。BNP+胸部X線+心電図。循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['low_bp'],
    message: '低血圧: 副腎不全・脱水・出血を考慮。早朝コルチゾール。副腎クリーゼ（ショック+低Na）→即搬送。',
    severity: 'warning',
  },
  {
    conditions: ['hyperpigmentation'],
    message: '色素沈着: 一次性副腎不全（Addison病）を疑う。早朝コルチゾール+ACTH。',
    severity: 'warning',
  },
  {
    conditions: ['lymphadenopathy'],
    message: 'リンパ節腫脹+倦怠感: 悪性リンパ腫・慢性感染症を考慮。LDH/sIL-2R+画像精査。',
    severity: 'warning',
  },
];
