/**
 * Diagnostic Booster — Undifferentiated Fever Data v3
 * 3-agent retroaudit 全指摘対応済み
 */

export const SYMPTOMS = [
  // Phase 4.1: 発熱パターン (1日内の体温変動様式)
  { id: 'spike_fever', label: '弛張熱 (1日内 1℃以上変動、解熱しない)', cat: '発熱パターン', weight: 4 },
  { id: 'continuous_fever', label: '稽留熱 (24時間 1℃未満変動、持続性高熱)', cat: '発熱パターン' },
  { id: 'intermittent_fever', label: '間歇熱 (発熱と解熱を繰り返す)', cat: '発熱パターン', weight: 4 },
  { id: 'relapsing_fever', label: '回帰熱 (数日熱発作 + 数日無熱期を反復)', cat: '発熱パターン', weight: 4 },
  { id: 'pel_ebstein', label: 'Pel-Ebstein型 (1〜2週単位の周期性反復、リンパ腫示唆。実臨床では稀)', cat: '発熱パターン', weight: 3 },
  // Phase 4.1: 持続期間
  { id: 'duration_acute', label: '急性 (<2週)', cat: '持続期間' },
  { id: 'duration_subacute', label: '亜急性 (2-3週)', cat: '持続期間' },
  { id: 'duration_chronic', label: '慢性 (3週以上、不明熱の閾値)', cat: '持続期間', weight: 4 },
  // Phase 4.1: リスク因子 (患者背景、発熱単独鑑別の手がかり)
  { id: 'travel_history', label: '海外渡航歴 (≤4週)', cat: 'リスク因子' },
  { id: 'animal_contact', label: '動物接触 (家畜/野生動物/節足動物)', cat: 'リスク因子' },
  { id: 'healthcare_exposure', label: '医療接触 (最近の入院/カテーテル/手術)', cat: 'リスク因子' },
  { id: 'immunocompromised', label: '免疫低下 (ステロイド/化学療法/HIV/移植)', cat: 'リスク因子', weight: 4 },
  { id: 'sore_throat', label: '咽頭痛', cat: '呼吸器' },
  { id: 'cough', label: '咳嗽', cat: '呼吸器' },
  { id: 'rhinorrhea', label: '鼻汁', cat: '呼吸器' },
  { id: 'dyspnea', label: '呼吸困難', cat: '呼吸器' },
  { id: 'headache', label: '頭痛', cat: '神経' },
  { id: 'altered_mental', label: '意識変容', cat: '神経' },
  { id: 'neck_stiffness', label: '項部硬直', cat: '神経' },
  { id: 'abdominal_pain', label: '腹痛', cat: '消化器' },
  { id: 'diarrhea', label: '下痢', cat: '消化器' },
  { id: 'vomiting', label: '嘔吐', cat: '消化器' },
  { id: 'dysuria', label: '排尿時痛・頻尿', cat: '泌尿器' },
  { id: 'flank_pain', label: '側腹部痛・CVA叩打痛', cat: '泌尿器' },
  { id: 'rash', label: '皮疹', cat: '皮膚' },
  { id: 'skin_redness', label: '皮膚の局所発赤・腫脹・熱感', cat: '皮膚' },
  { id: 'joint_pain', label: '関節痛（単関節/多関節）', cat: '筋骨格' },
  { id: 'lymphadenopathy', label: 'リンパ節腫脹', cat: '全身' },
  { id: 'weight_loss', label: '体重減少', cat: '全身' },
  { id: 'night_sweats', label: '盗汗', cat: '全身' },
  { id: 'chest_pain', label: '胸痛', cat: '循環器' },
  { id: 'palpitations', label: '動悸', cat: '循環器' },
  { id: 'trismus', label: '開口障害', cat: '耳鼻' },
  // Phase 2 #8: 二次梅毒・CDI
  { id: 'sexual_risk', label: '性行為歴 (リスク高)', cat: 'リスク' },
  { id: 'recent_antibiotic', label: '直近の抗菌薬使用 (≤8週間)', cat: 'リスク' },
  { id: 'chronic_diarrhea', label: '持続する水様性下痢', cat: '消化器' },
];

export const FINDINGS = [
  { id: 'tonsillar_exudate', label: '扁桃白苔・滲出物', triggers: ['sore_throat'] },
  { id: 'cervical_lymph', label: '頸部リンパ節腫脹・圧痛', triggers: ['sore_throat', 'lymphadenopathy'] },
  { id: 'unilateral_tonsil', label: '片側扁桃腫大・口蓋垂偏位', triggers: ['sore_throat', 'trismus'] },
  { id: 'hepatosplenomegaly', label: '肝脾腫', triggers: ['lymphadenopathy', 'weight_loss', 'night_sweats'] },
  { id: 'crackles', label: '肺crackles（湿性ラ音）', triggers: ['cough', 'dyspnea'] },
  { id: 'wheeze', label: '喘鳴', triggers: ['cough', 'dyspnea'] },
  { id: 'peritoneal_signs', label: '腹膜刺激徴候', triggers: ['abdominal_pain', 'vomiting'], weight: 4 },
  { id: 'murphy_sign', label: 'Murphy徴候陽性', triggers: ['abdominal_pain'] },
  { id: 'mcburney', label: 'McBurney圧痛・Rovsing徴候', triggers: ['abdominal_pain'] },
  { id: 'cva_tenderness', label: 'CVA叩打痛', triggers: ['flank_pain', 'dysuria', 'abdominal_pain'] },
  { id: 'new_murmur', label: '新規心雑音', triggers: ['chest_pain', 'palpitations'], weight: 4 },
  { id: 'relative_bradycardia', label: '相対的徐脈', triggers: [] },
  { id: 'petechiae', label: '点状出血', triggers: ['rash'] },
  { id: 'maculopapular_rash', label: '斑状丘疹状皮疹', triggers: ['rash'] },
  { id: 'vesicular_rash', label: '水疱性皮疹（帯状・片側性）', triggers: ['rash'] },
  { id: 'cellulitis_signs', label: '皮膚発赤・腫脹・熱感・境界明瞭', triggers: ['skin_redness'] },
  { id: 'necrotizing_signs', label: '急速進行・水疱・握雪感・不釣り合いな疼痛', triggers: ['skin_redness'] },
  { id: 'joint_swelling', label: '関節腫脹・発赤・熱感（単関節）', triggers: ['joint_pain'], weight: 4 },
  { id: 'meningeal_signs', label: '髄膜刺激徴候（Kernig/Brudzinski）', triggers: ['headache', 'neck_stiffness', 'altered_mental'], weight: 4 },
  { id: 'osler_janeway', label: 'Osler結節/Janeway病変', triggers: ['chest_pain', 'rash'], weight: 4 },
  { id: 'normal_o2sat', label: '【陰性】SpO2 正常 (≥96% 室内気)', triggers: [], cat: '陰性所見' },
  { id: 'normal_lung_sound', label: '【陰性】両肺呼吸音 清明', triggers: [], cat: '陰性所見' },
  { id: 'palm_sole_rash', label: '手掌・足底の紅斑（バラ疹）', triggers: ['rash', 'sexual_risk'], weight: 4 },
  { id: 'mucous_patch', label: '粘膜斑・扁平コンジローマ', triggers: ['rash', 'sexual_risk'] },
  { id: 'severe_diarrhea', label: '1日3回以上の水様便/血便', triggers: ['chronic_diarrhea', 'recent_antibiotic'] },
  { id: 'strawberry_tongue', label: '苺舌', triggers: ['sore_throat', 'rash'] },
  { id: 'thyroid_enlargement', label: '甲状腺腫大・圧痛', triggers: ['palpitations'] },
];

export const DIFFERENTIALS = [
  {
    id: 'common_cold',
    name: '感冒（ウイルス性URI）',
    cat: '感染症（ウイルス）',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['sore_throat', 'cough', 'rhinorrhea', 'headache'],
    findings: [],
    negativeFindings: ['duration_chronic', 'pel_ebstein', 'neck_stiffness', 'meningeal_signs', 'dysuria', 'flank_pain', 'cva_tenderness', 'diarrhea', 'travel_history', 'intermittent_fever', 'relapsing_fever', 'new_murmur'],
    showWhen: { anyOf: ['cough', 'sore_throat', 'rhinorrhea'] },
    redFlags: [],
    nextStep: '対症療法。抗菌薬不要。再受診基準: 3日以上の高熱持続、呼吸困難出現、症状が7-10日で改善しない場合。',
    link: '/docs/010-Acute-URI/j00-common-cold',
    comment: '最も頻度が高い。2-3日でピークを過ぎ、7-10日で軽快が典型。遷延する場合は二次感染や他疾患を考慮。',
  },
  {
    id: 'influenza',
    name: 'インフルエンザ',
    cat: '感染症（ウイルス）',
    freq: '高頻度（流行期）',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['cough', 'headache', 'sore_throat', 'rhinorrhea'],
    findings: [],
    negativeFindings: ['duration_chronic', 'pel_ebstein', 'neck_stiffness', 'meningeal_signs', 'dysuria', 'flank_pain', 'cva_tenderness', 'diarrhea', 'travel_history', 'intermittent_fever', 'relapsing_fever', 'new_murmur', 'rash'],
    showWhen: { anyOf: ['cough', 'sore_throat', 'rhinorrhea'] },
    redFlags: ['dyspnea', 'altered_mental'],
    nextStep: '迅速抗原検査。発症48時間以内なら抗ウイルス薬。再受診基準: 呼吸困難出現、意識朦朧、経口摂取不能。',
    link: '/docs/010-Acute-URI/j10-influenza-a',
    comment: '急激な発症、高熱、全身倦怠感、筋肉痛・関節痛が特徴。流行期の事前確率を考慮。',
  },
  {
    id: 'covid19',
    name: 'COVID-19',
    cat: '感染症（ウイルス）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['cough', 'sore_throat', 'headache', 'dyspnea', 'rhinorrhea'],
    findings: [],
    negativeFindings: ['duration_chronic', 'pel_ebstein', 'neck_stiffness', 'meningeal_signs', 'dysuria', 'flank_pain', 'cva_tenderness', 'diarrhea', 'travel_history', 'intermittent_fever', 'relapsing_fever', 'new_murmur', 'rash'],
    showWhen: { anyOf: ['cough', 'sore_throat', 'rhinorrhea', 'dyspnea'] },
    redFlags: ['dyspnea'],
    nextStep: '抗原検査。SpO2モニタリング。再受診基準: Day 7-10で呼吸困難・SpO2低下出現時は即受診。',
    link: '/docs/010-Acute-URI/u071-covid-19',
    comment: '現行株では鼻汁・咽頭痛が主要症状。呼吸困難はDay 7-10に進行しうる。',
  },
  {
    id: 'strep_throat',
    name: '溶連菌性咽頭炎',
    cat: '感染症（細菌）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['sore_throat', 'headache'],
    findings: ['tonsillar_exudate', 'cervical_lymph', 'strawberry_tongue'],
    negativeFindings: ['cough', 'duration_chronic', 'rhinorrhea', 'diarrhea', 'dysuria', 'flank_pain'],
    showWhen: { anyOf: ['sore_throat', 'tonsillar_exudate', 'cervical_lymph'] },
    redFlags: [],
    nextStep: 'Centor/McIsaac Score評価。迅速抗原検査。陽性ならアモキシシリン10日間（ペニシリンアレルギー時はセファレキシンまたはクラリスロマイシン）。EBV合併疑い時はセファレキシンを選択。',
    link: '/docs/010-Acute-URI/j020-strep-throat',
    comment: '咳嗽がないことがポイント（Centor基準）。扁桃白苔+頸部リンパ節+発熱+咳なし。',
  },
  {
    id: 'peritonsillar_abscess',
    name: '扁桃周囲膿瘍',
    cat: '感染症（細菌）/ 耳鼻',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['sore_throat', 'trismus'],
    findings: ['unilateral_tonsil', 'cervical_lymph'],
    redFlags: ['trismus'],
    nextStep: '耳鼻咽喉科へ紹介（穿刺ドレナージ・切開排膿が必要）。気道狭窄リスクあり。',
    link: '/docs/010-Acute-URI/j36-peritonsillar-abscess',
    comment: '片側の強い咽頭痛+開口障害+口蓋垂偏位。溶連菌咽頭炎の合併症として発症。重度の開口障害+嚥下困難+流涎は気道緊急。',
  },
  {
    id: 'infectious_mono',
    name: '伝染性単核球症（EBV）',
    cat: '感染症（ウイルス）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['sore_throat', 'lymphadenopathy', 'rash'],
    findings: ['tonsillar_exudate', 'cervical_lymph', 'hepatosplenomegaly'],
    redFlags: [],
    nextStep: '異型リンパ球確認（外注）。VCA-IgM/EBNA-IgG。アミノペニシリン系（AMPC/ABPC）は投与しないこと（高率に薬疹誘発）。',
    link: '/docs/010-Acute-URI/b279-infectious-mononucleosis',
    comment: '若年者。頸部リンパ節腫脹著明。脾腫注意（接触性スポーツ4週間禁止）。AMPC/ABPC投与で薬疹誘発。',
  },
  {
    id: 'pneumonia',
    name: '肺炎',
    cat: '感染症（細菌）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['cough', 'dyspnea', 'chest_pain'],
    findings: ['crackles'],
    negativeFindings: ['normal_o2sat', 'normal_lung_sound'],
    redFlags: ['dyspnea', 'altered_mental'],
    nextStep: '胸部X線。A-DROP評価。血液培養（重症時）。A-DROP 2点以上は紹介。',
    link: '/docs/020-Pneumonia',
    comment: '高齢者では発熱がないことも。SpO2低下に注意。',
  },
  {
    id: 'uti',
    name: '尿路感染症（膀胱炎・腎盂腎炎）',
    cat: '感染症（細菌）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['dysuria', 'flank_pain', 'vomiting', 'abdominal_pain'],
    findings: ['cva_tenderness'],
    negativeFindings: ['duration_chronic', 'cough', 'rhinorrhea', 'sore_throat', 'rash', 'neck_stiffness', 'meningeal_signs', 'new_murmur'],
    showWhen: { anyOf: ['dysuria', 'flank_pain', 'cva_tenderness'] },
    redFlags: ['altered_mental'],
    nextStep: '尿検査・尿培養。腎盂腎炎はCVA叩打痛+高熱で疑う。嘔吐で経口摂取不能・敗血症徴候→紹介。',
    link: '/docs/250-Urinary-Tract/n10-acute-pyelonephritis',
    comment: '女性に多い。高熱+CVA叩打痛=腎盂腎炎を強く疑う。男性は前立腺炎も鑑別。',
  },
  {
    id: 'acute_gastroenteritis',
    name: '急性胃腸炎',
    cat: '感染症',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['abdominal_pain', 'diarrhea', 'vomiting'],
    findings: [],
    negativeFindings: ['duration_chronic', 'weight_loss', 'night_sweats', 'cough', 'rhinorrhea', 'sore_throat', 'rash', 'neck_stiffness', 'new_murmur'],
    showWhen: { anyOf: ['abdominal_pain', 'diarrhea', 'vomiting'] },
    redFlags: ['altered_mental'],
    nextStep: '脱水評価。整腸剤・補液。血便→細菌性を考慮。再受診基準: 経口摂取不能24h以上、血便、意識朦朧。',
    link: '/docs/050-gastroenteritis',
    comment: 'ウイルス性が多い。血便・持続する高熱は細菌性を疑う。',
  },
  {
    id: 'appendicitis',
    name: '急性虫垂炎',
    cat: '外科',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 4,
    symptoms: ['abdominal_pain', 'vomiting'],
    findings: ['mcburney', 'peritoneal_signs'],
    redFlags: ['peritoneal_signs'],
    nextStep: '採血（WBC/CRP）。外科紹介（CT・エコー評価が必要）。',
    link: null,
    comment: '心窩部痛→右下腹部への移動が典型。McBurney圧痛+Rovsing徴候。穿孔で腹膜炎。',
  },
  {
    id: 'cholecystitis',
    name: '急性胆嚢炎',
    cat: '感染症（細菌）/ 外科',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['abdominal_pain', 'vomiting'],
    findings: ['murphy_sign'],
    redFlags: ['altered_mental'],
    nextStep: '採血（肝胆道系酵素・炎症）。外科/消化器内科に紹介（エコー・CT評価必要）。',
    link: '/docs/070-hepatobiliary',
    comment: '右季肋部痛+発熱+Murphy徴候。当院エコー未設置のため高く疑えば紹介。',
  },
  {
    id: 'cellulitis',
    name: '蜂窩織炎・皮膚軟部組織感染症',
    cat: '感染症（細菌）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['skin_redness'],
    findings: ['cellulitis_signs', 'necrotizing_signs'],
    negativeFindings: ['duration_chronic', 'cough', 'sore_throat', 'rhinorrhea', 'dysuria', 'flank_pain', 'cva_tenderness', 'diarrhea', 'neck_stiffness', 'new_murmur'],
    showWhen: { anyOf: ['skin_redness', 'cellulitis_signs', 'necrotizing_signs'] },
    redFlags: ['necrotizing_signs'],
    nextStep: '第一選択: セファレキシン。咬傷・嫌気性菌混合感染疑い: アモキシシリン/クラブラン酸。再受診基準: 急速拡大・水疱・握雪感→壊死性筋膜炎疑い→緊急搬送。',
    link: '/docs/210-skin-infect',
    comment: '境界明瞭な発赤・腫脹・熱感・疼痛。急速進行・水疱・握雪感・不釣り合いな疼痛は壊死性筋膜炎→緊急搬送。',
  },
  {
    id: 'herpes_zoster',
    name: '帯状疱疹',
    cat: '感染症（ウイルス）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['rash'],
    findings: ['vesicular_rash'],
    redFlags: [],
    nextStep: 'バラシクロビル1000mg×3回/日×7日間。72時間以内に開始。腎機能障害時は減量。三叉神経第1枝領域（Hutchinson徴候: 鼻尖の水疱）→眼部帯状疱疹→即日眼科紹介。播種性は搬送。',
    link: null,
    comment: '片側のデルマトームに沿う水疱。免疫低下者では播種性（全身散布）に注意。眼部帯状疱疹は失明リスク→眼科緊急。',
  },
  {
    id: 'meningitis',
    name: '髄膜炎',
    cat: '感染症 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['headache', 'neck_stiffness', 'altered_mental', 'vomiting'],
    findings: ['meningeal_signs', 'petechiae'],
    redFlags: ['altered_mental', 'neck_stiffness', 'meningeal_signs'],
    nextStep: '緊急搬送。可能であれば搬送前に血液培養+経験的抗菌薬投与を考慮。',
    link: null,
    comment: 'Jolt accentuationはスクリーニングとして有用（感度は報告により異なるが、陰性でも髄膜炎は否定できない）。項部硬直+意識変容は即搬送。',
  },
  {
    id: 'infective_endocarditis',
    name: '感染性心内膜炎',
    cat: '感染症（細菌）/ 循環器',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['chest_pain', 'joint_pain', 'rash', 'palpitations', 'spike_fever', 'duration_subacute', 'healthcare_exposure'],
    findings: ['new_murmur', 'osler_janeway', 'petechiae'],
    redFlags: ['new_murmur', 'osler_janeway', 'spike_fever'],
    nextStep: '血液培養3セット。循環器専門医紹介（経食道心エコー必要）。',
    link: null,
    comment: 'デバイス留置・歯科治療後・IV drug use歴で事前確率上昇。不明熱の鑑別として常に考慮。',
  },
  {
    id: 'septic_arthritis',
    name: '化膿性関節炎',
    cat: '整形外科 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    symptoms: ['joint_pain'],
    findings: ['joint_swelling'],
    redFlags: ['joint_swelling'],
    nextStep: '単関節の急性腫脹+発熱→化膿性関節炎を疑う。関節穿刺（グラム染色・培養）→整形外科紹介。遅れると関節破壊。',
    link: null,
    comment: '単関節の急性発熱+腫脹+疼痛+可動域制限。膝が最多。関節穿刺で膿性関節液+グラム陽性球菌が診断的。治療の遅れは不可逆的関節破壊→整形外科緊急。',
  },
  {
    id: 'acute_prostatitis',
    name: '急性前立腺炎',
    cat: '感染症（細菌）/ 泌尿器',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 2,
    symptoms: ['dysuria', 'abdominal_pain'],
    findings: [],
    redFlags: [],
    nextStep: '尿検査・尿培養。直腸診（前立腺圧痛、強いマッサージは菌血症リスク）。レボフロキサシン等のニューキノロン2-4週間（※腱断裂リスク〔高齢者・ステロイド併用〕に注意）。',
    link: '/docs/260-prostate/n410-acute-prostatitis',
    comment: '男性の発熱+排尿障害。直腸診で前立腺の腫大・圧痛。',
  },
  {
    id: 'adult_still',
    name: '成人Still病',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['joint_pain', 'rash', 'sore_throat', 'weight_loss', 'spike_fever'],
    findings: ['maculopapular_rash', 'joint_swelling', 'hepatosplenomegaly'],
    redFlags: [],
    nextStep: 'フェリチン（著明高値>1000は強く示唆。HLH/MASとの鑑別にも重要）。リウマチ科紹介。',
    link: null,
    comment: '弛張熱 (daily spike) +サーモンピンク疹+関節痛+咽頭痛+フェリチン著増。ANA/RF陰性。',
  },
  {
    id: 'sle',
    name: 'SLE',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['joint_pain', 'rash', 'weight_loss'],
    findings: ['maculopapular_rash', 'joint_swelling'],
    redFlags: [],
    nextStep: 'ANA、抗dsDNA抗体、補体。リウマチ科紹介。',
    link: '/docs/220-rheumatology/m329-sle',
    comment: '若年女性。蝶形紅斑、光線過敏、口腔潰瘍、多関節炎、漿膜炎。',
  },
  {
    id: 'malignant_lymphoma',
    name: '悪性リンパ腫',
    cat: '悪性腫瘍',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['lymphadenopathy', 'night_sweats', 'weight_loss', 'pel_ebstein', 'duration_chronic', 'intermittent_fever'],
    findings: ['hepatosplenomegaly'],
    redFlags: ['pel_ebstein', 'duration_chronic'],
    nextStep: '血液検査（LDH・sIL-2R）。リンパ節生検（血液内科紹介）。',
    link: null,
    comment: 'B症状（発熱・盗汗・体重減少）＋無痛性リンパ節腫脹。持続する場合は生検。',
  },
  {
    id: 'drug_fever',
    name: '薬剤熱',
    cat: '薬剤性',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 1,
    symptoms: [],
    findings: ['relative_bradycardia', 'maculopapular_rash'],
    redFlags: [],
    nextStep: '被疑薬中止。48-72時間で解熱確認。',
    link: '/docs/200-dermatitis/l270-drug-eruption',
    comment: '初回投与後5-28日（典型的には7-10日、再投与時はより早期）。相対的徐脈が手がかり。好酸球増多。全身状態は比較的良好。',
    showWhen: { anyOf: ['relative_bradycardia', 'maculopapular_rash', 'rash'] },
  },
  {
    id: 'tuberculosis',
    name: '結核',
    cat: '感染症（細菌）',
    freq: '低〜中頻度（地域差あり）',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['cough', 'night_sweats', 'weight_loss', 'duration_subacute', 'duration_chronic', 'intermittent_fever', 'immunocompromised'],
    findings: [],
    redFlags: ['duration_chronic', 'immunocompromised'],
    nextStep: '胸部X線。結核疑いの時点で保健所相談＋専門医療機関紹介。喀痰抗酸菌検査は専門施設で。喀血時は止血処置+紹介。',
    link: null,
    comment: '2週間以上の咳嗽+盗汗+体重減少で疑う。日本は結核中蔓延国。高齢者・免疫低下者に注意。院内感染リスクあり→マスク着用+隔離。',
  },
  // === Phase 4.1 追加: 不明熱・マラリア ===
  {
    id: 'fuo',
    name: '不明熱 (FUO: 3週以上の説明困難な発熱)',
    cat: '系統的精査',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 3,
    symptoms: ['duration_chronic', 'weight_loss', 'night_sweats'],
    findings: [],
    redFlags: ['duration_chronic'],
    nextStep: '系統的精査が必要。まず CBC・生化学・尿検査・血液培養2セット・尿培養・胸腹CT・自己抗体スクリーニング (ANA/RF/CRP/ESR)・HIV/結核検査・腫瘍マーカー。原因 4分類: 感染症 (30-40%)・悪性腫瘍 (20-30%)・自己免疫疾患 (15-25%)・その他 (薬剤熱/亜急性甲状腺炎/家族性地中海熱等)。所属医療機関で対応困難なら膠原病内科 or 総合内科紹介。',
    link: null,
    comment: 'Petersdorf診断基準: 38.3℃以上が3週間以上、外来3回 or 入院1週間で診断つかない。安易に "風邪" "気のせい" としない。原因不明でも最終的に約10-30%は診断つかず自然軽快する例あり (idiopathic FUO)。',
  },
  {
    id: 'malaria',
    name: 'マラリア',
    cat: '感染症（寄生虫）/ 緊急',
    freq: '極めて低頻度（日本国内）',
    prevalenceWeight: 1,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['headache', 'travel_history', 'intermittent_fever', 'continuous_fever', 'relapsing_fever'],
    findings: ['hepatosplenomegaly'],
    redFlags: ['travel_history'],
    nextStep: '熱帯・亜熱帯地域からの帰国者の発熱は必ず疑う。即日 感染症内科/熱帯医学施設へ紹介。血液塗抹 (Giemsa染色) で原虫 (Plasmodium) 同定。P. falciparum は重症化進行性 → 24時間以内の治療開始が rule。',
    link: null,
    comment: '渡航後1ヶ月以内の発熱では必須鑑別。Tertian (P.vivax/ovale: 48時間周期)、Quartan (P.malariae: 72時間周期)、不規則 (P.falciparum)。脳マラリア・ARDS・腎不全・DIC で致死。日本では熱帯熱マラリアの輸入症例。',
  },
  // === Phase 2 #8 追加: 二次梅毒・CDI ===
  {
    id: 'secondary_syphilis',
    name: '第2期梅毒',
    cat: '感染症（性感染症）',
    freq: '低〜中頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['rash', 'lymphadenopathy', 'sore_throat', 'sexual_risk', 'weight_loss'],
    findings: ['palm_sole_rash', 'mucous_patch', 'maculopapular_rash'],
    redFlags: ['palm_sole_rash'],
    nextStep: 'RPR/TPHA即日提出。全身性無痛性リンパ節腫脹+手掌・足底の紅斑+発熱→梅毒を強く疑う。性行為歴聴取が困難でも検査閾値を下げる。ベンジルペニシリンベンザチン筋注 or アモキシシリン内服。HIV同時検査。',
    link: '/docs/255-Sexual-Infect/a513-secondary-syphilis',
    comment: '「The Great Imitator」。あらゆる発熱+皮疹を模倣する。手掌・足底の紅斑（バラ疹）が最も特異的。近年日本で激増中。',
  },
  {
    id: 'cdi',
    name: 'Clostridioides difficile感染症 (CDI)',
    cat: '感染症（細菌）',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['abdominal_pain', 'diarrhea', 'recent_antibiotic', 'chronic_diarrhea', 'healthcare_exposure'],
    findings: ['severe_diarrhea'],
    redFlags: ['severe_diarrhea'],
    nextStep: '抗菌薬使用後（特にFQ・第3世代セフェム・クリンダマイシン）の発熱+水様性下痢→CDトキシン抗原検査（GDH+toxin）。被疑薬中止+メトロニダゾール経口 or バンコマイシン経口。重症（WBC≥15000/腎障害/中毒性巨大結腸）→消化器/感染症科紹介。',
    link: null,
    comment: '高齢者・PPI使用・入院歴・直近の抗菌薬がリスク。「下痢=胃腸炎」で片付けず、抗菌薬歴を必ず聴取。中毒性巨大結腸は致死的。',
  },
  {
    id: 'secondary_bacterial',
    name: 'ウイルス感染後二次性細菌感染',
    cat: '感染症（細菌）',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 2,
    symptoms: ['cough', 'dyspnea'],
    findings: ['crackles'],
    redFlags: ['dyspnea'],
    nextStep: '胸部X線。一旦改善した発熱の再上昇（二峰性発熱）は二次感染を疑う。',
    link: null,
    comment: 'ウイルス感染後に一旦改善→再度発熱上昇のパターン（二峰性発熱）。',
  },
  {
    id: 'thyroid_crisis',
    name: '甲状腺クリーゼ',
    cat: '内分泌 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['palpitations', 'altered_mental'],
    findings: ['thyroid_enlargement'],
    redFlags: ['altered_mental'],
    nextStep: '緊急搬送。甲状腺機能検査（TSH/FT3/FT4）。',
    link: null,
    comment: '高熱+頻脈+意識障害+甲状腺腫大。バセドウ病既往がヒント。致死率高く緊急対応。',
  },
  {
    id: 'pulmonary_embolism',
    name: '肺塞栓症',
    cat: '循環器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['dyspnea', 'chest_pain', 'palpitations'],
    findings: [],
    negativeFindings: ['normal_o2sat'],
    redFlags: ['dyspnea'],
    nextStep: 'Wells Score評価。D-dimer・造影CTは当院測定不可のため、Wells高リスクなら臨床判断で即搬送。',
    link: null,
    comment: '突然の呼吸困難+胸痛+頻脈。長期臥床・手術後・下肢腫脹がリスク。発熱は軽度のことが多い。',
  },
];

export const RED_FLAGS = [
  // Phase 4.1: 発熱単独鑑別の警告
  {
    conditions: ['immunocompromised'],
    message: '免疫低下患者の発熱: 日和見感染・敗血症リスク高。早期の血液培養 + 経験的抗菌薬 + 専門医相談を考慮。',
    severity: 'critical',
  },
  {
    conditions: ['travel_history'],
    message: '渡航歴あり + 発熱: マラリア (特に P. falciparum) を必ず除外。感染症内科 or 熱帯医学施設へ紹介。',
    severity: 'warning',
  },
  {
    conditions: ['duration_chronic'],
    message: '3週間以上の不明熱 (FUO): 感染症/悪性腫瘍/自己免疫疾患の系統的精査が必要。',
    severity: 'warning',
  },
  {
    conditions: ['pel_ebstein'],
    message: 'Pel-Ebstein型熱 (周期性反復熱): ホジキンリンパ腫を強く示唆。血液内科紹介を考慮。',
    severity: 'warning',
  },
  {
    conditions: ['altered_mental'],
    message: '意識変容: 髄膜炎・敗血症・重症感染症・甲状腺クリーゼを考慮。バイタル再確認、搬送準備。',
    severity: 'critical',
  },
  {
    conditions: ['neck_stiffness'],
    message: '項部硬直: 髄膜炎を疑う。Jolt accentuation・Kernig徴候を確認。陰性でも髄膜炎は否定できない。',
    severity: 'critical',
  },
  {
    conditions: ['meningeal_signs'],
    message: '髄膜刺激徴候: 細菌性髄膜炎を強く疑う。直ちに高次医療機関へ搬送。可能であれば搬送前に血液培養+経験的抗菌薬。',
    severity: 'critical',
  },
  {
    conditions: ['new_murmur'],
    message: '新規心雑音: 感染性心内膜炎を疑う。血液培養3セット採取し循環器専門医紹介。',
    severity: 'critical',
  },
  {
    conditions: ['osler_janeway'],
    message: 'Osler結節/Janeway病変: 感染性心内膜炎を強く示唆。直ちに血液培養+専門医紹介。',
    severity: 'critical',
  },
  {
    conditions: ['peritoneal_signs'],
    message: '腹膜刺激徴候: 消化管穿孔・虫垂炎穿孔等の外科的緊急を考慮。外科紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['necrotizing_signs'],
    message: '壊死性筋膜炎を疑う所見（急速進行・水疱・握雪感・不釣り合いな疼痛）: 緊急搬送。時間単位で進行し致死的。',
    severity: 'critical',
  },
  {
    conditions: ['joint_swelling'],
    message: '単関節の急性腫脹+発熱: 化膿性関節炎を疑う。関節穿刺→整形外科紹介。遅れると関節破壊。',
    severity: 'warning',
  },
  {
    conditions: ['murphy_sign'],
    message: 'Murphy徴候陽性: 急性胆嚢炎を疑う。外科/消化器内科へ紹介。',
    severity: 'warning',
  },
  {
    conditions: ['dyspnea'],
    message: '呼吸困難: SpO2確認。93%未満は搬送検討。肺炎・心不全・肺塞栓を鑑別。',
    severity: 'warning',
  },
  {
    conditions: ['petechiae'],
    message: '点状出血: DIC・血小板減少・髄膜炎菌血症を考慮。CBC+凝固採血。',
    severity: 'warning',
  },
  {
    conditions: ['trismus'],
    message: '開口障害: 扁桃周囲膿瘍による気道狭窄リスクを考慮。耳鼻咽喉科紹介。',
    severity: 'warning',
  },
];
