/**
 * Diagnostic Booster — Undifferentiated Headache Data
 */

export const SYMPTOMS = [
  // 発症様式
  { id: 'thunderclap', label: '雷鳴頭痛（数秒でピーク）', cat: '発症様式' },
  { id: 'acute_onset', label: '急性発症（分〜時間）', cat: '発症様式' },
  { id: 'subacute', label: '亜急性（日〜週で増悪）', cat: '発症様式' },
  { id: 'chronic', label: '慢性（月以上）', cat: '発症様式' },
  { id: 'first_ever', label: '初発（今までにない頭痛）', cat: '発症様式' },
  { id: 'pattern_change', label: '既存パターンからの変化', cat: '発症様式' },
  // 性状
  { id: 'pulsating', label: '拍動性', cat: '性状' },
  { id: 'tightening', label: '締め付け・圧迫感', cat: '性状' },
  { id: 'unilateral', label: '片側性', cat: '性状' },
  { id: 'bilateral', label: '両側性', cat: '性状' },
  { id: 'periorbital', label: '眼窩部・眼の奥', cat: '性状' },
  { id: 'occipital', label: '後頭部', cat: '性状' },
  // 増悪因子
  { id: 'worse_movement', label: '体動で悪化', cat: '増悪因子' },
  { id: 'worse_valsalva', label: '咳・いきみ・性交で悪化', cat: '増悪因子' },
  { id: 'worse_positional', label: '体位変換で変化（起立悪化/臥位悪化）', cat: '増悪因子' },
  // 随伴症状
  { id: 'nausea_vomiting', label: '嘔気・嘔吐', cat: '随伴症状' },
  { id: 'photophobia', label: '光過敏', cat: '随伴症状' },
  { id: 'phonophobia', label: '音過敏', cat: '随伴症状' },
  { id: 'aura', label: '前兆（視覚異常・閃輝暗点）', cat: '随伴症状' },
  { id: 'lacrimation', label: '流涙・結膜充血・鼻閉', cat: '随伴症状' },
  { id: 'fever', label: '発熱', cat: '随伴症状' },
  { id: 'neck_stiffness', label: '項部硬直・首の痛み', cat: '随伴症状' },
  { id: 'visual_loss', label: '視力障害・視野欠損', cat: '随伴症状' },
  { id: 'diplopia', label: '複視', cat: '随伴症状' },
  { id: 'focal_neuro', label: '麻痺・しびれ・失語', cat: '随伴症状' },
  { id: 'altered_mental', label: '意識障害', cat: '随伴症状' },
  { id: 'seizure', label: 'けいれん', cat: '随伴症状' },
  // リスク
  { id: 'age_over50', label: '50歳以上', cat: 'リスク' },
  { id: 'immunocompromised', label: '免疫不全（HIV/ステロイド等）', cat: 'リスク' },
  { id: 'analgesic_overuse', label: '鎮痛薬月10日以上使用', cat: 'リスク' },
  { id: 'head_trauma', label: '頭部外傷歴', cat: 'リスク' },
  { id: 'anticoagulant', label: '抗凝固薬使用中', cat: 'リスク' },
  { id: 'pregnancy', label: '妊娠中・産褥期', cat: 'リスク' },
];

export const FINDINGS = [
  // 髄膜刺激
  { id: 'meningeal_signs', label: '髄膜刺激徴候（Kernig/Brudzinski陽性）', triggers: ['fever', 'neck_stiffness', 'altered_mental'] },
  { id: 'jolt_positive', label: 'Jolt accentuation陽性', triggers: ['fever', 'neck_stiffness'] },
  // 側頭動脈
  { id: 'temporal_artery_tenderness', label: '側頭動脈圧痛・索状硬化・拍動減弱', triggers: ['age_over50', 'first_ever', 'visual_loss'] },
  // 神経所見
  { id: 'focal_deficit', label: '神経巣症状（片麻痺・感覚障害・失語）', triggers: ['focal_neuro', 'altered_mental', 'thunderclap'] },
  { id: 'pupil_asymmetry', label: '瞳孔不同', triggers: ['altered_mental', 'focal_neuro', 'thunderclap'] },
  { id: 'papilledema', label: '乳頭浮腫', triggers: ['subacute', 'visual_loss', 'worse_valsalva', 'nausea_vomiting'] },
  { id: 'ptosis_miosis', label: '眼瞼下垂+縮瞳（Horner症候群）', triggers: ['unilateral', 'periorbital', 'neck_stiffness'] },
  { id: 'cn3_palsy', label: '動眼神経麻痺（散瞳+眼瞼下垂+眼球運動障害）', triggers: ['diplopia', 'periorbital', 'thunderclap'] },
  // バイタル（常時表示）
  { id: 'hypertensive_crisis', label: '血圧 ≥180/120', triggers: [] },
  { id: 'fever_high', label: '高熱 ≥38.5℃', triggers: [] },
];

export const DIFFERENTIALS = [
  // === Killer / 緊急 ===
  {
    id: 'sah',
    name: 'くも膜下出血（SAH）',
    cat: '脳血管 / 緊急',
    freq: '低頻度',
    symptoms: ['thunderclap', 'first_ever', 'nausea_vomiting', 'neck_stiffness', 'altered_mental'],
    findings: ['meningeal_signs', 'focal_deficit', 'pupil_asymmetry'],
    redFlags: ['thunderclap', 'meningeal_signs'],
    nextStep: '即日CT施設へ紹介/搬送。発症6時間以内のCT感度98-100%。CT陰性でも臨床的疑いが強ければ腰椎穿刺（高次施設で）。',
    link: null,
    comment: '「人生最悪の頭痛」「数秒でピーク」が最大の手がかり。雷鳴頭痛=SAH否定まではSAH。嘔吐・意識障害を伴うことが多い。30%は初回出血で死亡。',
  },
  {
    id: 'meningitis',
    name: '髄膜炎',
    cat: '感染症 / 緊急',
    freq: '低頻度',
    symptoms: ['fever', 'neck_stiffness', 'altered_mental', 'nausea_vomiting', 'acute_onset', 'photophobia'],
    findings: ['meningeal_signs', 'jolt_positive', 'fever_high', 'focal_deficit'],
    redFlags: ['meningeal_signs', 'altered_mental'],
    nextStep: '即搬送。可能であれば搬送前に血液培養+経験的抗菌薬（CTRX 2g IV）。',
    link: null,
    comment: '発熱+頭痛+項部硬直の三徴。ただし全て揃わないことも。Jolt陽性はスクリーニングに有用だが陰性でも否定不可。免疫不全者は非典型的。',
  },
  {
    id: 'gca',
    name: '巨細胞性動脈炎（GCA/側頭動脈炎）',
    cat: '血管炎 / 緊急',
    freq: '低頻度',
    symptoms: ['age_over50', 'first_ever', 'unilateral', 'visual_loss'],
    findings: ['temporal_artery_tenderness'],
    redFlags: ['temporal_artery_tenderness'],
    nextStep: 'ESR+CRP（即日）。ESR正常でもGCA否定不可（生検陽性例の4-22%はESR正常）。GCA疑い→失明予防のためプレドニゾロン先行投与を検討+即日眼科+リウマチ科紹介。',
    link: null,
    comment: '50歳以上の新規頭痛+側頭動脈圧痛・索状硬化・拍動減弱。顎跛行（咀嚼時の顎痛）は特異度高い。失明は非可逆的→疑ったら生検結果を待たずにステロイド。PMRの合併多い。',
  },
  {
    id: 'stroke',
    name: '脳血管障害（脳出血・脳梗塞）',
    cat: '脳血管 / 緊急',
    freq: '低〜中頻度',
    symptoms: ['acute_onset', 'focal_neuro', 'altered_mental', 'nausea_vomiting'],
    findings: ['focal_deficit', 'pupil_asymmetry', 'hypertensive_crisis'],
    redFlags: ['focal_deficit', 'pupil_asymmetry'],
    nextStep: '即搬送。脳梗塞は発症4.5時間以内ならt-PA適応あり→時間が命。',
    link: null,
    comment: '突然の片麻痺・感覚障害・失語・構音障害。脳出血は頭痛+意識障害が強い。高血圧・Af・抗凝固薬使用がリスク。FAST（Face-Arm-Speech-Time）で評価。',
  },
  {
    id: 'brain_tumor',
    name: '脳腫瘍',
    cat: '腫瘍',
    freq: '低頻度',
    symptoms: ['subacute', 'pattern_change', 'nausea_vomiting', 'focal_neuro', 'worse_valsalva', 'seizure'],
    findings: ['papilledema', 'focal_deficit'],
    redFlags: ['papilledema'],
    nextStep: 'MRI施設へ紹介。乳頭浮腫あれば緊急性高い。',
    link: null,
    comment: '亜急性〜慢性の進行性頭痛+神経巣症状。早朝に悪い、咳・いきみで増悪（頭蓋内圧亢進）。嘔吐は噴射性。乳頭浮腫が重要所見。',
  },
  {
    id: 'cerebral_venous_thrombosis',
    name: '脳静脈洞血栓症',
    cat: '脳血管',
    freq: '低頻度',
    symptoms: ['subacute', 'pregnancy', 'seizure', 'focal_neuro', 'nausea_vomiting'],
    findings: ['papilledema', 'focal_deficit'],
    redFlags: ['papilledema'],
    nextStep: 'MRI/MRV施設へ紹介。妊婦・産褥期・OC使用中の頭痛は疑え。',
    link: null,
    comment: '妊娠中・産褥期・経口避妊薬使用中の若年女性に好発。亜急性の頭痛+けいれん+神経症状。通常のCTでは見逃しやすい。',
  },
  {
    id: 'intracranial_aneurysm',
    name: '未破裂脳動脈瘤（警告頭痛）',
    cat: '脳血管',
    freq: '低頻度',
    symptoms: ['acute_onset', 'periorbital', 'unilateral', 'diplopia'],
    findings: ['cn3_palsy', 'pupil_asymmetry'],
    redFlags: ['cn3_palsy'],
    nextStep: '散瞳を伴う動眼神経麻痺=後交通動脈瘤を疑う。即紹介/搬送。',
    link: null,
    comment: '散瞳+眼瞼下垂+眼球運動障害（CN3麻痺）=後交通動脈瘤の圧迫→破裂前の警告サイン。散瞳なしのCN3麻痺は虚血性（DM等）の可能性。',
  },
  {
    id: 'carotid_dissection',
    name: '頸動脈解離',
    cat: '脳血管 / 緊急',
    freq: '低頻度',
    symptoms: ['acute_onset', 'unilateral', 'periorbital', 'focal_neuro', 'head_trauma'],
    findings: ['ptosis_miosis', 'focal_deficit'],
    redFlags: ['ptosis_miosis'],
    nextStep: 'Horner症候群+片側頭痛+神経症状→頸動脈解離疑い。MRA施設へ即紹介。',
    link: null,
    comment: '片側の頭痛/頸部痛+Horner症候群（縮瞳+眼瞼下垂+無汗）±脳梗塞症状。外傷・カイロプラクティック後が契機。若年の脳梗塞原因として重要。',
  },
  {
    id: 'hypertensive_emergency',
    name: '高血圧緊急症',
    cat: '循環器 / 緊急',
    freq: '低〜中頻度',
    symptoms: ['acute_onset', 'bilateral', 'nausea_vomiting', 'visual_loss'],
    findings: ['hypertensive_crisis', 'papilledema'],
    redFlags: ['hypertensive_crisis'],
    nextStep: '収縮期≥180かつ臓器障害（頭痛・視力障害・乳頭浮腫・意識障害）→降圧+搬送。臓器障害なし（高血圧切迫症）→外来降圧で経過観察可能。',
    link: null,
    comment: '血圧≥180/120+標的臓器障害が高血圧緊急症の定義。頭痛のみで臓器障害なし=切迫症→外来対応可。区別が重要。',
  },
  {
    id: 'intracranial_hypotension',
    name: '低髄液圧性頭痛',
    cat: '神経',
    freq: '低頻度',
    symptoms: ['worse_positional', 'bilateral', 'occipital'],
    findings: [],
    redFlags: [],
    nextStep: 'MRI施設へ紹介（硬膜造影・脳下垂）。安静臥床+補液+カフェイン。',
    link: null,
    comment: '起立で増悪、臥位で軽減が最大の特徴。腰椎穿刺後・脊椎手術後に多いが、特発性もある。MRIで硬膜造影効果。',
  },
  // === 一次性頭痛 ===
  {
    id: 'migraine',
    name: '片頭痛',
    cat: '一次性頭痛',
    freq: '極めて高頻度',
    symptoms: ['pulsating', 'unilateral', 'nausea_vomiting', 'photophobia', 'phonophobia', 'worse_movement', 'aura'],
    findings: [],
    redFlags: [],
    nextStep: 'トリプタン（スマトリプタン50mg）。NSAIDs。制吐剤。頭痛ダイアリー。月4回以上→予防薬（バルプロ酸/アミトリプチリン）。',
    link: '/docs/140-Headache',
    comment: '片側拍動性+嘔気+光過敏+音過敏+体動で悪化。前兆（閃輝暗点）は約30%に。除外診断ではなく、典型的パターンなら積極的に診断してよい。ただし初発・パターン変化時は二次性を除外。',
  },
  {
    id: 'tension_type',
    name: '緊張型頭痛',
    cat: '一次性頭痛',
    freq: '極めて高頻度',
    symptoms: ['tightening', 'bilateral', 'chronic'],
    findings: [],
    redFlags: [],
    nextStep: 'NSAIDs。ストレス・姿勢改善指導。慢性化（月15日以上）→アミトリプチリン。',
    link: '/docs/140-Headache',
    comment: '両側の締め付け感。体動で悪化しない。嘔気・光過敏は軽度or absent。最も頻度が高い頭痛。除外診断。',
  },
  {
    id: 'cluster',
    name: '群発頭痛',
    cat: '一次性頭痛',
    freq: '低〜中頻度',
    symptoms: ['periorbital', 'unilateral', 'lacrimation'],
    findings: ['ptosis_miosis'],
    redFlags: [],
    nextStep: '発作時: 酸素吸入（7-12L/min 15分）+ スマトリプタン皮下注。予防: ベラパミル。',
    link: '/docs/140-Headache',
    comment: '片側の眼窩部激痛+流涙+結膜充血+鼻閉+Horner様症状。15分-3時間持続。毎日同じ時間に出現（特に夜間）。男性に多い。',
  },
  {
    id: 'moh',
    name: '薬物乱用頭痛（MOH）',
    cat: '一次性頭痛（二次性要素）',
    freq: '中頻度',
    symptoms: ['chronic', 'bilateral', 'analgesic_overuse', 'pattern_change'],
    findings: [],
    redFlags: [],
    nextStep: '原因薬剤の段階的中止。予防薬導入。頭痛ダイアリー。',
    link: '/docs/140-Headache',
    comment: '鎮痛薬を月10日以上使用（トリプタン・エルゴタミンは月10日、NSAIDs・アセトアミノフェンは月15日が基準）。薬を飲むほど頭痛が増える悪循環。',
    alwaysShow: true,
  },
  {
    id: 'sinusitis',
    name: '急性副鼻腔炎',
    cat: '耳鼻',
    freq: '高頻度',
    symptoms: ['fever', 'periorbital', 'bilateral', 'worse_valsalva'],
    findings: ['fever_high'],
    redFlags: [],
    nextStep: '10日以上持続 or 二峰性悪化→細菌性。AMPC。前屈で増悪+膿性鼻汁が診断的。',
    link: null,
    comment: '前頭部/眼窩部/頬部の痛み+膿性鼻汁+前屈で悪化。ウイルス性が大半（10日以内に軽快）。細菌性は抗菌薬。「副鼻腔炎による頭痛」と自己診断→実は片頭痛のことが多い。',
  },
  {
    id: 'cervicogenic',
    name: '頸原性頭痛',
    cat: '筋骨格',
    freq: '中頻度',
    symptoms: ['unilateral', 'occipital'],
    findings: [],
    redFlags: [],
    nextStep: 'NSAIDs。理学療法。頸椎精査が必要なら整形外科紹介。',
    link: null,
    comment: '頸部から後頭部への放散痛。頸部の可動域制限。デスクワーク・スマホ姿勢が増悪因子。後頭神経ブロックが有効なことがある。',
  },
];

export const RED_FLAGS = [
  {
    conditions: ['thunderclap'],
    message: '雷鳴頭痛: SAH否定まではSAHとして扱え。即日CT施設へ紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['meningeal_signs'],
    message: '髄膜刺激徴候: 細菌性髄膜炎を強く疑う。即搬送。可能なら血培+抗菌薬先行。',
    severity: 'critical',
  },
  {
    conditions: ['altered_mental'],
    message: '意識障害: SAH・脳出血・髄膜炎・脳ヘルニアを考慮。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['focal_deficit'],
    message: '神経巣症状: 脳血管障害・脳腫瘍を疑う。即紹介/搬送。脳梗塞は発症4.5h以内でt-PA適応。',
    severity: 'critical',
  },
  {
    conditions: ['pupil_asymmetry'],
    message: '瞳孔不同: 脳ヘルニア・動脈瘤を疑う。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['cn3_palsy'],
    message: '散瞳+眼瞼下垂+眼球運動障害: 後交通動脈瘤の圧迫を疑う。破裂前の警告→即紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['papilledema'],
    message: '乳頭浮腫: 頭蓋内圧亢進を示唆。脳腫瘍・静脈洞血栓症を考慮。MRI紹介。',
    severity: 'critical',
  },
  {
    conditions: ['temporal_artery_tenderness'],
    message: '側頭動脈圧痛: GCA（側頭動脈炎）を疑う。失明予防にステロイド先行投与を検討。ESR正常でも否定不可。即日眼科+リウマチ科紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ptosis_miosis'],
    message: 'Horner症候群: 頸動脈解離を疑う。MRA施設へ紹介。',
    severity: 'warning',
  },
  {
    conditions: ['hypertensive_crisis'],
    message: '血圧≥180/120: 臓器障害（頭痛・視力障害・乳頭浮腫）あれば高血圧緊急症。降圧+搬送。',
    severity: 'warning',
  },
  {
    conditions: ['seizure'],
    message: 'けいれん: 脳腫瘍・脳静脈洞血栓症・髄膜脳炎を考慮。CT/MRI紹介。',
    severity: 'warning',
  },
  {
    conditions: ['neck_stiffness'],
    message: '項部硬直: 髄膜炎・SAHを疑う。Jolt accentuation・Kernig確認。',
    severity: 'warning',
  },
];
