/**
 * Diagnostic Booster — Unexplained Lymphadenopathy Data
 */

export const SYMPTOMS = [
  // 部位
  { id: 'cervical', label: '頸部', cat: '部位' },
  { id: 'axillary', label: '腋窩', cat: '部位' },
  { id: 'inguinal', label: '鼠径', cat: '部位' },
  { id: 'supraclavicular', label: '鎖骨上窩', cat: '部位' },
  { id: 'generalized', label: '全身性（2領域以上）', cat: '部位' },
  { id: 'epitrochlear', label: '滑車上', cat: '部位' },
  // 性状
  { id: 'painless', label: '無痛性', cat: '性状' },
  { id: 'painful', label: '有痛性・圧痛あり', cat: '性状' },
  { id: 'rapid_growth', label: '急速増大（日〜週単位）', cat: '性状' },
  { id: 'slow_growth', label: '緩徐増大（月単位）', cat: '性状' },
  { id: 'over_2cm', label: '2cm超', cat: '性状' },
  { id: 'persisting_4wks', label: '4週間以上持続', cat: '性状' },
  // B症状
  { id: 'fever', label: '発熱', cat: 'B症状' },
  { id: 'night_sweats', label: '盗汗', cat: 'B症状' },
  { id: 'weight_loss', label: '体重減少（6ヶ月で10%以上）', cat: 'B症状' },
  // 随伴
  { id: 'sore_throat', label: '咽頭痛', cat: '随伴' },
  { id: 'dental_pain', label: '歯痛・歯科感染', cat: '随伴' },
  { id: 'skin_infection', label: '皮膚感染・外傷', cat: '随伴' },
  { id: 'fatigue', label: '倦怠感', cat: '随伴' },
  { id: 'rash', label: '皮疹', cat: '随伴' },
  { id: 'joint_pain', label: '関節痛', cat: '随伴' },
  // リスク
  { id: 'cat_contact', label: '猫との接触歴', cat: 'リスク' },
  { id: 'sexual_risk', label: '性行為歴', cat: 'リスク' },
  { id: 'drug_history', label: '薬剤歴（フェニトイン・カルバマゼピン等）', cat: 'リスク' },
  { id: 'cancer_history', label: '悪性腫瘍の既往', cat: 'リスク' },
  { id: 'young_adult', label: '若年者（15-35歳）', cat: 'リスク' },
];

export const FINDINGS = [
  { id: 'hard_fixed', label: '硬い・不動（周囲と癒着）', triggers: ['painless', 'slow_growth', 'over_2cm', 'supraclavicular', 'cancer_history'] },
  { id: 'rubbery', label: '弾性硬・可動性良好', triggers: ['painless', 'over_2cm', 'generalized'] },
  { id: 'tender_soft', label: '柔らかい・圧痛あり', triggers: ['painful', 'rapid_growth', 'sore_throat', 'dental_pain', 'skin_infection'] },
  { id: 'splenomegaly', label: '脾腫', triggers: ['generalized', 'fever', 'fatigue'] },
  { id: 'hepatomegaly', label: '肝腫大', triggers: ['generalized', 'weight_loss'] },
  { id: 'tonsillar_exudate', label: '扁桃白苔・肥大', triggers: ['sore_throat', 'cervical', 'fever'] },
  { id: 'skin_lesion', label: '猫ひっかき傷・皮膚病変', triggers: ['cat_contact', 'skin_infection'] },
  { id: 'palm_sole_rash', label: '手掌・足底の紅斑', triggers: ['sexual_risk', 'rash', 'generalized'] },
  // 常時表示
  { id: 'pallor', label: '眼瞼結膜蒼白', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 反応性（最多）===
  {
    id: 'reactive',
    name: '反応性リンパ節腫脹（感染巣の反応）',
    cat: '反応性',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['painful', 'cervical', 'sore_throat', 'dental_pain', 'skin_infection'],
    findings: ['tender_soft', 'tonsillar_exudate'],
    redFlags: [],
    nextStep: '原発巣を特定（咽頭炎・歯科感染・皮膚感染）し治療。2-4週で縮小傾向→経過観察。再受診基準: 4週以上持続・増大傾向・B症状出現→再評価。',
    link: null,
    comment: '最も頻度が高い。感染巣のドレナージ領域のリンパ節が反応性に腫脹。柔らかく圧痛あり。原発巣治療で2-4週以内に縮小。',
  },
  // === 感染症 ===
  {
    id: 'ebv',
    name: '伝染性単核球症（EBV）',
    cat: '感染症',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['cervical', 'generalized', 'sore_throat', 'fever', 'fatigue', 'young_adult'],
    findings: ['tonsillar_exudate', 'splenomegaly'],
    redFlags: [],
    nextStep: '異型リンパ球確認（外注）。VCA-IgM/EBNA-IgG。脾腫→接触性スポーツ4週間禁止。アミノペニシリン系禁忌。',
    link: '/docs/010-Acute-URI/b279-infectious-mononucleosis',
    comment: '若年者の頸部リンパ節腫脹+咽頭炎+発熱+肝脾腫。全身性リンパ節腫脹が特徴。',
  },
  {
    id: 'hiv',
    name: 'HIV感染症（急性期/慢性期）',
    cat: '感染症',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['generalized', 'fever', 'rash', 'weight_loss', 'fatigue', 'sexual_risk'],
    findings: ['splenomegaly'],
    redFlags: [],
    nextStep: 'HIV抗原抗体検査。リスク行動歴（MSM・不特定多数の性交渉・注射薬物使用）を聴取。急性HIV症候群: IM様症候群（発熱+咽頭痛+リンパ節腫脹+皮疹）で発症。',
    link: null,
    comment: '急性HIV症候群はEBVに酷似（IM-like illness）。持続性全身性リンパ節腫脹（PGL）は慢性HIV感染の特徴。リスク行動歴がなくても検査閾値は低くすべき。',
  },
  {
    id: 'tuberculosis_ln',
    name: '結核性リンパ節炎',
    cat: '感染症',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['cervical', 'painless', 'slow_growth', 'fever', 'night_sweats', 'weight_loss'],
    findings: ['rubbery'],
    redFlags: [],
    nextStep: 'IGRA（T-SPOT/QFT）+胸部X線。結核疑い→保健所相談+専門医療機関紹介。穿刺培養は飛散リスクあり専門施設で。',
    link: null,
    comment: '頸部リンパ節腫脹が最多（scrofula）。波動を触れることも。肺結核の合併有無を確認（胸部X線）。日本は結核中蔓延国であることを忘れるな。',
  },
  {
    id: 'cat_scratch',
    name: '猫ひっかき病',
    cat: '感染症',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 1,
    symptoms: ['painful', 'cervical', 'axillary', 'cat_contact', 'fever'],
    findings: ['tender_soft', 'skin_lesion'],
    redFlags: [],
    nextStep: '猫との接触歴+ひっかき傷+所属リンパ節腫脹で臨床診断。多くは自然軽快（数週〜月）。膿瘍形成→穿刺ドレナージ。抗菌薬（AZM）は重症例に。再受診基準: 4週以上で増大持続・高熱持続・膿瘍形成→再受診。',
    link: null,
    comment: '猫（特に子猫）によるひっかき傷の1-3週後にドレナージ領域のリンパ節腫脹。Bartonella henselae。免疫正常者は自然軽快が多い。',
  },
  {
    id: 'secondary_syphilis',
    name: '第2期梅毒',
    cat: '感染症（性感染症）',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['generalized', 'painless', 'rash', 'sexual_risk'],
    findings: ['palm_sole_rash'],
    redFlags: ['palm_sole_rash'],
    nextStep: 'RPR/TPHA提出。全身性の無痛性リンパ節腫脹+手掌・足底の紅斑（バラ疹）は梅毒を強く疑う。',
    link: '/docs/255-Sexual-Infect/a513-secondary-syphilis',
    comment: '第2期梅毒は全身リンパ節腫脹を来す。手掌・足底のバラ疹、粘膜斑、扁平コンジローマが鑑別の鍵。性行為歴に関わらず検査提出。',
  },
  // === 悪性腫瘍 ===
  {
    id: 'malignant_lymphoma',
    name: '悪性リンパ腫',
    cat: '悪性腫瘍',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    symptoms: ['painless', 'over_2cm', 'slow_growth', 'persisting_4wks', 'fever', 'night_sweats', 'weight_loss', 'fatigue', 'young_adult'],
    findings: ['rubbery', 'splenomegaly', 'hepatomegaly'],
    redFlags: ['over_2cm', 'persisting_4wks'],
    nextStep: 'LDH+sIL-2R（補助的、正常でも否定不可）+CBC+ESR。B症状あり or 2cm超+増大持続→速やかに血液内科紹介（生検依頼）。4週間ルール: 感染源不明で4週以上持続→生検を検討。',
    link: null,
    comment: '無痛性+弾性硬+進行性増大±B症状（38℃以上の原因不明の発熱・盗汗・6ヶ月で10%以上の体重減少）。Hodgkinリンパ腫は若年者（15-35歳）の頸部/縦隔に好発。sIL-2Rはアグレッシブで高感度だがインドレントでは50-60%と低い。',
  },
  {
    id: 'metastatic',
    name: '転移性リンパ節腫脹',
    cat: '悪性腫瘍',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    symptoms: ['painless', 'over_2cm', 'supraclavicular', 'slow_growth', 'cancer_history'],
    findings: ['hard_fixed'],
    redFlags: ['supraclavicular', 'hard_fixed'],
    nextStep: '石様硬+不動+鎖骨上窩→転移性を強く疑う。左鎖骨上窩（Virchowリンパ節）=消化器癌（胃癌が典型）。右=肺癌/縦隔腫瘍。原発巣検索→CT施設紹介。',
    link: null,
    comment: '硬い+不動+鎖骨上窩=悪性転移の確率が最も高い。原発巣の検索が必須（胸部X線+CT紹介）。頸部の固定性リンパ節は頭頸部癌、腋窩は乳癌も鑑別。',
  },
  // === 自己免疫・その他 ===
  {
    id: 'sle',
    name: 'SLE',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['generalized', 'fever', 'rash', 'joint_pain', 'fatigue'],
    findings: ['splenomegaly'],
    redFlags: [],
    nextStep: 'ANA+抗dsDNA抗体+補体。リウマチ科紹介。',
    link: '/docs/220-rheumatology',
    comment: '若年女性。全身性リンパ節腫脹+蝶形紅斑+関節痛+漿膜炎。リンパ節腫脹はSLEの活動性を反映。',
  },
  {
    id: 'sarcoidosis',
    name: 'サルコイドーシス',
    cat: '全身性疾患',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 3,
    symptoms: ['generalized', 'fatigue', 'rash'],
    findings: [],
    redFlags: [],
    nextStep: 'ACE+リゾチーム+胸部X線（BHL: 両側肺門リンパ節腫脹）。眼科（ぶどう膜炎）。CT施設紹介（縦隔リンパ節）。',
    link: null,
    comment: '両側肺門リンパ節腫脹（BHL）が胸部X線で発見されることが多い。結節性紅斑+BHL+関節痛=Löfgren症候群。日本では若年女性と中年男性の二峰性分布。',
  },
  {
    id: 'kikuchi',
    name: '菊池病（壊死性リンパ節炎）',
    cat: '自己免疫',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['cervical', 'painful', 'fever', 'young_adult', 'fatigue'],
    findings: ['tender_soft'],
    redFlags: [],
    nextStep: '若年女性+頸部リンパ節腫脹+発熱が典型。自然軽快（1-4ヶ月）が多い。SLEとの鑑別（ANA提出）。持続する場合は生検で確定（血液内科紹介）。再受診基準: 4ヶ月以上遷延・新症状出現・ANA陽性→SLE精査。',
    link: null,
    comment: '20-30代女性に好発。頸部後三角のリンパ節腫脹+発熱+白血球減少が典型。悪性リンパ腫やSLEとの鑑別に生検が有用。自然軽快するが再発あり。',
  },
  {
    id: 'drug_induced',
    name: '薬剤性リンパ節腫脹',
    cat: '薬剤性',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['generalized', 'drug_history', 'rash'],
    findings: [],
    redFlags: [],
    nextStep: '被疑薬の同定と中止。フェニトイン・カルバマゼピン・アロプリノール・抗菌薬（ST合剤等）が代表。中止後4-8週で改善が典型。',
    link: null,
    comment: '薬剤開始後に全身性リンパ節腫脹+発疹+発熱を来すことがある（DIHS/DRESSの一部）。中止で改善→確認的診断。',
    alwaysShow: true,
  },
];

export const RED_FLAGS = [
  {
    conditions: ['supraclavicular'],
    message: '鎖骨上窩リンパ節: 悪性腫瘍の確率が最も高い。左（Virchow）=消化器癌、右=肺癌/縦隔腫瘍。速やかに精査紹介。',
    severity: 'critical',
  },
  {
    conditions: ['hard_fixed'],
    message: '硬い+不動（固定性）: 転移性悪性腫瘍を強く疑う。原発巣検索（CT紹介）。',
    severity: 'critical',
  },
  {
    conditions: ['over_2cm'],
    message: '2cm超+増大傾向: 悪性リンパ腫を除外。LDH/sIL-2R+血液内科紹介（生検検討）。',
    severity: 'warning',
  },
  {
    conditions: ['persisting_4wks'],
    message: '4週間以上持続（感染源不明）: 経過観察の延長ではなく生検を検討せよ（4週間ルール）。',
    severity: 'warning',
  },
  {
    conditions: ['night_sweats'],
    message: '盗汗（B症状）: 悪性リンパ腫を疑う。発熱+盗汗+体重減少=B症状。血液内科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['weight_loss'],
    message: '体重減少: 悪性腫瘍・結核・HIVを考慮。精査。',
    severity: 'warning',
  },
  {
    conditions: ['palm_sole_rash'],
    message: '手掌・足底の紅斑: 第2期梅毒（バラ疹）を除外。RPR/TPHA提出。',
    severity: 'warning',
  },
];
