/**
 * Diagnostic Booster — Undifferentiated Palpitations Data
 */

export const SYMPTOMS = [
  // 性状
  { id: 'rapid_regular', label: '速くて規則的（ドキドキ速い）', cat: '性状' },
  { id: 'irregular', label: '脈が不規則・バラバラ', cat: '性状' },
  { id: 'skipped_beat', label: '脈が飛ぶ・ドクンと一拍', cat: '性状' },
  { id: 'pounding', label: '胸がバクバク・ドンドン', cat: '性状' },
  // 発症
  { id: 'sudden_onset_offset', label: '突然始まり突然止まる', cat: '発症様式' },
  { id: 'gradual', label: '徐々に始まる', cat: '発症様式' },
  { id: 'exertional', label: '労作時に発症', cat: '発症様式' },
  { id: 'at_rest', label: '安静時に発症', cat: '発症様式' },
  // 持続
  { id: 'seconds', label: '秒〜数分で消失', cat: '持続時間' },
  { id: 'minutes_hours', label: '数分〜数時間持続', cat: '持続時間' },
  { id: 'persistent', label: '持続性（常にある）', cat: '持続時間' },
  { id: 'recurrent', label: '反復性', cat: '持続時間' },
  // 誘因
  { id: 'caffeine', label: 'カフェイン・エナジードリンク', cat: '誘因' },
  { id: 'alcohol', label: 'アルコール', cat: '誘因' },
  { id: 'stress', label: 'ストレス・不安', cat: '誘因' },
  // 随伴
  { id: 'syncope', label: '失神・前失神', cat: '随伴症状' },
  { id: 'chest_pain', label: '胸痛', cat: '随伴症状' },
  { id: 'dyspnea', label: '呼吸困難', cat: '随伴症状' },
  { id: 'dizziness', label: 'めまい', cat: '随伴症状' },
  { id: 'cold_sweat', label: '冷汗', cat: '随伴症状' },
  { id: 'hyperventilation', label: '過換気・四肢しびれ', cat: '随伴症状' },
  { id: 'tremor', label: '手指振戦', cat: '随伴症状' },
  { id: 'weight_loss', label: '体重減少', cat: '随伴症状' },
  { id: 'heat_intolerance', label: '暑がり・発汗過多', cat: '随伴症状' },
  // リスク
  { id: 'cardiac_history', label: '心疾患の既往', cat: 'リスク' },
  { id: 'family_sudden_death', label: '家族歴に若年突然死', cat: 'リスク' },
  { id: 'young', label: '若年者（40歳未満）', cat: 'リスク' },
];

export const FINDINGS = [
  // ECG
  { id: 'ecg_af', label: 'ECG: 心房細動（f波・RR不整）', triggers: ['irregular', 'persistent', 'minutes_hours'] },
  { id: 'ecg_aflutter', label: 'ECG: 心房粗動（鋸歯状波）', triggers: ['rapid_regular', 'persistent'] },
  { id: 'ecg_psvt', label: 'ECG: PSVT（整な狭QRS頻脈 HR>150）', triggers: ['sudden_onset_offset', 'rapid_regular'] },
  { id: 'ecg_pvc', label: 'ECG: 心室期外収縮（幅広QRS・先行P波なし）', triggers: ['skipped_beat'] },
  { id: 'ecg_pac', label: 'ECG: 上室期外収縮（正常QRS・異所性P波）', triggers: ['skipped_beat'] },
  { id: 'ecg_delta_wave', label: 'ECG: δ波+短PR（WPW）', triggers: ['sudden_onset_offset', 'young', 'syncope', 'family_sudden_death'] },
  { id: 'ecg_brugada', label: 'ECG: V1-V3 coved型ST上昇（Brugada）', triggers: ['syncope', 'family_sudden_death', 'at_rest'] },
  { id: 'ecg_qtc_prolonged', label: 'ECG: QTc延長', triggers: ['syncope', 'family_sudden_death'] },
  { id: 'ecg_sinus_tachy', label: 'ECG: 洞性頻脈（整・P波正常・HR>100）', triggers: ['gradual', 'exertional', 'stress'] },
  // 聴診・身体所見
  { id: 'murmur', label: '心雑音', triggers: ['exertional', 'cardiac_history'] },
  { id: 'thyroid_enlargement', label: '甲状腺腫大', triggers: ['tremor', 'weight_loss', 'heat_intolerance'] },
  { id: 'exophthalmos', label: '眼球突出', triggers: ['tremor', 'weight_loss', 'heat_intolerance'] },
  // バイタル（常時表示）
  { id: 'irregular_pulse', label: '脈不整（触診）', triggers: [] },
  { id: 'tachycardia', label: '頻脈 HR>100', triggers: [] },
  { id: 'bradycardia', label: '徐脈 HR<50', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 不整脈 ===
  {
    id: 'atrial_fibrillation',
    name: '心房細動（Af）',
    cat: '不整脈',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 3,
    symptoms: ['irregular', 'minutes_hours', 'persistent', 'recurrent', 'dyspnea', 'dizziness'],
    findings: ['ecg_af', 'irregular_pulse', 'tachycardia'],
    redFlags: ['ecg_af'],
    nextStep: 'CHA2DS2-VAScスコア評価→抗凝固薬の適応判断。心拍数コントロール（β遮断薬 or Ca拮抗薬）。甲状腺チェック（Af新規発症の原因）。心エコー（当院不可→循環器紹介）。再受診基準: 失神・胸痛・呼吸困難→即受診。',
    link: '/docs/090-cardiovascular',
    comment: '脈の不整+RR間隔不整。脳梗塞の主要原因→抗凝固薬の適応を必ず評価。発作性Afは受診時の洞調律でも否定不可→ホルター。アルコール（Holiday Heart）・甲状腺が原因のことも。',
  },
  {
    id: 'atrial_flutter',
    name: '心房粗動（AFL）',
    cat: '不整脈',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['rapid_regular', 'persistent', 'minutes_hours', 'dyspnea'],
    findings: ['ecg_aflutter', 'tachycardia'],
    redFlags: [],
    nextStep: '鋸歯状波（II/III/aVF）で診断。HR約150（2:1伝導）が典型。循環器紹介（カテーテルアブレーション）。再受診基準: 失神・胸痛・呼吸困難→即受診。',
    link: null,
    comment: 'HR約150で整な頻脈→AFLを疑え。2:1伝導でf波が見えにくいことあり。Afと同様に血栓リスクあり→抗凝固薬評価。',
  },
  {
    id: 'psvt',
    name: '発作性上室性頻拍（PSVT）',
    cat: '不整脈',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['sudden_onset_offset', 'rapid_regular', 'seconds', 'minutes_hours', 'recurrent', 'dizziness', 'young'],
    findings: ['ecg_psvt', 'tachycardia'],
    redFlags: [],
    nextStep: '発作時: Valsalva手技・冷水顔面浸漬で停止試行。無効→循環器紹介（ATP急速静注 or カテーテルアブレーション）。非発作時ECG正常が多い→ホルター。再受診基準: 失神・長時間止まらない→即受診。',
    link: null,
    comment: '「突然始まり突然止まる」整な頻脈（HR150-250）が典型。若年女性に多い。AVNRT（房室結節リエントリー）が最多。予後は良好だが失神を伴う場合は要精査。',
  },
  {
    id: 'pvc',
    name: '心室期外収縮（PVC）',
    cat: '不整脈',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['skipped_beat', 'pounding', 'at_rest', 'recurrent'],
    findings: ['ecg_pvc'],
    redFlags: [],
    nextStep: 'ECGで幅広QRS+先行P波なし。単発・単形性・自覚症状のみなら経過観察可。多発（総心拍の10%以上）・多源性・連発→ホルター+循環器紹介。再受診基準: 失神・持続する動悸→即受診。',
    link: null,
    comment: '「ドクンと一拍」「脈が飛ぶ」が典型的な訴え。健常者でも非常に多い。カフェイン・ストレス・睡眠不足で増加。器質的心疾患の合併がなければ予後良好。',
  },
  {
    id: 'pac',
    name: '上室期外収縮（PAC/SVPC）',
    cat: '不整脈',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['skipped_beat', 'pounding', 'recurrent'],
    findings: ['ecg_pac'],
    redFlags: [],
    nextStep: '正常QRS+異所性P波。ほぼ全ての人に生じる生理的現象。症状が強い場合はβ遮断薬少量。器質的心疾患の合併確認。',
    link: null,
    comment: 'PVCと同様「脈が飛ぶ」感覚。QRS幅が正常で先行する異所性P波がある。多発PACはAfへの移行リスクあり→経過観察。',
  },
  // === 危険な不整脈基盤 ===
  {
    id: 'wpw',
    name: 'WPW症候群',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['sudden_onset_offset', 'young', 'syncope', 'family_sudden_death', 'rapid_regular'],
    findings: ['ecg_delta_wave'],
    redFlags: ['ecg_delta_wave', 'syncope', 'family_sudden_death'],
    nextStep: 'δ波+短PR→WPW。Af合併時にVFリスク（偽性VT）。即循環器紹介（カテーテルアブレーション）。β遮断薬・ジギタリス・Ca拮抗薬はWPW+Afで禁忌。',
    link: null,
    comment: 'ECGでδ波（QRS立ち上がりの鈍い段差）+短PR間隔+幅広QRS。若年者の動悸。WPW+Afは致死的→副伝導路を介した急速伝導でVFに移行しうる。',
  },
  {
    id: 'brugada',
    name: 'Brugada症候群',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['syncope', 'family_sudden_death', 'at_rest'],
    findings: ['ecg_brugada'],
    redFlags: ['ecg_brugada', 'family_sudden_death'],
    nextStep: 'V1-V3でcoved型ST上昇→Brugada疑い。即循環器紹介。ICD適応の判断。',
    link: null,
    comment: '夜間・安静時の失神/突然死（ポックリ病）。東南アジア系男性に多い。ECG Type 1（coved型）が診断的。Type 2/3は薬物負荷で誘発。',
  },
  {
    id: 'long_qt',
    name: 'QT延長症候群',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['syncope', 'family_sudden_death'],
    findings: ['ecg_qtc_prolonged'],
    redFlags: ['ecg_qtc_prolonged', 'family_sudden_death'],
    nextStep: 'QTc延長（男>440ms/女>460ms）→循環器紹介。QT延長誘発薬（マクロライド・フルオロキノロン・三環系・ドンペリドン等）の中止/変更。電解質（K/Mg/Ca）補正。',
    link: null,
    comment: '先天性（遺伝子異常）と後天性（薬剤性・低K・低Mg）。TdP（多形性VT）→心停止リスク。薬剤歴と家族歴が鍵。',
  },
  // === 洞性頻脈の原因 ===
  {
    id: 'hyperthyroidism',
    name: '甲状腺機能亢進症（バセドウ病）',
    cat: '内分泌',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['rapid_regular', 'gradual', 'persistent', 'tremor', 'weight_loss', 'heat_intolerance'],
    findings: ['ecg_sinus_tachy', 'tachycardia', 'thyroid_enlargement', 'exophthalmos'],
    redFlags: [],
    nextStep: 'TSH+FT3+FT4。TSH低値+FT3/FT4高値→甲状腺機能亢進症。チアマゾール（メルカゾール）開始。甲状腺クリーゼ（高熱+頻脈+意識障害）→即搬送。再受診基準: 内服開始後2-4週で効果判定+肝機能チェック。',
    link: '/docs/130-endocrine',
    comment: '動悸+頻脈+手指振戦+体重減少+発汗過多+暑がり。Af新規発症の原因であることも。TSHは動悸患者で必ずチェック。',
  },
  {
    id: 'anemia_palpitations',
    name: '貧血',
    cat: '血液',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['rapid_regular', 'exertional', 'gradual', 'persistent', 'dyspnea', 'dizziness'],
    findings: ['ecg_sinus_tachy', 'tachycardia'],
    redFlags: [],
    nextStep: 'CBC+フェリチン。貧血→原因検索。',
    link: '/docs/320-hematology',
    comment: '代償性の洞性頻脈。労作時に動悸+息切れ。眼瞼結膜蒼白が簡便なスクリーニング。',
  },
  {
    id: 'panic_disorder',
    name: 'パニック障害',
    cat: '精神科',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['rapid_regular', 'sudden_onset_offset', 'hyperventilation', 'stress', 'at_rest', 'cold_sweat', 'chest_pain', 'recurrent'],
    findings: ['ecg_sinus_tachy'],
    redFlags: [],
    nextStep: '器質的疾患を除外した上での診断。ECG正常+TSH/CBC正常+典型的な過換気+不安発作→パニック障害。精神科/心療内科紹介。再受診基準: 失神・胸痛が新たに出現→再評価（Killer除外）。',
    link: '/docs/170-psychiatry',
    comment: '動悸+過換気+四肢しびれ+恐怖感+「死ぬかもしれない」。除外診断。初発時は心原性を必ず除外。「パニックだろう」は最後の診断。',
    alwaysShow: true,
  },
  {
    id: 'dehydration_fever',
    name: '脱水・発熱による洞性頻脈',
    cat: '全身',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['rapid_regular', 'gradual', 'exertional'],
    findings: ['ecg_sinus_tachy', 'tachycardia'],
    redFlags: [],
    nextStep: '原因治療（補液・解熱）。持続する場合は他の原因検索。',
    link: null,
    comment: '洞性頻脈の最多原因。原因が明らかなら治療で改善。不釣り合いな頻脈（微熱でHR>120等）は他の原因（PE・敗血症等）を考慮。',
  },
  {
    id: 'caffeine_substance',
    name: 'カフェイン・物質誘発性',
    cat: '外因性',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['rapid_regular', 'skipped_beat', 'caffeine', 'recurrent', 'pounding'],
    findings: ['ecg_sinus_tachy'],
    redFlags: [],
    nextStep: 'カフェイン・エナジードリンク・アルコールの摂取量を聴取。減量/中止指導。再受診基準: 減量後も改善なし2週→再評価。失神→即受診。',
    link: null,
    comment: 'コーヒー3-4杯/日以上、エナジードリンク常用、大量飲酒後（Holiday Heart Syndrome→一過性Af）が原因。摂取歴の詳細聴取が鑑別の鍵。',
  },
  {
    id: 'inappropriate_sinus_tachy',
    name: '不適切洞性頻脈（IST）',
    cat: '自律神経',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 2,
    symptoms: ['rapid_regular', 'persistent', 'at_rest', 'exertional', 'recurrent', 'young'],
    findings: ['ecg_sinus_tachy', 'tachycardia'],
    redFlags: [],
    nextStep: '安静時HR>100が持続+器質的原因を全て除外→IST。甲状腺・貧血・心不全・PE・薬剤を除外してからの診断。イバブラジン（循環器紹介で検討）。',
    link: null,
    comment: '若年女性に多い。安静時でもHR>100。器質的疾患の除外診断。POTS（体位性起立性頻脈症候群）との鑑別も必要。',
  },
  {
    id: 'drug_induced_palpitations',
    name: '薬剤性動悸',
    cat: '薬剤性',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['rapid_regular', 'pounding', 'recurrent'],
    findings: ['ecg_sinus_tachy', 'tachycardia'],
    redFlags: [],
    nextStep: '被疑薬の同定。気管支拡張薬（β2刺激薬）・甲状腺ホルモン過量・テオフィリン・交感神経刺激薬が代表。用量調整or代替薬。再受診基準: 変更後2-4週で効果判定。失神→即受診。',
    link: null,
    comment: 'β2刺激薬（SABA/LABA）、甲状腺ホルモン（レボチロキシン過量）、テオフィリン、エフェドリン含有総合感冒薬、漢方（麻黄含有）が原因。',
    alwaysShow: true,
  },
];

export const RED_FLAGS = [
  {
    conditions: ['syncope'],
    message: '失神を伴う動悸: 致死的不整脈（VT/VF・WPW+Af・Brugada・QT延長）の可能性。12誘導ECG必須。循環器紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['exertional'],
    message: '労作時発症の動悸: 器質的心疾患（AS・HOCM・冠動脈疾患）の除外必須。心エコー（当院不可→循環器紹介）。',
    severity: 'critical',
  },
  {
    conditions: ['family_sudden_death'],
    message: '家族歴に若年突然死: WPW・Brugada・QT延長・HCMを疑う。ECG+循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_delta_wave'],
    message: 'δ波+短PR: WPW症候群。Af合併時にVFリスク。循環器紹介。β遮断薬・ジギタリス・Ca拮抗薬はWPW+Afで禁忌。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_brugada'],
    message: 'Brugada型ECG: V1-V3 coved型ST上昇。即循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_qtc_prolonged'],
    message: 'QTc延長: TdP→心停止リスク。QT延長誘発薬中止+電解質補正+循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_af'],
    message: '心房細動: 脳梗塞リスク。CHA2DS2-VASc評価→抗凝固薬の適応判断。循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['chest_pain'],
    message: '胸痛+動悸: ACS・PE・大動脈解離を考慮。12誘導ECG+搬送準備。',
    severity: 'warning',
  },
  {
    conditions: ['dyspnea'],
    message: '呼吸困難+動悸: 心不全・PE・貧血を鑑別。SpO2+BNP+胸部X線。',
    severity: 'warning',
  },
  {
    conditions: ['bradycardia'],
    message: '徐脈: 洞不全症候群・房室ブロックを考慮。ECG確認+循環器紹介。',
    severity: 'warning',
  },
];
