/**
 * Diagnostic Booster — Undifferentiated Polyarthralgia Data
 */

export const SYMPTOMS = [
  // 関節数・分布
  { id: 'monoarticular', label: '単関節（1関節）', cat: '関節数' },
  { id: 'oligoarticular', label: '少数関節（2-4関節）', cat: '関節数' },
  { id: 'polyarticular', label: '多関節（5関節以上）', cat: '関節数' },
  { id: 'symmetric', label: '左右対称', cat: '分布' },
  { id: 'asymmetric', label: '非対称', cat: '分布' },
  { id: 'small_joints', label: '小関節（手指MP/PIP/MTP）', cat: '罹患関節' },
  { id: 'large_joints', label: '大関節（膝/肩/股/肘/足首）', cat: '罹患関節' },
  { id: 'dip', label: 'DIP関節', cat: '罹患関節' },
  { id: 'shoulder_hip_girdle', label: '肩帯・腰帯（両肩・両股）', cat: '罹患関節' },
  // こわばり
  { id: 'stiffness_long', label: '朝のこわばり 30分以上', cat: 'こわばり' },
  { id: 'stiffness_short', label: '朝のこわばり 30分未満', cat: 'こわばり' },
  // 発症
  { id: 'acute_onset', label: '急性発症（時間〜日）', cat: '発症' },
  { id: 'chronic', label: '慢性（数週〜月以上）', cat: '発症' },
  // 随伴
  { id: 'fever', label: '発熱', cat: '随伴' },
  { id: 'rash', label: '皮疹', cat: '随伴' },
  { id: 'oral_ulcer', label: '口腔内潰瘍', cat: '随伴' },
  { id: 'eye_symptoms', label: '眼症状（充血/ドライアイ）', cat: '随伴' },
  { id: 'raynaud', label: 'レイノー現象', cat: '随伴' },
  { id: 'muscle_weakness', label: '筋力低下（近位筋）', cat: '随伴' },
  { id: 'back_pain', label: '腰痛（炎症性: 安静で悪化）', cat: '随伴' },
  { id: 'preceding_infection', label: '先行感染（尿道炎/腸炎）', cat: '随伴' },
  { id: 'dorsal_edema', label: '手背・足背の浮腫', cat: '随伴' },
  // リスク
  { id: 'age_over50', label: '50歳以上', cat: 'リスク' },
  { id: 'psoriasis_history', label: '乾癬の既往', cat: 'リスク' },
  { id: 'hyperuricemia', label: '尿酸値高値の既往', cat: 'リスク' },
  { id: 'young_female', label: '若年女性', cat: 'リスク' },
  { id: 'temporal_headache', label: '新規の側頭部頭痛/顎跛行/視力障害', cat: '随伴' },
];

export const FINDINGS = [
  { id: 'joint_swelling', label: '関節腫脹・熱感・発赤', triggers: ['monoarticular', 'acute_onset', 'fever', 'stiffness_long'] },
  { id: 'squeeze_test', label: 'Squeeze test陽性（MCP/MTP圧迫で疼痛）', triggers: ['small_joints', 'symmetric', 'stiffness_long'] },
  { id: 'rheumatoid_nodule', label: 'リウマトイド結節', triggers: ['small_joints', 'symmetric', 'chronic'] },
  { id: 'butterfly_rash', label: '蝶形紅斑', triggers: ['rash', 'young_female'] },
  { id: 'gottron', label: 'ゴットロン丘疹（手指関節伸側の紅斑）', triggers: ['rash', 'muscle_weakness'] },
  { id: 'psoriatic_nails', label: '爪変化（点状陥凹・爪甲剥離）', triggers: ['dip', 'psoriasis_history'] },
  { id: 'tophi', label: '痛風結節（耳介・肘・指）', triggers: ['monoarticular', 'hyperuricemia'] },
  // 常時表示
  { id: 'elevated_crp_esr', label: 'CRP/ESR上昇', triggers: [] },
  { id: 'elevated_ck', label: 'CK上昇', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 緊急 ===
  {
    id: 'septic_arthritis',
    name: '化膿性関節炎',
    cat: '感染症 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    symptoms: ['monoarticular', 'acute_onset', 'fever', 'large_joints'],
    findings: ['joint_swelling', 'elevated_crp_esr'],
    redFlags: ['joint_swelling'],
    nextStep: '単関節の急性腫脹+発熱→化膿性関節炎を疑う。即日整形外科紹介（関節穿刺・培養が必要）。24-48時間の遅延で不可逆的関節破壊が進行。経口抗菌薬で様子を見ない。',
    link: null,
    comment: '膝が最多。黄色ブドウ球菌が主因。糖尿病・人工関節・免疫抑制がリスク。関節液のグラム染色・培養が確定診断。',
  },
  // === 結晶性関節炎 ===
  {
    id: 'gout',
    name: '痛風',
    cat: '結晶性関節炎',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['monoarticular', 'acute_onset', 'large_joints', 'hyperuricemia'],
    findings: ['joint_swelling', 'tophi'],
    redFlags: [],
    nextStep: '第1MTP関節（足の親指付け根）の急性発赤・腫脹が典型。尿酸値（発作中は低下することあり）。NSAIDs or コルヒチン。痛風結節あり=慢性痛風→尿酸降下薬。再受診基準: 発熱+複数関節→化膿性との鑑別で紹介。',
    link: '/docs/120-Dyslipidemia',
    comment: '中年男性に多い。飲酒・肉食・利尿薬がリスク。発作中の尿酸値は正常のことがある→発作後2-4週で再検。',
  },
  {
    id: 'pseudogout',
    name: '偽痛風（CPPD結晶沈着症）',
    cat: '結晶性関節炎',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['monoarticular', 'acute_onset', 'large_joints', 'age_over50'],
    findings: ['joint_swelling'],
    redFlags: [],
    nextStep: '膝関節が最多。X線で軟骨石灰化（chondrocalcinosis）。関節穿刺（CPPD結晶）→整形外科紹介。NSAIDs or コルヒチン。再受診基準: 発熱出現→化膿性との鑑別で即受診。',
    link: null,
    comment: '高齢者の急性単関節炎。膝が最多。痛風と異なり尿酸は正常。化膿性関節炎との臨床鑑別は困難→関節穿刺が必要。',
  },
  // === 炎症性（膠原病）===
  {
    id: 'rheumatoid_arthritis',
    name: '関節リウマチ（RA）',
    cat: '膠原病',
    freq: '中〜高頻度',
    prevalenceWeight: 7,
    severityWeight: 3,
    symptoms: ['polyarticular', 'symmetric', 'small_joints', 'stiffness_long', 'chronic'],
    findings: ['squeeze_test', 'rheumatoid_nodule', 'elevated_crp_esr'],
    redFlags: [],
    nextStep: 'RF+抗CCP抗体+CRP/ESR。抗CCP抗体陽性は特異度95-99%（RF陰性でも早期RA拾い上げ可能）。手指X線（骨びらん）。4週間以上の多関節炎→リウマチ科紹介（治療の窓: 早期介入が関節破壊を防ぐ）。再受診基準: 関節腫脹の急速悪化→即受診。',
    link: '/docs/220-Rheumatology',
    comment: '対称性+小関節（MP/PIP/MTP）+朝のこわばり60分以上が典型。RF陰性RA（seronegative RA）は20-30%存在→抗CCP抗体で拾う。DIPは侵さない（DIP→OA or PsA）。',
  },
  {
    id: 'sle',
    name: 'SLE',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['polyarticular', 'symmetric', 'rash', 'oral_ulcer', 'young_female', 'fever', 'raynaud'],
    findings: ['butterfly_rash', 'elevated_crp_esr'],
    redFlags: ['butterfly_rash'],
    nextStep: 'ANA+抗dsDNA抗体+補体（C3/C4）+CBC+尿検査（蛋白尿）。リウマチ科紹介。再受診基準: 血尿・浮腫・呼吸困難・高熱→即受診。',
    link: '/docs/220-Rheumatology',
    comment: '若年女性。蝶形紅斑+光線過敏+口腔潰瘍+多関節炎+漿膜炎+腎障害。ANA陽性（感度95%以上だが特異度低い）。関節炎は非びらん性（RAと異なりX線で骨びらんを来さない）。',
  },
  {
    id: 'pmr',
    name: 'リウマチ性多発筋痛症（PMR）',
    cat: '膠原病',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['shoulder_hip_girdle', 'stiffness_long', 'age_over50', 'symmetric', 'fever', 'temporal_headache'],
    findings: ['elevated_crp_esr'],
    redFlags: [],
    nextStep: 'ESR（著明高値が典型）+CRP。プレドニゾロン15mg/日で劇的改善（24-72時間以内）→診断的治療。1週間で反応なし→PMR診断を再考。頭痛/視力障害/顎跛行→GCA合併を疑い即日眼科+リウマチ科紹介。再受診基準: 頭痛・視力変化出現→即受診（GCA=失明リスク）。',
    link: '/docs/220-Rheumatology',
    comment: '50歳以上+両肩・腰帯の痛み+朝のこわばり+ESR著明高値。「関節痛」というよりも「肩や腰回りが痛くて動けない」。PMRの15-20%にGCA合併→頭痛・顎跛行を聴取。',
  },
  {
    id: 'rs3pe',
    name: 'RS3PE症候群',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 3,
    symptoms: ['acute_onset', 'age_over50', 'symmetric', 'dorsal_edema', 'stiffness_long'],
    findings: ['elevated_crp_esr'],
    redFlags: [],
    nextStep: '高齢者+手背・足背の圧痕性浮腫+急性対称性多関節炎。悪性腫瘍の合併（paraneoplastic）が約15-30%→年齢に応じたがんスクリーニング。プレドニゾロンで改善。リウマチ科紹介。',
    link: null,
    comment: '高齢男性に多い。手背・足背のpitting edemaが特徴的。PMRとの鑑別。悪性腫瘍随伴症候群として出現することがある→がんスクリーニングを忘れるな。',
  },
  {
    id: 'dermatomyositis',
    name: '皮膚筋炎/多発性筋炎',
    cat: '膠原病',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['muscle_weakness', 'rash', 'polyarticular', 'fever'],
    findings: ['gottron', 'elevated_ck', 'elevated_crp_esr'],
    redFlags: ['elevated_ck', 'muscle_weakness'],
    nextStep: 'CK+アルドラーゼ+抗ARS抗体。ゴットロン丘疹+ヘリオトロープ疹が診断的。悪性腫瘍合併（特に皮膚筋炎で30-40%）→がんスクリーニング。リウマチ科紹介。再受診基準: 嚥下困難・呼吸困難→即受診（間質性肺炎・嚥下障害リスク）。',
    link: null,
    comment: '近位筋筋力低下（階段昇降・起立困難）+特徴的皮疹。CK上昇+近位筋力低下は必ず本疾患を鑑別。悪性腫瘍随伴として発症することがある。',
  },
  // === 脊椎関節炎 ===
  {
    id: 'reactive_arthritis',
    name: '反応性関節炎',
    cat: '脊椎関節炎',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 2,
    symptoms: ['oligoarticular', 'asymmetric', 'large_joints', 'acute_onset', 'preceding_infection', 'eye_symptoms', 'back_pain'],
    findings: ['joint_swelling', 'elevated_crp_esr'],
    redFlags: [],
    nextStep: '先行感染（尿道炎/腸炎）の1-4週後に発症する非対称性関節炎。クラミジア/サルモネラ/カンピロバクター等が原因。NSAIDs。遷延→リウマチ科紹介。',
    link: null,
    comment: '旧称Reiter症候群（関節炎+尿道炎+結膜炎の三徴）。先行感染歴が鑑別の鍵。HLA-B27関連。若年男性に多い。',
  },
  {
    id: 'psoriatic_arthritis',
    name: '乾癬性関節炎（PsA）',
    cat: '脊椎関節炎',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['dip', 'asymmetric', 'psoriasis_history', 'back_pain', 'chronic'],
    findings: ['psoriatic_nails', 'joint_swelling'],
    redFlags: [],
    nextStep: '乾癬+関節炎。DIP関節の炎症（RAでは侵さない）+爪変化が特徴。皮膚症状が軽微/先行しないことも（arthritis before psoriasis）。リウマチ科/皮膚科紹介。',
    link: null,
    comment: '乾癬患者の約30%に関節炎を合併。DIP関節炎+ソーセージ指（指趾炎/dactylitis）+爪病変が特徴的パターン。5つの臨床型（対称性多関節型はRAと酷似）。',
  },
  // === 非炎症性 ===
  {
    id: 'osteoarthritis',
    name: '変形性関節症（OA）',
    cat: '非炎症性',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['dip', 'large_joints', 'stiffness_short', 'chronic', 'age_over50'],
    findings: [],
    redFlags: [],
    nextStep: 'DIP関節（Heberden結節）/膝/股が典型。朝のこわばり30分未満。CRP/ESR正常。X線（関節裂隙狭小化・骨棘）。NSAIDs+運動療法+体重管理。再受診基準: 急性腫脹+発熱→化膿性/結晶性の除外。',
    link: '/docs/230-Orthopedics',
    comment: '最も頻度が高い関節疾患。加齢+肥満+関節負荷が危険因子。DIP（Heberden結節）・PIP（Bouchard結節）・膝・股が好発。炎症マーカーは正常。',
    alwaysShow: true,
  },
  // === ウイルス性 ===
  {
    id: 'viral_arthritis',
    name: 'ウイルス性関節炎',
    cat: '感染症',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['polyarticular', 'symmetric', 'acute_onset', 'rash', 'fever'],
    findings: ['elevated_crp_esr'],
    redFlags: [],
    nextStep: '先行するウイルス感染（発熱・発疹・咽頭痛）+対称性多関節痛→ウイルス性。パルボウイルスB19（成人では関節症状が主体）、HBV、HCV、風疹。多くは自然軽快（2-6週）。NSAIDs。再受診基準: 6週以上遷延→RA精査。',
    link: null,
    comment: 'ウイルス感染後の一過性多関節痛。パルボB19は成人女性で関節症状が強い。自然軽快が原則。6週以上遷延する場合はRAとの鑑別が必要→RF/抗CCP提出。',
  },
];

export const RED_FLAGS = [
  {
    // 安全側設計: joint_swelling単独でも発火（化膿性の見逃し=関節喪失のため過剰警告を許容）
    conditions: ['joint_swelling'],
    message: '関節腫脹・熱感: 単関節+急性+発熱なら化膿性関節炎を疑う。即日整形外科紹介（関節穿刺）。24-48時間の遅延で関節破壊。',
    severity: 'critical',
  },
  {
    conditions: ['temporal_headache'],
    message: '側頭部頭痛/顎跛行/視力障害: GCA（巨細胞性動脈炎）を疑う。失明リスク。ESR正常でも否定不可。プレドニゾロン先行投与を検討+即日眼科+リウマチ科紹介。',
    severity: 'critical',
  },
  {
    conditions: ['elevated_ck'],
    message: 'CK上昇+近位筋力低下: 皮膚筋炎/多発性筋炎を疑う。悪性腫瘍合併あり。リウマチ科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['muscle_weakness'],
    message: '近位筋筋力低下（階段昇降・起立困難）: 筋炎・甲状腺疾患・副腎不全を鑑別。CK+TSH。',
    severity: 'warning',
  },
  {
    conditions: ['butterfly_rash'],
    message: '蝶形紅斑: SLEを疑う。ANA+抗dsDNA+補体+腎機能。リウマチ科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['fever'],
    message: '発熱+関節炎: 化膿性関節炎（単関節+急性なら緊急）・ウイルス性・膠原病・反応性を鑑別。',
    severity: 'warning',
  },
];
