/**
 * Diagnostic Booster — Undifferentiated Rash Data v2
 * 3-agent audit v1 全指摘対応済み
 */

export const SYMPTOMS = [
  { id: 'erythema', label: '紅斑（赤い斑）', cat: '原発疹' },
  { id: 'papule', label: '丘疹（ブツブツ）', cat: '原発疹' },
  { id: 'vesicle', label: '水疱', cat: '原発疹' },
  { id: 'pustule', label: '膿疱', cat: '原発疹' },
  { id: 'wheal', label: '膨疹（一過性の膨隆）', cat: '原発疹' },
  { id: 'purpura', label: '紫斑（圧迫で消退しない）', cat: '原発疹' },
  { id: 'nodule', label: '結節（皮下の硬い腫瘤）', cat: '原発疹' },
  { id: 'scale', label: '鱗屑（カサカサ・フケ状）', cat: '続発疹' },
  { id: 'crust', label: '痂皮（かさぶた）', cat: '続発疹' },
  { id: 'erosion', label: 'びらん・潰瘍', cat: '続発疹' },
  { id: 'lichenification', label: '苔癬化（皮膚の肥厚・粗造化）', cat: '続発疹' },
  { id: 'annular', label: '環状（リング状）', cat: '配列' },
  { id: 'linear', label: '線状', cat: '配列' },
  { id: 'dermatomal', label: 'デルマトーム（片側帯状）', cat: '配列' },
  { id: 'symmetric', label: '左右対称', cat: '配列' },
  { id: 'scattered', label: '散在性・汎発性', cat: '配列' },
  { id: 'sun_exposed', label: '露光部（顔・手背・前腕）', cat: '分布' },
  { id: 'flexural', label: '屈側（肘窩・膝窩）', cat: '分布' },
  { id: 'extensor', label: '伸側（肘・膝）', cat: '分布' },
  { id: 'seborrheic', label: '脂漏部位（頭皮・眉間・鼻唇溝）', cat: '分布' },
  { id: 'palms_soles', label: '手掌・足底', cat: '分布' },
  { id: 'contact_area', label: '接触部位限定', cat: '分布' },
  { id: 'trunk', label: '体幹主体', cat: '分布' },
  { id: 'pruritus', label: '掻痒（かゆい）', cat: '自覚症状' },
  { id: 'pain', label: '疼痛', cat: '自覚症状' },
  { id: 'burning', label: '灼熱感', cat: '自覚症状' },
  { id: 'asymptomatic', label: '無症状', cat: '自覚症状' },
  { id: 'acute', label: '急性（数日以内）', cat: '経過' },
  { id: 'chronic', label: '慢性（数週〜月以上）', cat: '経過' },
  { id: 'recurrent', label: '再発性', cat: '経過' },
  { id: 'steroid_worsened', label: 'ステロイド外用で悪化/一時改善→再燃', cat: '経過' },
  { id: 'treatment_resistant', label: '6ヶ月以上治療抵抗性', cat: '経過' },
  { id: 'new_drug', label: '新規薬剤開始あり', cat: '誘因' },
  { id: 'fever', label: '発熱', cat: '全身' },
  { id: 'joint_pain', label: '関節痛', cat: '全身' },
  { id: 'mucosal', label: '粘膜症状（口腔・眼・陰部）', cat: '全身' },
  { id: 'sexual_risk', label: '性行為歴あり', cat: 'リスク' },
];

export const FINDINGS = [
  { id: 'nikolsky_positive', label: 'Nikolsky sign陽性（正常皮膚が擦ると剥離）', triggers: ['vesicle', 'erosion', 'scattered', 'new_drug', 'mucosal'] },
  { id: 'auspitz_sign', label: 'Auspitz sign陽性（鱗屑剥離後の点状出血）', triggers: ['scale', 'erythema', 'extensor'] },
  { id: 'koebner', label: 'Koebner現象（外傷部に新生皮疹）', triggers: ['scale', 'erythema'] },
  { id: 'central_clearing', label: '辺縁隆起+中心治癒（環状）', triggers: ['annular', 'erythema', 'scale'] },
  { id: 'koh_positive', label: 'KOH直接鏡検 陽性（外注結果）', triggers: ['scale', 'annular', 'steroid_worsened'] },
  { id: 'mucosal_erosion', label: '粘膜びらん（口腔・眼・陰部）', triggers: ['mucosal', 'fever', 'new_drug', 'erosion'] },
  { id: 'target_lesion', label: '標的状病変（target lesion）', triggers: ['erythema', 'symmetric', 'palms_soles'] },
  { id: 'palm_sole_rash', label: '手掌・足底の紅斑', triggers: ['palms_soles', 'scattered', 'sexual_risk'] },
  { id: 'lymphadenopathy', label: '全身リンパ節腫脹', triggers: ['scattered', 'fever', 'sexual_risk'] },
  { id: 'dermoscopy_finding', label: 'ダーモスコピー所見あり', triggers: [] },
  { id: 'fever_high', label: '高熱 ≥38.5℃', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 緊急 ===
  {
    id: 'sjs_ten',
    name: 'SJS / TEN',
    cat: '薬疹 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['erythema', 'erosion', 'scattered', 'new_drug', 'fever', 'mucosal', 'acute', 'pain', 'burning'],
    findings: ['nikolsky_positive', 'mucosal_erosion', 'fever_high'],
    redFlags: ['nikolsky_positive', 'mucosal_erosion'],
    nextStep: '被疑薬の即時中止。即日皮膚科紹介/搬送。死亡率: SJS 1-5%、TEN 25-35%。',
    link: '/docs/200-dermatitis/l270-drug-eruption',
    comment: '薬剤開始後2-4週で全身紅斑+口腔・眼・陰部の粘膜びらん+発熱。Nikolsky陽性。高リスク薬: カルバマゼピン(HLA-A*3101)、アロプリノール(HLA-B*5801)、ラモトリギン、ST合剤、oxicam系NSAIDs。被疑薬中止が最優先。',
  },
  {
    id: 'drug_eruption',
    name: '薬疹（紅斑丘疹型）',
    cat: '薬疹',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['erythema', 'papule', 'scattered', 'symmetric', 'new_drug', 'pruritus', 'acute'],
    findings: [],
    redFlags: [],
    nextStep: '被疑薬の中止。軽症: 抗ヒスタミン薬+ステロイド外用。再受診基準: 口内・目・陰部の痛み出現、皮疹の急速拡大→SJS/TEN除外のため即受診。',
    link: '/docs/200-dermatitis/l270-drug-eruption',
    comment: '薬剤開始1-2週で全身に対称性の紅斑丘疹。掻痒を伴う。被疑薬中止で数日-2週で軽快。SJS/TENへの移行に常に注意。',
  },
  {
    id: 'secondary_syphilis',
    name: '第2期梅毒（バラ疹）',
    cat: '性感染症',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['erythema', 'papule', 'scattered', 'palms_soles', 'sexual_risk', 'asymptomatic', 'trunk'],
    findings: ['palm_sole_rash', 'lymphadenopathy'],
    redFlags: ['palm_sole_rash'],
    nextStep: 'RPR/TPHA即日提出。治療: ベンジルペニシリンベンザチン筋注（ステルイズ240万単位 単回）or アモキシシリン内服（1500mg/日 分3 4週間）。性行為歴の聴取が困難でも検査を提出せよ。',
    link: '/docs/255-Sexual-Infect/a513-secondary-syphilis',
    comment: '手掌・足底を含む全身の紅斑（バラ疹）。無痒性が特徴。「The Great Imitator」=あらゆる皮疹を模倣。性行為歴に関わらず手掌・足底の紅斑はRPR/TPHA提出。',
  },
  {
    id: 'purpura_vasculitis',
    name: '紫斑（血管炎・ITP・DIC）',
    cat: '血液 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['purpura', 'fever', 'joint_pain'],
    findings: ['fever_high'],
    redFlags: ['purpura'],
    nextStep: 'CBC+凝固（PT/APTT/FDP/D-dimer）即日。DIC疑い→搬送。IgA血管炎→腎機能確認。',
    link: null,
    comment: '圧迫で消退しない紅斑=紫斑。触知可能紫斑=血管炎。紫斑+発熱→髄膜炎菌・DICを除外。下肢優位+関節痛+腹痛→IgA血管炎。',
  },
  {
    id: 'viral_exanthem',
    name: 'ウイルス性発疹症（麻疹・風疹・その他）',
    cat: '感染症（ウイルス）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['erythema', 'papule', 'scattered', 'fever', 'acute', 'symmetric', 'trunk'],
    findings: ['lymphadenopathy', 'fever_high'],
    redFlags: [],
    nextStep: '麻疹・風疹は感染症法上の届出義務あり（五類・全数・直ちに届出）。抗原検査/IgM。空気感染予防策（麻疹）。',
    link: null,
    comment: '発熱+全身性紅斑丘疹で想起。麻疹: Koplik斑→顔面から体幹へ下降性に拡大。風疹: 後頸部リンパ節腫脹が特徴。成人風疹→妊婦への先天性風疹症候群リスク。伝染性紅斑（リンゴ病）: 頬の蝶形紅斑+レース状皮疹。',
  },
  {
    id: 'herpes_simplex',
    name: '単純ヘルペス（HSV）',
    cat: '感染症（ウイルス）',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['vesicle', 'pain', 'burning', 'recurrent', 'acute'],
    findings: [],
    redFlags: [],
    nextStep: '口唇ヘルペス: バラシクロビル500mg×2回/日×5日間。性器ヘルペス: バラシクロビル500mg×2回/日×5-10日間。PIT療法（初期症状出現時の患者判断内服）も選択肢。再受診基準: 広範囲の拡大、免疫低下者は即受診。',
    link: null,
    comment: '口唇・陰部の再発性水疱が典型。初感染は重症化しうる。HSVカポジ水痘様発疹症（アトピー患者）は広範囲に拡大→搬送。',
  },
  // === 高頻度 ===
  {
    id: 'eczema',
    name: '湿疹・皮膚炎',
    cat: '皮膚炎',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['erythema', 'papule', 'scale', 'pruritus', 'chronic', 'recurrent', 'lichenification'],
    findings: [],
    redFlags: [],
    nextStep: 'ステロイド外用（部位別ランク選択は疾患ページ参照）+保湿指導。ステロイド開始前にKOH提出（外注: 白癬除外。結果判明前は抗真菌外用を併用or処方保留を検討）。再受診基準: 2-4週で改善なし→診断再考。',
    link: '/docs/200-dermatitis/l309-eczema-hand-eczema',
    comment: '最も頻度が高い皮疹。掻痒+紅斑+鱗屑が基本パターン。慢性化で苔癬化。',
  },
  {
    id: 'atopic_dermatitis',
    name: 'アトピー性皮膚炎',
    cat: '皮膚炎',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['erythema', 'papule', 'pruritus', 'flexural', 'chronic', 'recurrent', 'lichenification', 'symmetric'],
    findings: [],
    redFlags: [],
    nextStep: 'ステロイド外用+保湿（部位別ランク選択は疾患ページ参照）。急性期→導入療法。寛解後→プロアクティブ療法。総IgE・TARC。再受診基準: 2-4週で改善なし→治療見直し。',
    link: '/docs/200-dermatitis/l209-ad-induction-phase',
    comment: '掻痒+左右対称+屈側優位（肘窩・膝窩・頸部）+慢性再発性。アトピー素因（喘息・鼻炎・家族歴）。',
  },
  {
    id: 'contact_dermatitis',
    name: '接触皮膚炎',
    cat: '皮膚炎',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['erythema', 'vesicle', 'pruritus', 'contact_area', 'acute'],
    findings: [],
    redFlags: [],
    nextStep: '原因物質の同定・除去。ステロイド外用（部位別ランク選択は疾患ページ参照）。パッチテスト（皮膚科紹介）。再受診基準: 2-4週で改善なし→再受診。',
    link: '/docs/200-dermatitis/l239-contact-dermatitis',
    comment: '接触部位に一致した紅斑・水疱。金属・化粧品・洗剤・植物・ゴム手袋が原因。接触歴の詳細聴取が鑑別の鍵。',
  },
  {
    id: 'urticaria',
    name: '蕁麻疹',
    cat: '皮膚炎',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['wheal', 'pruritus', 'acute', 'scattered', 'recurrent'],
    findings: [],
    redFlags: [],
    nextStep: '抗ヒスタミン薬。24時間以内に消退する膨疹が特徴。個疹が24時間以上持続→蕁麻疹様血管炎を疑え→皮膚科紹介（生検は当院不可）。アナフィラキシー徴候（呼吸困難・血圧低下）→アドレナリン0.3mg筋注+搬送。',
    link: '/docs/200-dermatitis/l509-urticaria',
    comment: '一過性の膨疹（24h以内に消退）が本態。慢性（6週以上）は特発性が多い。個疹が24h以上持続+紫斑を残す→蕁麻疹様血管炎→皮膚科紹介。',
  },
  {
    id: 'tinea',
    name: '白癬（体部・足部）',
    cat: '皮膚感染',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['erythema', 'scale', 'annular', 'pruritus'],
    findings: ['central_clearing', 'koh_positive'],
    redFlags: [],
    nextStep: 'KOH直接鏡検（外注）。陽性→抗真菌外用（ルリコン等）。爪白癬→内服（テルビナフィン等、肝機能注意）。',
    link: '/docs/210-skin-infect',
    comment: '辺縁隆起+中心治癒の環状紅斑が典型。KOH陽性で確定。ステロイドで修飾されるとtinea incognitoに。',
  },
  {
    id: 'tinea_incognito',
    name: 'Tinea incognito（ステロイド修飾白癬）',
    cat: '皮膚感染',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['erythema', 'scale', 'steroid_worsened', 'recurrent'],
    findings: ['koh_positive'],
    redFlags: ['steroid_worsened'],
    nextStep: 'ステロイド外用を中止。KOH直接鏡検（外注）。KOH結果判明前はステロイド再開せず抗真菌外用を先行処方。陽性→抗真菌外用に切り替え。',
    link: '/docs/210-skin-infect',
    comment: '前医のステロイド外用で「一時改善→再燃」を繰り返す=tinea incognitoを最も疑うべきパターン。KOH検査が唯一の確定手段。',
  },
  {
    id: 'psoriasis',
    name: '乾癬',
    cat: '皮膚炎',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['erythema', 'scale', 'extensor', 'chronic', 'symmetric', 'papule', 'recurrent'],
    findings: ['auspitz_sign', 'koebner'],
    redFlags: [],
    nextStep: 'ステロイド外用+VD3外用。中等症以上→皮膚科紹介（光線療法・生物学的製剤）。',
    link: '/docs/200-dermatitis/l400-psoriasis-vulgaris',
    comment: '銀白色鱗屑を伴う境界明瞭な紅色局面。肘・膝・頭皮・臀部に好発。Auspitz sign。Koebner現象。爪病変（点状陥凹・油滴徴候）。関節症性乾癬の合併あり。',
  },
  {
    id: 'seborrheic_dermatitis',
    name: '脂漏性皮膚炎',
    cat: '皮膚炎',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 1,
    symptoms: ['erythema', 'scale', 'seborrheic', 'chronic', 'pruritus'],
    findings: [],
    redFlags: [],
    nextStep: '抗真菌外用（ケトコナゾール）+弱いステロイド外用。頭皮→抗真菌シャンプー。',
    link: '/docs/200-dermatitis/l219-seborrheic-dermatitis',
    comment: '頭皮・眉間・鼻唇溝・耳後部の脂漏部位に好発する紅斑+油性鱗屑。Malasseziaの関与。',
  },
  {
    id: 'herpes_zoster',
    name: '帯状疱疹',
    cat: '感染症（ウイルス）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['vesicle', 'dermatomal', 'pain', 'burning', 'acute'],
    findings: [],
    redFlags: [],
    nextStep: 'バラシクロビル1000mg×3回/日×7日間（72h以内に開始、腎機能障害時は減量）。三叉神経第1枝（Hutchinson徴候）→眼部帯状疱疹→即日眼科紹介。再受診基準: 対側への水疱拡大（播種性）、眼症状（視力低下・充血）→即受診。',
    link: '/docs/210-skin-infect',
    comment: '片側のデルマトームに沿う水疱+神経痛。皮疹前2-3日は前駆痛のみ。免疫低下者で播種性リスク→搬送。',
  },
  {
    id: 'erythema_multiforme',
    name: '多形紅斑',
    cat: '免疫反応',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['erythema', 'palms_soles', 'symmetric', 'acute', 'papule', 'fever'],
    findings: ['target_lesion'],
    redFlags: [],
    nextStep: '標的状病変が特徴。HSV感染後が最多原因。軽症→対症療法。粘膜病変→SJSとの鑑別（皮膚科紹介）。',
    link: null,
    comment: '同心円状のtarget lesion。四肢末端・手掌に好発。EM minor: 粘膜病変軽度。EM major: 粘膜病変高度→SJSとの鑑別必要→皮膚科紹介。',
  },
  {
    id: 'ctcl',
    name: '皮膚T細胞リンパ腫（CTCL/菌状息肉症）',
    cat: '悪性腫瘍',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 3,
    symptoms: ['erythema', 'scale', 'treatment_resistant', 'chronic', 'trunk'],
    findings: [],
    redFlags: ['treatment_resistant'],
    nextStep: '6ヶ月以上の治療抵抗性紅斑→皮膚科紹介（生検: 当院不可）。',
    link: null,
    comment: '非露光部（bathing trunk分布）に好発する慢性紅斑。poikilodermaが手がかり。湿疹・乾癬と誤診されやすい。',
  },
  {
    id: 'scabies',
    name: '疥癬',
    cat: '皮膚感染（寄生虫）',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['papule', 'pruritus', 'scattered', 'linear'],
    findings: ['dermoscopy_finding'],
    redFlags: [],
    nextStep: 'ダーモスコピーで疥癬トンネル確認。イベルメクチン内服（約200μg/kg空腹時単回、2週後に再投与）or フェノトリン（スミスリンローション5%）外用。同居者の同時治療。治療後も2-4週は掻痒が持続することがある（死んだダニへの反応、治療失敗ではない）。',
    link: null,
    comment: '夜間に増悪する激しい掻痒+指間・手首・腋窩・陰部の丘疹。ダーモスコピーでdelta wing sign。高齢者施設でアウトブレイク。角化型疥癬は感染力が強い。',
  },
  {
    id: 'insect_bite',
    name: '虫刺症',
    cat: '外因性',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['papule', 'pruritus', 'acute', 'scattered'],
    findings: [],
    redFlags: [],
    nextStep: 'ステロイド外用+抗ヒスタミン薬。蜂刺傷: アナフィラキシー徴候（数時間以内の呼吸困難・全身蕁麻疹・血圧低下）→アドレナリン0.3mg筋注+搬送。過去の蜂刺傷反応歴を聴取。',
    link: null,
    comment: '露出部の掻痒性丘疹。蚊・ダニ・ノミ・蜂が原因。紅斑中心に刺し口がヒント。',
    alwaysShow: true,
  },
  {
    id: 'pityriasis_rosea',
    name: 'ジベルばら色粃糠疹',
    cat: '皮膚炎',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['erythema', 'scale', 'trunk', 'symmetric', 'acute'],
    findings: [],
    redFlags: [],
    nextStep: '自然軽快（6-8週）。対症療法のみ。梅毒バラ疹との鑑別にRPR/TPHA提出を検討。',
    link: null,
    comment: '先行するherald patch→1-2週後に体幹にクリスマスツリー様の小紅斑多発。若年者に多い。6-8週で軽快。梅毒バラ疹との鑑別が重要。',
  },
];

export const RED_FLAGS = [
  {
    conditions: ['nikolsky_positive'],
    message: 'Nikolsky sign陽性: SJS/TEN/天疱瘡を疑う。被疑薬即時中止。即日皮膚科紹介/搬送。',
    severity: 'critical',
  },
  {
    conditions: ['mucosal_erosion'],
    message: '粘膜びらん（口腔・眼・陰部）: SJS/TENを疑う。被疑薬中止+即日皮膚科紹介。',
    severity: 'critical',
  },
  {
    conditions: ['purpura'],
    message: '紫斑: DIC・血管炎・ITP・髄膜炎菌を考慮。CBC+凝固即日。発熱を伴えば髄膜炎菌性敗血症→即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['palm_sole_rash'],
    message: '手掌・足底の紅斑: 第2期梅毒（バラ疹）を除外せよ。RPR/TPHA提出。',
    severity: 'warning',
  },
  {
    conditions: ['steroid_worsened'],
    message: 'ステロイドで悪化/再燃: tinea incognito（ステロイド修飾白癬）を疑う。ステロイド中止+KOH検査（外注）。',
    severity: 'warning',
  },
  {
    conditions: ['treatment_resistant'],
    message: '6ヶ月以上治療抵抗性: CTCL（菌状息肉症）を除外。皮膚科紹介（生検）。',
    severity: 'warning',
  },
  {
    conditions: ['mucosal'],
    message: '粘膜症状あり: SJS/TEN・天疱瘡・梅毒を鑑別。詳細な粘膜診察+皮膚科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['fever'],
    message: '発熱+皮疹: 薬疹(SJS/TEN)・ウイルス性発疹症（麻疹は届出義務）・血管炎を鑑別。全身評価。',
    severity: 'warning',
  },
];
