/**
 * Diagnostic Booster — Undifferentiated Syncope Data
 */

export const SYMPTOMS = [
  // 状況
  { id: 'exertional', label: '労作中・運動中に発症', cat: '状況' },
  { id: 'standing', label: '長時間立位中', cat: '状況' },
  { id: 'postural', label: '起立時に発症', cat: '状況' },
  { id: 'supine', label: '臥位・座位で発症', cat: '状況' },
  { id: 'post_micturition', label: '排尿後', cat: '状況' },
  { id: 'post_cough', label: '咳嗽後', cat: '状況' },
  { id: 'neck_rotation', label: '頸部回旋・圧迫時', cat: '状況' },
  { id: 'postprandial', label: '食後', cat: '状況' },
  // 前駆症状
  { id: 'prodrome_present', label: '前駆症状あり（冷汗・嘔気・眼前暗黒感）', cat: '前駆症状' },
  { id: 'no_prodrome', label: '前駆症状なし（突然の意識消失）', cat: '前駆症状' },
  // 随伴
  { id: 'palpitations', label: '動悸', cat: '随伴症状' },
  { id: 'chest_pain', label: '胸痛', cat: '随伴症状' },
  { id: 'dyspnea', label: '呼吸困難', cat: '随伴症状' },
  { id: 'seizure_witnessed', label: 'けいれん目撃', cat: '随伴症状' },
  { id: 'headache', label: '頭痛', cat: '随伴症状' },
  { id: 'focal_neuro', label: '神経巣症状（麻痺・失語）', cat: '随伴症状' },
  // 回復
  { id: 'rapid_recovery', label: '速やかに回復（秒〜分）', cat: '回復' },
  { id: 'prolonged_confusion', label: '意識回復に時間がかかる（遷延）', cat: '回復' },
  // リスク
  { id: 'cardiac_history', label: '心疾患の既往（弁膜症・心不全・不整脈）', cat: 'リスク' },
  { id: 'family_sudden_death', label: '家族歴に若年突然死', cat: 'リスク' },
  { id: 'antihypertensive', label: '降圧薬・利尿薬・α遮断薬使用中', cat: 'リスク' },
  { id: 'qt_prolonging_drug', label: 'QT延長誘発薬使用中', cat: 'リスク' },
  { id: 'recurrent', label: '再発性（複数回）', cat: 'リスク' },
  { id: 'young_athlete', label: '若年者・アスリート', cat: 'リスク' },
];

export const FINDINGS = [
  // ECG所見
  { id: 'ecg_qtc_prolonged', label: 'QTc延長（男>440ms 女>460ms）', triggers: ['no_prodrome', 'qt_prolonging_drug', 'family_sudden_death'] },
  { id: 'ecg_delta_wave', label: 'δ波+短PR間隔（WPW症候群）', triggers: ['palpitations', 'no_prodrome', 'young_athlete'] },
  { id: 'ecg_brugada', label: 'V1-V3 coved型ST上昇（Brugada型）', triggers: ['no_prodrome', 'family_sudden_death', 'supine'] },
  { id: 'ecg_av_block', label: '房室ブロック（II度以上）', triggers: ['no_prodrome', 'cardiac_history'] },
  { id: 'ecg_bundle_branch', label: '脚ブロック（二束ブロック・交代性）', triggers: ['no_prodrome', 'cardiac_history'] },
  { id: 'ecg_abnormal_q', label: '異常Q波（陳旧性心筋梗塞）', triggers: ['cardiac_history', 'chest_pain'] },
  { id: 'ecg_st_change', label: 'ST変化（虚血性）', triggers: ['chest_pain', 'exertional'] },
  // 聴診
  { id: 'systolic_ejection_murmur', label: '収縮期駆出性雑音', triggers: ['exertional', 'cardiac_history'] },
  { id: 'valsalva_murmur_increase', label: 'Valsalva手技で雑音増強', triggers: ['exertional', 'young_athlete'] },
  // 起立性
  { id: 'orthostatic_drop', label: '起立性血圧低下（収縮期≥20 or 拡張期≥10mmHg低下）', triggers: ['postural', 'antihypertensive', 'standing'] },
  // バイタル（常時表示）
  { id: 'irregular_pulse', label: '脈不整', triggers: [] },
  { id: 'bradycardia', label: '徐脈 HR<50', triggers: [] },
  { id: 'hypotension', label: '収縮期血圧<90', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 心原性（Killer Syncope）===
  {
    id: 'aortic_stenosis',
    name: '大動脈弁狭窄症（AS）',
    cat: '構造的心疾患 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['exertional', 'no_prodrome', 'cardiac_history', 'dyspnea'],
    findings: ['systolic_ejection_murmur'],
    redFlags: ['exertional', 'systolic_ejection_murmur'],
    nextStep: '心エコー必須（当院不可→循環器紹介）。労作時失神+収縮期駆出性雑音→AS強く疑う。心エコーまで運動制限指示。',
    link: null,
    comment: '高齢者の労作時失神+収縮期駆出性雑音（頸部に放散）。重症ASは突然死リスクあり。弁置換の適応評価が必要。',
  },
  {
    id: 'hocm',
    name: '肥大型心筋症（HOCM/HCM）',
    cat: '構造的心疾患 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['exertional', 'no_prodrome', 'young_athlete', 'family_sudden_death', 'palpitations'],
    findings: ['systolic_ejection_murmur', 'valsalva_murmur_increase'],
    redFlags: ['exertional', 'family_sudden_death'],
    nextStep: '心エコー必須（当院不可→循環器紹介）。Valsalvaで雑音増強が手がかり。若年アスリートの突然死の最多原因。運動制限指示。',
    link: null,
    comment: '若年者の労作時失神+家族歴（突然死）。Valsalvaで雑音増強は閉塞性HCMを示唆。運動部在籍者は競技復帰に循環器の許可が必要。',
  },
  {
    id: 'arrhythmia_vt_vf',
    name: '致死的不整脈（VT/VF）',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['no_prodrome', 'supine', 'palpitations', 'cardiac_history'],
    findings: ['ecg_abnormal_q', 'ecg_st_change', 'irregular_pulse'],
    redFlags: ['no_prodrome', 'supine'],
    nextStep: '12誘導ECG必須。ECG異常あり→即循環器紹介/搬送。心停止既往なら搬送。',
    link: null,
    comment: '前駆症状なしの突然の意識消失+速やかな回復（→心室性不整脈の自然停止）。臥位での失神は心原性を強く疑う。陳旧性MI+左室機能低下がVT/VFの最大リスク。',
  },
  {
    id: 'complete_av_block',
    name: '完全房室ブロック/洞不全症候群',
    cat: '不整脈 / 緊急',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['no_prodrome', 'cardiac_history', 'recurrent'],
    findings: ['ecg_av_block', 'bradycardia'],
    redFlags: ['bradycardia'],
    nextStep: 'ECGでII度以上のAVブロック/徐脈→即循環器紹介。ペースメーカー適応の可能性。',
    link: null,
    comment: '突然の意識消失+徐脈。Adams-Stokes発作（一過性心停止による失神）。ECGでII度Mobitz II型/III度AVブロック、または洞停止。',
  },
  {
    id: 'long_qt',
    name: 'QT延長症候群',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['no_prodrome', 'family_sudden_death', 'qt_prolonging_drug', 'young_athlete'],
    findings: ['ecg_qtc_prolonged'],
    redFlags: ['ecg_qtc_prolonged', 'family_sudden_death'],
    nextStep: 'QTc延長（男>440ms/女>460ms）→循環器紹介。QT延長誘発薬（マクロライド系・フルオロキノロン系・抗精神病薬・三環系抗うつ薬・抗不整脈薬・制吐薬〔ドンペリドン〕等）の中止/変更。家族スクリーニング。',
    link: null,
    comment: '先天性（遺伝子異常）と後天性（薬剤性・電解質異常）がある。Torsades de Pointes（多形性VT）から心停止に至る。薬剤歴と家族歴が鍵。',
  },
  {
    id: 'wpw',
    name: 'WPW症候群',
    cat: '不整脈',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    resolvedStillDangerous: true,
    symptoms: ['palpitations', 'no_prodrome', 'young_athlete'],
    findings: ['ecg_delta_wave'],
    redFlags: ['ecg_delta_wave'],
    nextStep: 'δ波+短PR間隔→WPW。Af合併時にVFリスク。循環器紹介（カテーテルアブレーション）。',
    link: null,
    comment: '若年者の動悸+失神。ECGでδ波（QRS立ち上がりの鈍い段差）+短PR間隔。偽性陽性あり→循環器で精査。',
  },
  {
    id: 'brugada',
    name: 'Brugada症候群',
    cat: '不整脈 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    resolvedStillDangerous: true,
    symptoms: ['no_prodrome', 'family_sudden_death', 'supine'],
    findings: ['ecg_brugada'],
    redFlags: ['ecg_brugada', 'family_sudden_death'],
    nextStep: 'V1-V3でcoved型ST上昇→Brugada疑い。即循環器紹介。夜間・安静時の失神が特徴。',
    link: null,
    comment: '東南アジア系男性に多い。夜間睡眠中の突然死（ポックリ病との関連）。ECG Type 1（coved型）が診断的。家族内スクリーニング。ICD適応の判断は循環器で。',
  },
  {
    id: 'pulmonary_embolism',
    name: '肺塞栓症',
    cat: '循環器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['dyspnea', 'chest_pain', 'no_prodrome'],
    findings: ['hypotension', 'ecg_st_change'],
    redFlags: ['hypotension', 'dyspnea'],
    nextStep: '失神+呼吸困難+胸痛+DVTリスク→PE（肺塞栓）疑い。D-dimer/造影CTは当院不可→臨床的疑いで搬送。',
    link: null,
    comment: '突然の失神+呼吸困難。massive PEではショック→失神。長期臥床・術後・下肢腫脹・悪性腫瘍がリスク。',
  },
  {
    id: 'acs_syncope',
    name: '急性冠症候群（ACS）',
    cat: '循環器 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['chest_pain', 'no_prodrome', 'cardiac_history', 'dyspnea'],
    findings: ['ecg_st_change', 'hypotension'],
    redFlags: ['chest_pain', 'ecg_st_change'],
    nextStep: '胸痛+失神+ST変化→ACS疑い。即搬送。両上肢血圧で大動脈解離を除外→アスピリン。',
    link: null,
    comment: '下壁MI（右冠動脈閉塞）は徐脈+低血圧を伴いやすく失神の原因になる。広範前壁MIでも心原性ショックで失神。',
  },
  // === 反射性（最多・予後良好）===
  {
    id: 'vasovagal',
    name: '血管迷走神経性失神（VVS）',
    cat: '反射性',
    freq: '極めて高頻度',
    prevalenceWeight: 10,
    severityWeight: 1,
    symptoms: ['prodrome_present', 'standing', 'rapid_recovery', 'young_athlete'],
    findings: [],
    redFlags: [],
    nextStep: '心原性を除外した上での除外診断。ECG正常+典型的前駆症状+誘因あり→VVS。生活指導: 長時間立位回避、前駆症状時のしゃがみ込み・下肢筋ポンプ。安全指導: 原因確定まで運転禁止。入浴は一人で長時間行わない（シャワー推奨）。高所作業・危険機械操作を禁止。再受診基準: 労作時・臥位での再発、外傷を伴う再発→再評価。',
    link: null,
    comment: '最も頻度が高い。長時間立位・疼痛・採血・恐怖などが誘因。前駆症状（冷汗+嘔気+眼前暗黒感）後に意識消失→速やかに回復。若年者に多い。ただし心原性の除外が前提。',
  },
  {
    id: 'situational',
    name: '状況失神（排尿後・咳嗽後・食後）',
    cat: '反射性',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 1,
    symptoms: ['post_micturition', 'post_cough', 'postprandial', 'prodrome_present', 'rapid_recovery'],
    findings: [],
    redFlags: [],
    nextStep: '特定の状況で再現性がある場合→状況失神。心原性除外が前提。誘因回避の生活指導。',
    link: null,
    comment: '排尿時失神（高齢男性・夜間）、咳嗽失神（COPD等）、食後低血圧（高齢者）。再現性のある状況+前駆症状が鑑別の鍵。',
  },
  {
    id: 'carotid_sinus',
    name: '頸動脈洞症候群',
    cat: '反射性',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 2,
    symptoms: ['neck_rotation', 'no_prodrome', 'cardiac_history'],
    findings: ['bradycardia'],
    redFlags: [],
    nextStep: '頸部回旋・圧迫で失神→頸動脈洞症候群疑い。頸動脈洞マッサージ（循環器で実施、当院禁忌）。ペースメーカー適応あり。',
    link: null,
    comment: '高齢男性。髭剃り・ネクタイ締め・頸部回旋で失神。頸動脈洞過敏による心抑制型（徐脈）or血管抑制型（低血圧）。',
  },
  // === 起立性低血圧 ===
  {
    id: 'orthostatic_hypotension',
    name: '起立性低血圧',
    cat: '循環器',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['postural', 'antihypertensive', 'prodrome_present'],
    findings: ['orthostatic_drop'],
    redFlags: [],
    nextStep: '臥位→立位3分後の血圧測定。原因検索: 脱水・消化管出血（黒色便）・副腎不全・薬剤性（降圧薬・利尿薬・α遮断薬・三環系・硝酸薬・抗パーキンソン薬）。安全指導: 原因確定まで運転禁止。入浴注意。再受診基準: 失神の再発、黒色便→即受診。',
    link: '/docs/090-Cardiovascular',
    comment: '起立後に収縮期≥20 or 拡張期≥10mmHg低下。高齢者で最多。降圧薬過量が最も多い原因。黒色便→消化管出血の除外を忘れるな。',
  },
  // === てんかん鑑別 ===
  {
    id: 'epilepsy',
    name: 'てんかん発作（鑑別）',
    cat: '神経',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['seizure_witnessed', 'prolonged_confusion', 'focal_neuro'],
    findings: [],
    redFlags: ['seizure_witnessed'],
    nextStep: 'けいれん目撃+意識回復遷延（数分〜数十分）→てんかんの可能性。脳波（当院不可→神経内科紹介）。MRI紹介。初発けいれんは器質的原因除外が必須。',
    link: null,
    comment: '失神との鑑別: 失神は速やかに回復（秒〜1分）、てんかんは遷延する意識障害+健忘。失神でも数秒のけいれん様運動（convulsive syncope）が起こりうるため、けいれん=てんかんではない。舌側縁の咬傷はてんかんを示唆（先端の咬傷は失神でも起こる）。尿失禁は両者で起こるため鑑別に使えない。ただし高齢者では失神後にも数分のconfusion（post-syncopal confusion）がありうる→遷延のみでてんかんと断定しない。',
  },
  // === その他 ===
  {
    id: 'hypoglycemia',
    name: '低血糖',
    cat: '代謝',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['prodrome_present', 'prolonged_confusion'],
    findings: [],
    redFlags: [],
    nextStep: '血糖測定。低血糖→ブドウ糖投与。インスリン・SU薬使用患者で注意。',
    link: null,
    comment: '低血糖は失神ではなく意識障害（回復に時間がかかる）。冷汗+振戦+空腹感が前駆。DM治療中の患者で発作性に起こる。',
  },
  {
    id: 'stroke_syncope',
    name: '脳血管障害（椎骨脳底動脈系）',
    cat: '脳血管 / 緊急',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 5,
    symptoms: ['focal_neuro', 'headache', 'no_prodrome'],
    findings: ['hypotension'],
    redFlags: ['focal_neuro'],
    nextStep: '神経巣症状あり→脳血管障害疑い。即搬送。※失神の原因として脳血管障害は稀だが、椎骨脳底動脈系の虚血では起こりうる。',
    link: null,
    comment: '失神の原因として脳卒中は稀（<1%）。ただし神経巣症状（片麻痺・構音障害・複視）を伴う場合は除外必須。失神+神経巣症状=脳血管障害として搬送。',
  },
  {
    id: 'drug_induced_syncope',
    name: '薬剤性失神',
    cat: '薬剤性',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['antihypertensive', 'qt_prolonging_drug', 'postural'],
    findings: ['orthostatic_drop', 'ecg_qtc_prolonged', 'bradycardia'],
    redFlags: [],
    nextStep: '被疑薬の同定。降圧薬→起立性低血圧。QT延長誘発薬→不整脈。β遮断薬→徐脈。用量調整or代替薬。',
    link: null,
    comment: '降圧薬過量（起立性低血圧）、QT延長誘発薬（TdP: マクロライド・フルオロキノロン・三環系・ドンペリドン等）、β遮断薬（徐脈）、α遮断薬（血管拡張）、硝酸薬（血管拡張）、PDE5阻害薬（硝酸薬併用で重篤低血圧）、抗パーキンソン薬（起立性低血圧）が主な原因。ポリファーマシーの高齢者で特に注意。',
    alwaysShow: true,
  },
];

export const RED_FLAGS = [
  {
    conditions: ['exertional'],
    message: '労作時失神: 大動脈弁狭窄症（AS）・肥大型心筋症（HOCM）・冠動脈疾患を疑う。心エコーまで運動制限。循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['no_prodrome'],
    message: '前駆症状なしの突然の意識消失: 不整脈（VT/VF・AVブロック・Brugada・QT延長）を強く疑う。12誘導ECG必須。',
    severity: 'critical',
  },
  {
    conditions: ['supine'],
    message: '臥位での失神: 心原性を強く疑う（反射性・起立性では説明できない）。ECG+循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['family_sudden_death'],
    message: '家族歴に若年突然死: WPW・Brugada・QT延長・HCMを疑う。ECG+循環器紹介+家族スクリーニング。',
    severity: 'critical',
  },
  {
    conditions: ['chest_pain'],
    message: '胸痛を伴う失神: ACS・肺塞栓・大動脈解離を疑う。ECG+搬送準備。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_qtc_prolonged'],
    message: 'QTc延長: Torsades de Pointes（多形性VT）→心停止リスク。QT延長誘発薬中止+循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_brugada'],
    message: 'Brugada型ECG: V1-V3 coved型ST上昇。即循環器紹介。ICD適応の判断。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_delta_wave'],
    message: 'δ波+短PR: WPW症候群。Af合併時にVFリスク。循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['ecg_av_block'],
    message: '高度房室ブロック: ペースメーカー適応。循環器紹介。',
    severity: 'critical',
  },
  {
    conditions: ['systolic_ejection_murmur'],
    message: '収縮期駆出性雑音: AS・HCMを疑う。心エコー（当院不可→循環器紹介）。',
    severity: 'warning',
  },
  {
    conditions: ['bradycardia'],
    message: '徐脈 HR<50: 洞不全症候群・房室ブロックを考慮。ECG確認+循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['hypotension'],
    message: '低血圧（収縮期<90）: ショック・出血・PE・心原性を考慮。輸液+搬送準備。',
    severity: 'warning',
  },
  {
    conditions: ['seizure_witnessed'],
    message: 'けいれん目撃: てんかん vs convulsive syncope（失神に伴う短時間のけいれん）の鑑別。意識回復が遷延するならてんかん寄り。神経内科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['focal_neuro'],
    message: '神経巣症状: 脳血管障害を除外。即搬送。',
    severity: 'critical',
  },
  {
    conditions: ['palpitations'],
    message: '失神直前の動悸: 不整脈原性失神（VT・SVT・Af）を疑う。12誘導ECG必須。',
    severity: 'warning',
  },
  {
    conditions: ['cardiac_history'],
    message: '構造的心疾患/不整脈の既往あり: ESC高リスク。心原性失神の可能性高い。ECG+循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['ecg_bundle_branch'],
    message: '二束ブロック/交代性脚ブロック: 高度伝導障害への進展リスク。循環器紹介。',
    severity: 'warning',
  },
  {
    conditions: ['ecg_abnormal_q'],
    message: '異常Q波（陳旧性MI）: VT/VFリスクの基盤。循環器紹介。',
    severity: 'warning',
  },
];
