/**
 * Diagnostic Booster — Involuntary Weight Loss Data
 */

export const SYMPTOMS = [
  // 食欲
  { id: 'appetite_preserved', label: '食欲保持（食べているのに痩せる）', cat: '食欲' },
  { id: 'appetite_decreased', label: '食欲低下', cat: '食欲' },
  { id: 'appetite_increased', label: '食欲亢進', cat: '食欲' },
  { id: 'dysphagia', label: '嚥下障害（飲み込みにくい）', cat: '食欲' },
  { id: 'early_satiety', label: '早期満腹感', cat: '食欲' },
  { id: 'nausea', label: '悪心・嘔吐', cat: '食欲' },
  // 消化器
  { id: 'abdominal_pain', label: '腹痛', cat: '消化器' },
  { id: 'diarrhea', label: '下痢', cat: '消化器' },
  { id: 'steatorrhea', label: '脂肪便（脂っぽい・浮く便）', cat: '消化器' },
  { id: 'bloody_stool', label: '血便・黒色便', cat: '消化器' },
  // 全身
  { id: 'fever', label: '発熱', cat: '全身' },
  { id: 'night_sweats', label: '盗汗', cat: '全身' },
  { id: 'fatigue', label: '倦怠感', cat: '全身' },
  { id: 'polydipsia', label: '口渇・多飲・多尿', cat: '全身' },
  { id: 'tremor', label: '動悸・手指振戦・発汗過多', cat: '全身' },
  { id: 'cough', label: '咳嗽', cat: '全身' },
  { id: 'lymphadenopathy', label: 'リンパ節腫脹', cat: '全身' },
  { id: 'jaundice', label: '黄疸', cat: '全身' },
  // 精神
  { id: 'depressed_mood', label: '気分の落ち込み・意欲低下', cat: '精神' },
  { id: 'body_image', label: '体型へのこだわり（痩せ願望）', cat: '精神' },
  // 社会的
  { id: 'elderly', label: '高齢者（75歳以上）', cat: '社会的' },
  { id: 'living_alone', label: '独居', cat: '社会的' },
  { id: 'cooking_difficulty', label: '買い物・調理が困難', cat: '社会的' },
  { id: 'denture_problem', label: '義歯不適合・口腔問題', cat: '社会的' },
  { id: 'economic', label: '経済的問題', cat: '社会的' },
  // リスク
  { id: 'smoking', label: '喫煙歴', cat: 'リスク' },
  { id: 'alcohol', label: '大量飲酒歴', cat: 'リスク' },
  { id: 'over_5pct', label: '6ヶ月で5%以上の減少', cat: 'リスク' },
];

export const FINDINGS = [
  { id: 'hepatomegaly', label: '肝腫大', triggers: ['jaundice', 'abdominal_pain', 'alcohol'] },
  { id: 'splenomegaly', label: '脾腫', triggers: ['lymphadenopathy', 'fever'] },
  { id: 'abdominal_mass', label: '腹部腫瘤', triggers: ['abdominal_pain', 'early_satiety'] },
  { id: 'ascites', label: '腹水', triggers: ['abdominal_pain', 'jaundice'] },
  { id: 'supraclavicular_ln', label: '鎖骨上窩リンパ節', triggers: ['lymphadenopathy'] },
  { id: 'thyroid_enlargement', label: '甲状腺腫大', triggers: ['tremor', 'appetite_increased'] },
  { id: 'hyperpigmentation', label: '色素沈着', triggers: ['fatigue'] },
  { id: 'fobt_positive', label: '便潜血陽性', triggers: ['bloody_stool', 'abdominal_pain'] },
  // 常時表示
  { id: 'cachexia', label: 'るいそう（明らかな栄養不良）', triggers: [] },
  { id: 'low_albumin', label: '低アルブミン血症', triggers: [] },
];

export const DIFFERENTIALS = [
  // === 悪性腫瘍 ===
  {
    id: 'gi_cancer',
    name: '消化器癌（胃癌・大腸癌・膵癌）',
    cat: '悪性腫瘍',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 5,
    symptoms: ['appetite_decreased', 'abdominal_pain', 'bloody_stool', 'early_satiety', 'jaundice', 'over_5pct', 'dysphagia', 'nausea'],
    findings: ['abdominal_mass', 'hepatomegaly', 'ascites', 'fobt_positive', 'supraclavicular_ln', 'cachexia', 'low_albumin'],
    redFlags: ['fobt_positive', 'supraclavicular_ln', 'abdominal_mass'],
    nextStep: '便潜血2回法。CEA/CA19-9（50歳以上）。便潜血陽性→消化器内科紹介（下部内視鏡）。嚥下障害/早期満腹感→上部消化管内視鏡紹介。黄疸→肝胆膵精査（CT紹介）。再受診基準: 黄疸・血便・嚥下困難の悪化→即受診。',
    link: null,
    comment: '食欲低下+体重減少+腹部症状=消化器癌を最優先で除外。胃癌: 早期満腹感。大腸癌: 便潜血・便通変化。膵癌: 黄疸・背部痛。肝硬変（サルコペニア）も体重減少の原因。腫瘍マーカー陰性でも悪性は除外不可→画像・内視鏡が必要。',
  },
  {
    id: 'lung_cancer',
    name: '肺癌',
    cat: '悪性腫瘍',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 5,
    symptoms: ['cough', 'smoking', 'appetite_decreased', 'over_5pct', 'fatigue'],
    findings: ['supraclavicular_ln', 'cachexia'],
    redFlags: ['supraclavicular_ln'],
    nextStep: '胸部X線。異常影→CT施設紹介。喫煙歴+50歳以上+体重減少は高リスク。再受診基準: 血痰・呼吸困難悪化→即受診。',
    link: null,
    comment: '喫煙歴+慢性咳嗽+体重減少で疑う。胸部X線が初期スクリーニング。2週間以上の血痰は紹介閾値を下げる。',
  },
  {
    id: 'malignant_lymphoma',
    name: '悪性リンパ腫',
    cat: '悪性腫瘍',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 5,
    symptoms: ['lymphadenopathy', 'fever', 'night_sweats', 'over_5pct', 'fatigue'],
    findings: ['splenomegaly', 'supraclavicular_ln'],
    redFlags: ['supraclavicular_ln'],
    nextStep: 'LDH+sIL-2R+CBC。B症状（38℃以上の発熱+盗汗+6ヶ月で10%以上の体重減少）→血液内科紹介（生検）。再受診基準: リンパ節増大・高熱持続→即受診。',
    link: null,
    comment: 'B症状+無痛性リンパ節腫脹。sIL-2R正常でも否定不可（インドレント型で低感度）。',
  },
  // === 内分泌・代謝 ===
  {
    id: 'hyperthyroidism',
    name: '甲状腺機能亢進症',
    cat: '内分泌',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['appetite_increased', 'appetite_preserved', 'tremor', 'diarrhea', 'fatigue'],
    findings: ['thyroid_enlargement'],
    redFlags: [],
    nextStep: 'TSH+FT3/FT4。TSH低値→甲状腺機能亢進症。食欲があるのに痩せる=本疾患を最優先で疑え。再受診基準: 高熱+頻脈+意識障害（甲状腺クリーゼ）→即搬送。',
    link: '/docs/130-endocrine',
    comment: '食欲亢進+体重減少+動悸+手指振戦+発汗過多+暑がり。「食べているのに痩せる」の代表的原因。',
  },
  {
    id: 'diabetes_uncontrolled',
    name: '糖尿病（新規・コントロール不良）',
    cat: '代謝',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 3,
    symptoms: ['polydipsia', 'appetite_preserved', 'fatigue', 'over_5pct'],
    findings: [],
    redFlags: [],
    nextStep: 'HbA1c+随時血糖。口渇+多飲+多尿+体重減少=DM。1型は急速な体重減少+ケトアシドーシスリスク。再受診基準: 嘔吐・意識障害（DKA/HHS）→即受診。',
    link: '/docs/110-diabetes',
    comment: '口渇+多飲+多尿で疑う。食べているのに痩せるパターン。高齢者のHHS（高浸透圧高血糖状態）は致死的。',
  },
  {
    id: 'adrenal_insufficiency',
    name: '副腎不全',
    cat: '内分泌',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['appetite_decreased', 'fatigue', 'nausea', 'over_5pct'],
    findings: ['hyperpigmentation', 'low_albumin'],
    redFlags: ['hyperpigmentation'],
    nextStep: '早朝コルチゾール。低Na+好酸球増多+低血圧+色素沈着→Addison病。再受診基準: 嘔吐・下痢・発熱時のシックデイ→即受診（副腎クリーゼリスク→即搬送）。',
    link: null,
    comment: '見逃されやすい。ステロイド長期使用歴→二次性副腎不全。色素沈着は一次性の特徴。',
  },
  // === 消化器 ===
  {
    id: 'malabsorption',
    name: '吸収不良症候群',
    cat: '消化器',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['diarrhea', 'steatorrhea', 'appetite_preserved', 'abdominal_pain', 'fatigue'],
    findings: ['low_albumin'],
    redFlags: [],
    nextStep: '脂肪便+体重減少→吸収不良。セリアック病（抗tTG抗体、日本では稀）、慢性膵炎（膵外分泌不全→エラスターゼ）、短腸症候群。消化器紹介。',
    link: null,
    comment: '食べているのに痩せる+脂肪便（脂っぽく浮く便）が手がかり。慢性膵炎（飲酒歴）→膵酵素補充。セリアック病は日本では稀だがグローバル化で増加。',
  },
  {
    id: 'ibd',
    name: '炎症性腸疾患（IBD: UC/CD）',
    cat: '消化器',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['bloody_stool', 'diarrhea', 'abdominal_pain', 'fever', 'over_5pct'],
    findings: [],
    redFlags: ['bloody_stool'],
    nextStep: '血便+慢性下痢+体重減少→IBD疑い。消化器内科紹介（下部内視鏡）。CBC+CRP+アルブミン。再受診基準: 大量血便・高熱・腹痛増悪→即受診。',
    link: null,
    comment: '若年者の血便+慢性下痢+体重減少。UC: 粘血便、直腸から連続性。CD: 腹痛+下痢+肛門病変、非連続性。',
  },
  {
    id: 'chronic_pancreatitis',
    name: '慢性膵炎',
    cat: '消化器',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 3,
    symptoms: ['abdominal_pain', 'steatorrhea', 'appetite_decreased', 'alcohol', 'over_5pct'],
    findings: ['low_albumin'],
    redFlags: [],
    nextStep: '飲酒歴+上腹部痛+脂肪便→慢性膵炎。膵酵素（リパーゼ）。CT紹介（膵石・石灰化）。膵酵素補充療法。禁酒指導。',
    link: null,
    comment: 'アルコール多飲歴+反復する上腹部痛+脂肪便。膵外分泌不全→脂肪吸収障害。膵癌のリスク因子でもある。',
  },
  // === 感染症 ===
  {
    id: 'tuberculosis',
    name: '結核',
    cat: '感染症',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    symptoms: ['cough', 'fever', 'night_sweats', 'over_5pct', 'fatigue'],
    findings: [],
    redFlags: [],
    nextStep: '胸部X線。2週間以上の咳嗽+盗汗+体重減少→結核疑い。保健所相談+専門医療機関紹介。再受診基準: 血痰・呼吸困難→即受診。',
    link: null,
    comment: '日本は結核中蔓延国。高齢者・免疫低下者で特に注意。',
  },
  {
    id: 'hiv',
    name: 'HIV感染症',
    cat: '感染症',
    freq: '低頻度',
    prevalenceWeight: 2,
    severityWeight: 4,
    symptoms: ['over_5pct', 'fever', 'diarrhea', 'fatigue', 'lymphadenopathy'],
    findings: [],
    redFlags: [],
    nextStep: 'HIV抗原抗体検査。リスク行動歴の聴取。AIDS wasting syndromeは進行期。',
    link: null,
    comment: '非意図的体重減少+慢性下痢+持続性リンパ節腫脹で想起。リスク行動歴がなくても検査閾値は低く。',
  },
  // === 精神 ===
  {
    id: 'depression',
    name: 'うつ病',
    cat: '精神科',
    freq: '高頻度',
    prevalenceWeight: 8,
    severityWeight: 3,
    symptoms: ['appetite_decreased', 'depressed_mood', 'fatigue', 'over_5pct'],
    findings: [],
    redFlags: [],
    nextStep: 'PHQ-2≧3→PHQ-9で詳細評価。器質的疾患を除外した上で。精神科/心療内科紹介。再受診基準: 希死念慮→精神科緊急。',
    link: '/docs/170-psychiatry',
    comment: '食欲低下+体重減少+気分の落ち込み+意欲低下。高齢者のうつ病は身体症状が前面に出やすい（仮面うつ病）。器質的疾患の除外が先。',
  },
  {
    id: 'eating_disorder',
    name: '摂食障害（神経性やせ症）',
    cat: '精神科',
    freq: '低〜中頻度',
    prevalenceWeight: 3,
    severityWeight: 4,
    symptoms: ['body_image', 'appetite_decreased', 'over_5pct'],
    findings: ['cachexia', 'low_albumin'],
    redFlags: ['cachexia'],
    nextStep: '若年女性+痩せ願望+低体重（BMI＜17.5）→神経性やせ症。電解質（低K→致死的不整脈リスク）。精神科紹介。再受診基準: 失神・徐脈・低K→即受診。',
    link: null,
    comment: '体型へのこだわり+食事制限/嘔吐/過度の運動。BMI＜17.5が診断基準。低K→QT延長→心停止リスク。死亡率は精神疾患中最高。',
  },
  // === 社会的 ===
  {
    id: 'frailty_social',
    name: 'フレイル・社会的要因',
    cat: '社会的',
    freq: '高頻度（高齢者）',
    prevalenceWeight: 8,
    severityWeight: 2,
    symptoms: ['elderly', 'living_alone', 'cooking_difficulty', 'denture_problem', 'economic', 'appetite_decreased', 'fatigue'],
    findings: ['cachexia', 'low_albumin'],
    redFlags: [],
    nextStep: '器質的疾患を除外した上で社会的要因を評価。義歯調整（歯科紹介）。配食サービス・介護保険申請・地域包括支援センター連携。栄養補助食品（ONS）の導入。再受診基準: 体重減少が進行→月1回の体重モニタリング。',
    link: null,
    comment: '高齢者の体重減少では社会的要因が最大原因のことが少なくない。独居・買い物困難・調理困難・義歯不適合・経済的問題。検査の前に生活状況を確認せよ。',
    alwaysShow: true,
  },
  // === 薬剤性 ===
  {
    id: 'drug_induced',
    name: '薬剤性体重減少',
    cat: '薬剤性',
    freq: '中頻度',
    prevalenceWeight: 5,
    severityWeight: 2,
    symptoms: ['appetite_decreased', 'nausea'],
    findings: [],
    redFlags: [],
    nextStep: '被疑薬の同定。メトホルミン（消化器症状）・GLP-1受容体作動薬（食欲抑制）・SGLT2阻害薬（尿糖排泄）・トピラマート・SSRI/SNRI・抗癌剤が代表。用量調整or代替薬。再受診基準: 減量/中止後も体重減少持続→器質的疾患精査。',
    link: null,
    comment: 'メトホルミンやGLP-1RAは意図的に使用されることもあるが、非意図的な過度の体重減少は用量調整が必要。SGLT2iは尿糖排泄で体重減少。',
    alwaysShow: true,
  },
];

export const RED_FLAGS = [
  {
    conditions: ['over_5pct'],
    message: '6ヶ月で5%以上の非意図的体重減少: 悪性腫瘍の確率が有意に上昇。系統的精査を開始。',
    severity: 'warning',
  },
  {
    conditions: ['fobt_positive'],
    message: '便潜血陽性: 消化管悪性腫瘍を除外。消化器内科紹介（下部内視鏡）。',
    severity: 'critical',
  },
  {
    conditions: ['supraclavicular_ln'],
    message: '鎖骨上窩リンパ節: 悪性腫瘍の確率が最も高い。速やかに精査紹介。',
    severity: 'critical',
  },
  {
    conditions: ['abdominal_mass'],
    message: '腹部腫瘤: 消化器癌を疑う。CT紹介。',
    severity: 'critical',
  },
  {
    conditions: ['jaundice'],
    message: '黄疸+体重減少: 膵癌・胆管癌・肝硬変を疑う。肝機能+ビリルビン+CT紹介。閉塞性黄疸は緊急精査。',
    severity: 'critical',
  },
  {
    conditions: ['dysphagia'],
    message: '嚥下障害+体重減少: 食道癌・胃癌を除外。上部消化管内視鏡紹介。',
    severity: 'warning',
  },
  {
    conditions: ['bloody_stool'],
    message: '血便・黒色便: 消化管出血・悪性腫瘍。消化器内科紹介。',
    severity: 'warning',
  },
  {
    conditions: ['cachexia'],
    message: 'るいそう（明らかな栄養不良）: 悪性腫瘍・摂食障害・進行期疾患を考慮。早急な精査。',
    severity: 'warning',
  },
  {
    conditions: ['hyperpigmentation'],
    message: '色素沈着: 副腎不全（Addison病）を疑う。早朝コルチゾール。',
    severity: 'warning',
  },
];
